(()=>{'use strict';
const KEY='rupais-world-kitty-diary-v1',D=document,$=s=>D.querySelector(s),$$=s=>[...D.querySelectorAll(s)];
$('.diary-header')?.style.setProperty('display','none','important');$('.diary-nav')?.style.setProperty('display','none','important');$('.workspace')?.style.setProperty('display','block','important');$('.main-panel')?.style.setProperty('width','100%','important');
const initial={drafts:[],pages:[],working:null};let store=load(),mode='new',activeId=null,readerId=null,photos=[];
function load(){try{return{...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(initial)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(store));counts()}
function uid(){return`diary_${Date.now()}_${Math.random().toString(36).slice(2,7)}`}
function nowFields(){const n=new Date(),local=new Date(n-n.getTimezoneOffset()*60000).toISOString();return{date:local.slice(0,10),time:local.slice(11,16)}}
function blank(){return{id:null,title:'',body:'',mood:'😊 Happy',weather:'🌙 Clear Night',style:'blush',photos:[],...nowFields()}}
function value(){syncRefToHidden();return{id:activeId,title:$('#entryTitle').value.trim(),body:$('#entryBody').innerHTML,mood:$('#entryMood').value,weather:$('#entryWeather').value,date:$('#entryDate').value,time:$('#entryTime').value,style:$('#paperWrap').dataset.style,photos:[...photos],updatedAt:new Date().toISOString()}}
function fill(e=blank(),nextMode='new') {mode=nextMode;activeId=e.id||null;$('#entryTitle').value=e.title||'';$('#entryBody').innerHTML=e.body||'';$('#entryMood').value=e.mood||'😊 Happy';$('#entryWeather').value=e.weather||'🌙 Clear Night';$('#entryDate').value=e.date||nowFields().date;$('#entryTime').value=e.time||nowFields().time;photos=[...(e.photos||[])];setStyle(e.style||'blush');renderPhotos();stats();$('#editorTitle').textContent=nextMode==='page'?'Edit your diary page ✨':nextMode==='draft'?'Continue your draft ✨':'Write a new memory ✨';$('#publishPage').childNodes[0].textContent=nextMode==='page'?'↻ Update Page':'＋ Create Diary Page';$('#publishPage small').textContent=nextMode==='page'?'Save changes to this page':'Add it to My Pages';syncHiddenToRef();show('editor')}
function syncHiddenToRef(){if(!$('#refBody'))return;$('#refTitle').value=$('#entryTitle').value;$('#refBody').innerHTML=$('#entryBody').innerHTML;$('#refMood').value=$('#entryMood').value;$('#refWeather').value=$('#entryWeather').value;$('#refDate').value=$('#entryDate').value;$('#refTime').value=$('#entryTime').value;$('#refBody').style.fontFamily=$('#entryBody').style.fontFamily||'Kalam';$('#referenceStage');renderRefPhotos()}
function syncRefToHidden(){if(!$('#refBody')||$('.reference-stage')?.hidden)return;$('#entryTitle').value=$('#refTitle').value;$('#entryBody').innerHTML=$('#refBody').innerHTML;$('#entryMood').value=$('#refMood').value;$('#entryWeather').value=$('#refWeather').value;$('#entryDate').value=$('#refDate').value;$('#entryTime').value=$('#refTime').value}
function renderRefPhotos(){const tray=$('#refPhotos');if(!tray)return;tray.innerHTML=photos.length?`<img src="${photos.at(-1)}" alt="Diary photo">`:''}
function show(name){$$('.view').forEach(x=>x.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.nav-action').forEach(x=>x.classList.toggle('active',x.dataset.view===name));if(name==='drafts')renderDrafts();if(name==='pages')renderPages();scrollTo({top:0,behavior:'smooth'})}
function counts(){$('#draftCount').textContent=`${store.drafts.length} saved`;$('#pageCount').textContent=`${store.pages.length} finished`}
function plain(html){const x=D.createElement('div');x.innerHTML=html;return x.textContent.trim()}
function stats(){const content=plain($('#entryBody').innerHTML),n=content.split(/\s+/).filter(Boolean).length;$('#wordCount').textContent=`${n} word${n===1?'':'s'}`;$('#readTime').textContent=`${Math.max(1,Math.ceil(n/200))} min read`;if($('#statsWords'))$('#statsWords').textContent=n;if($('#statsChars'))$('#statsChars').textContent=content.length}
function notify(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function saved(message='All changes saved'){const s=$('#saveState');s.textContent=`✓ ${message}`;setTimeout(()=>s.textContent='✓ All changes saved',1500)}
function upsert(list,item){const i=list.findIndex(x=>x.id===item.id);if(i<0)list.unshift(item);else list[i]=item}
function saveDraft(silent=false){let e=value();if(!plain(e.body)&&!e.title&&!e.photos.length){if(!silent)notify('Write a little something first ♥');return}if(mode==='page'){store.working=e;persist();if(!silent)notify('Editing page · changes kept safely');return}e.id=activeId||uid();e.createdAt=store.drafts.find(x=>x.id===e.id)?.createdAt||e.updatedAt;upsert(store.drafts,e);activeId=e.id;mode='draft';store.working=null;persist();if(!silent)notify('Draft saved under Drafts ♥');saved('Draft saved')}
function publish(){const e=value();if(!plain(e.body)&&!e.title){notify('Add a title or write your memory first ♥');return}if(mode==='page'){const old=store.pages.find(x=>x.id===activeId);upsert(store.pages,{...old,...e,id:activeId});notify('Diary page updated ♥')}else{e.id=uid();e.createdAt=e.updatedAt;store.pages.unshift(e);if(activeId)store.drafts=store.drafts.filter(x=>x.id!==activeId);activeId=e.id;mode='page';notify('Your diary page was created ✨')}store.working=null;persist();saved(mode==='page'?'Page saved':'Saved');renderPages();setTimeout(()=>openReader(activeId),350)}
function card(e,type){const article=D.createElement('article');article.className='entry-card';const text=plain(e.body).slice(0,150)||'A new memory is waiting here…';article.innerHTML=`<div class="entry-card-preview" data-style="${e.style||'blush'}">${text}</div><h3>${escape(e.title||'Untitled memory')}</h3><div class="entry-card-meta"><span>${formatDate(e.date)}</span><span>${e.mood||''}</span></div><div class="entry-card-actions"><button data-open>${type==='draft'?'Continue':'Read'}</button><button data-delete>Delete</button></div>`;article.querySelector('[data-open]').onclick=()=>type==='draft'?fill(e,'draft'):openReader(e.id);article.querySelector('[data-delete]').onclick=ev=>{ev.stopPropagation();if(!confirm(`Delete this ${type}?`))return;store[type==='draft'?'drafts':'pages']=store[type==='draft'?'drafts':'pages'].filter(x=>x.id!==e.id);persist();type==='draft'?renderDrafts():renderPages();notify('Moved out of your diary')};return article}
function empty(label){return`<div class="empty-state"><div style="font-size:46px">${label==='drafts'?'📁':'📖'}</div><h3>No ${label} yet</h3><p>${label==='drafts'?'Saved unfinished entries will appear here.':'Create your first finished diary page.'}</p></div>`}
function renderDrafts(){const g=$('#draftGrid');g.innerHTML='';if(!store.drafts.length)g.innerHTML=empty('drafts');else store.drafts.forEach(x=>g.append(card(x,'draft')))}
function renderPages(){const g=$('#pagesGrid');g.innerHTML='';if(!store.pages.length)g.innerHTML=empty('pages');else store.pages.forEach(x=>g.append(card(x,'page')))}
function formatDate(date){if(!date)return'';return new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T12:00`))}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function readerHTML(e){return`<h1>${escape(e.title||'Dear Diary…')}</h1><div class="reader-meta"><span>${formatDate(e.date)} · ${e.time||''}</span><span>${e.mood}</span><span>${e.weather}</span></div><div class="reader-content">${e.body}</div>${e.photos?.length?`<div class="reader-photos">${e.photos.map(p=>`<img src="${p}" alt="Diary memory">`).join('')}</div>`:''}`}
function openReader(id){const e=store.pages.find(x=>x.id===id);if(!e)return;readerId=id;$('#readerPaper').dataset.style=e.style||'blush';$('#readerPaper').innerHTML=readerHTML(e);show('reader')}
function setStyle(style){$('#paperWrap').dataset.style=style;if($('.reference-stage'))$('.reference-stage').dataset.pageStyle=style;$$('button[data-style]').forEach(x=>x.classList.toggle('active',x.dataset.style===style))}
function renderPhotos(){const tray=$('#photoTray');tray.innerHTML='';photos.forEach((src,i)=>{const c=D.createElement('div');c.className='photo-card';c.innerHTML=`<img src="${src}" alt="Attached diary memory"><button aria-label="Remove photo">×</button>`;c.querySelector('button').onclick=()=>{photos.splice(i,1);renderPhotos();changed()};tray.append(c)});renderRefPhotos()}
function insertText(text){$('#entryBody').focus();D.execCommand('insertText',false,text);changed()}
function cycleStyle(){const styles=['blush','night','lavender','sage'],current=$('#paperWrap').dataset.style;setStyle(styles[(styles.indexOf(current)+1)%styles.length]);changed()}
function lastPhotoCard(){return $('#photoTray .photo-card:last-child')}
function changed(){stats();$('#saveState').textContent='● Saving…';clearTimeout(changed.timer);changed.timer=setTimeout(()=>{if($('#autoSave').checked){if(mode==='page'){store.working=value();persist()}else saveDraft(true);saved()}else $('#saveState').textContent='Unsaved changes'},1500)}
$$('.nav-action[data-view]').forEach(b=>b.onclick=()=>b.dataset.view==='editor'?fill(blank()):show(b.dataset.view));$$('[data-write]').forEach(b=>b.onclick=()=>fill(blank()));$('#newEntry').onclick=()=>fill(blank());$('#saveDraft').onclick=()=>saveDraft();$('#publishPage').onclick=publish;$('#backToPages').onclick=()=>show('pages');$('#editPage').onclick=()=>{const e=store.pages.find(x=>x.id===readerId);if(e)fill(e,'page')};
$('#previewPage').onclick=()=>{const e=value();$('#previewPaper').dataset.style=e.style;$('#previewPaper').innerHTML=readerHTML(e);$('#previewDialog').showModal()};$('.dialog-close').onclick=()=>$('#previewDialog').close();$('#previewDialog').onclick=e=>{if(e.target===$('#previewDialog'))e.target.close()};
$$('[data-command]').forEach(b=>b.onclick=()=>{D.execCommand(b.dataset.command,false,null);$('#entryBody').focus();changed()});$$('[data-insert]').forEach(b=>b.onclick=()=>{D.execCommand('insertText',false,b.dataset.insert);$('#entryBody').focus();changed()});$('#fontPicker').onchange=e=>{$('#entryBody').style.fontFamily=e.target.value;changed()};$$('button[data-style]').forEach(b=>b.onclick=()=>{setStyle(b.dataset.style);changed()});$$('[data-font]').forEach(b=>b.onclick=()=>{$('#entryBody').style.fontFamily=b.dataset.font;$$('[data-font]').forEach(x=>x.classList.toggle('active',x===b));changed()});
function addPhotoFile(f,input){if(!f)return;if(f.size>2_000_000){notify('Please choose a photo under 2 MB');return}const r=new FileReader;r.onload=()=>{photos.push(r.result);renderPhotos();changed()};r.readAsDataURL(f);input.value=''}
$('#photoInput').onchange=e=>addPhotoFile(e.target.files[0],e.target);$('#refPhotoInput').onchange=e=>addPhotoFile(e.target.files[0],e.target);
$('#voiceButton').onclick=()=>{const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){notify('Voice diary is not supported in this browser');return}const r=new Speech;r.lang='en-IN';r.interimResults=false;$('#refBody').focus();$('#voiceButton').textContent='● Listening…';r.onresult=e=>{D.execCommand('insertText',false,`${e.results[0][0].transcript} `);syncRefToHidden();changed()};r.onend=()=>$('#voiceButton').textContent='🎙️ Voice Diary';r.start()};
$('#voiceButtonBottom').onclick=()=>$('#voiceButton').click();
$$('[data-reference-view]').forEach(button=>button.onclick=()=>button.dataset.referenceView==='editor'?fill(blank()):show(button.dataset.referenceView));
$$('[data-reference-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.referenceAction;if(action==='save')$('#saveDraft').click();if(action==='preview')$('#previewPage').click();if(action==='publish')$('#publishPage').click()});
$$('[data-ref-command]').forEach(button=>button.onclick=()=>{$('#refBody').focus();D.execCommand(button.dataset.refCommand,false,null);syncRefToHidden();changed()});
$$('[data-reference-insert]').forEach(button=>button.onclick=()=>{$('#refBody').focus();D.execCommand('insertText',false,button.dataset.referenceInsert);syncRefToHidden();changed()});
$$('[data-reference-font]').forEach(button=>button.onclick=()=>{$('#refBody').style.fontFamily=button.dataset.referenceFont;$('#entryBody').style.fontFamily=button.dataset.referenceFont;changed()});
$$('[data-reference-style]').forEach(button=>button.onclick=()=>{setStyle(button.dataset.referenceStyle);changed()});
$$('[data-reference-tool]').forEach(button=>button.onclick=()=>{const tool=button.dataset.referenceTool;if(tool==='voice')$('#voiceButton').click();if(tool==='templates'||tool==='styles')scrollTo({top:document.body.scrollHeight,behavior:'smooth'});if(tool==='handwriting')$('#refBody').focus()});
['input','keyup','paste'].forEach(event=>$('#refBody').addEventListener(event,()=>{syncRefToHidden();changed()}));$$('.reference-field').forEach(field=>field.addEventListener('change',()=>{syncRefToHidden();changed()}));
const quickButtons=$$('.quick-tools button');quickButtons.find(b=>b.textContent.includes('Templates')).onclick=()=>insertText('Dear Diary... ♥\n\nToday I feel...\n\nThe best part of my day was...\n\nI am grateful for...');quickButtons.find(b=>b.textContent.includes('Page Styles')).onclick=cycleStyle;quickButtons.find(b=>b.textContent.includes('Handwriting')).onclick=()=>{$('#fontPicker').selectedIndex=($('#fontPicker').selectedIndex+1)%$('#fontPicker').options.length;$('#entryBody').style.fontFamily=$('#fontPicker').value;changed()};
$$('.diary-nav .decorative').forEach(b=>{if(b.textContent.includes('Calendar'))b.onclick=()=>{$('#entryDate').focus();$('#entryDate').showPicker?.()};if(b.textContent.includes('Search'))b.onclick=()=>{const q=prompt('Search this diary entry');if(q)window.find(q)};if(b.textContent.includes('Memory Box'))b.onclick=()=>show('pages')});
const objectButtons=$$('.object-tools>div button');objectButtons.forEach(b=>{if(b.textContent.includes('Move'))b.onclick=()=>{const p=$('#paperWrap');p.dataset.photoMoved=p.dataset.photoMoved?'':'1';p.style.setProperty('--photo-x',p.dataset.photoMoved?'18px':'0');p.style.setProperty('--photo-y',p.dataset.photoMoved?'10px':'0')};if(b.textContent.includes('Resize'))b.onclick=()=>{const p=$('#paperWrap'),large=p.dataset.photoLarge!=='1';p.dataset.photoLarge=large?'1':'0';p.style.setProperty('--photo-width',large?'215px':'190px');p.style.setProperty('--photo-height',large?'250px':'225px')};if(b.textContent.includes('Rotate'))b.onclick=()=>{const p=$('#paperWrap'),angle=Number(p.dataset.photoAngle||5)+15;p.dataset.photoAngle=angle;p.style.setProperty('--photo-rotation',`${angle}deg`)};if(b.textContent.includes('Delete'))b.onclick=()=>{if(photos.length){photos.pop();renderPhotos();changed()}};if(b.textContent.includes('Duplicate'))b.onclick=()=>{if(photos.length){photos.push(photos.at(-1));renderPhotos();changed()}}});
const editButtons=$$('.object-tools>button');editButtons.forEach(b=>{if(b.textContent.includes('Existing'))b.onclick=()=>show('pages');if(b.textContent.includes('Add New'))b.onclick=()=>fill(blank());if(b.textContent.includes('Update'))b.onclick=publish});
$$('.page-nav button').forEach(b=>{if(b.textContent.includes('Single'))b.onclick=()=>{$('#paperWrap').style.maxWidth='';notify('Single page view')};if(b.textContent.includes('Two Page'))b.onclick=()=>{$('#paperWrap').style.maxWidth='760px';notify('Two page view')};if(b.textContent.includes('Scroll'))b.onclick=()=>{$('#entryBody').style.overflowY='auto';notify('Scroll view')};if(b.textContent.includes('First Page'))b.onclick=()=>store.pages.length&&openReader(store.pages.at(-1).id);if(b.textContent.includes('Last Page'))b.onclick=()=>store.pages.length&&openReader(store.pages[0].id)});
$$('[data-page-move]').forEach(b=>b.onclick=()=>window.scrollBy({top:b.dataset.pageMove==='up'?-180:180,behavior:'smooth'}));
$$('.add-entry button').forEach(b=>{if(b.textContent.includes('Video'))b.onclick=()=>insertText(' 🎬 ');if(b.textContent.includes('Audio Note'))b.onclick=()=>insertText(' 🎵 ');if(b.textContent.includes('Doodle'))b.onclick=()=>insertText(' ✏️ ');if(b.textContent.includes('Location'))b.onclick=()=>insertText(' 📍 ');if(b.textContent.includes('Note Card'))b.onclick=()=>insertText('\n🗒️ Note: ')});
['input','keyup','paste'].forEach(event=>$('#entryBody').addEventListener(event,changed));$$('.entry-details input,.entry-details select').forEach(x=>x.addEventListener('change',changed));
counts();fill(store.working||blank(),store.working?.id&&store.pages.some(x=>x.id===store.working.id)?'page':'new');
})();
