const STORAGE_KEY='rupaiModernHistory:v1';
const chapterSeed=[
  {id:'rise-of-british-power',number:1,title:'The Rise of British Power',description:'From traders to rulers: the British expansion in India.',topics:12,difficulty:'Medium',progress:80},
  {id:'revolt-of-1857',number:2,title:'Revolt of 1857',description:'The first war of independence and its impact.',topics:10,difficulty:'Medium',progress:70},
  {id:'social-religious-reforms',number:3,title:'Social & Religious Reforms',description:"Reforms that awakened India's social conscience.",topics:11,difficulty:'Easy',progress:90},
  {id:'indian-national-movement',number:4,title:'Indian National Movement',description:'The struggle for freedom and unity.',topics:15,difficulty:'Hard',progress:75},
  {id:'gandhian-era',number:5,title:'Gandhian Era',description:'Non-violence, truth and mass movements that changed history.',topics:10,difficulty:'Medium',progress:85},
  {id:'world-wars-impact',number:6,title:'World Wars & Their Impact',description:'Global wars and their effect on India.',topics:9,difficulty:'Medium',progress:60},
  {id:'india-after-independence',number:7,title:'India After Independence',description:'Challenges, progress and nation building.',topics:12,difficulty:'Medium',progress:70},
  {id:'constitution-democracy',number:8,title:'Constitution & Democracy',description:'Framing of the Constitution and democratic values.',topics:9,difficulty:'Easy',progress:80},
  {id:'five-year-plans',number:9,title:'Five-Year Plans & Economic Growth',description:'Planning the future for a stronger India.',topics:8,difficulty:'Medium',progress:65},
  {id:'science-technology-space',number:10,title:'Science, Technology & Space Achievements',description:"India's journey in science and space.",topics:9,difficulty:'Medium',progress:75},
  {id:'india-21st-century',number:11,title:'India in the 21st Century',description:'A new era of opportunities, challenges and global leadership.',topics:12,difficulty:'Hard',progress:60}
];
function readState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch{return {}}}
let saved=readState(),chapters=chapterSeed.map(chapter=>({...chapter,...(saved.chapters?.[chapter.id]||{}),favorite:window.RupaiFavorites?.has(`modern-${chapter.id}`)||Boolean(saved.chapters?.[chapter.id]?.favorite)})),toastTimer;
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify({chapters:Object.fromEntries(chapters.map(chapter=>[chapter.id,{progress:chapter.progress,favorite:chapter.favorite,lastOpened:chapter.lastOpened||'',downloaded:Boolean(chapter.downloaded)}]))}))}
function showToast(message){const toast=document.querySelector('#toast');clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function chapterRoute(chapter){return `modern-history.html?chapter=${encodeURIComponent(chapter.id)}`}
function openChapter(chapter){chapter.lastOpened=new Date().toISOString();persist();location.href=chapterRoute(chapter)}
function openTool(tool,chapter){const panel={'Notes':'My Notes','Videos':'Videos','Maps':'Maps','Ask Curio':'Ask Curio'}[tool];location.href=`index.html?${new URLSearchParams({panel,subject:'History',period:'Modern History',chapter:chapter.title,context:chapter.title})}`}
function sparkle(control){const layer=document.querySelector('#interactionLayer'),left=parseFloat(control.style.left),top=parseFloat(control.style.top),width=parseFloat(control.style.width),height=parseFloat(control.style.height);for(let i=0;i<8;i++){const dot=document.createElement('i');dot.className='sparkle';dot.style.left=`${left+width/2}%`;dot.style.top=`${top+height/2}%`;dot.style.setProperty('--dx',`${Math.cos(i)*24}px`);dot.style.setProperty('--dy',`${Math.sin(i)*24}px`);layer.appendChild(dot);setTimeout(()=>dot.remove(),700)}}
function toggleFavorite(chapter,control){chapter.favorite=!chapter.favorite;const item={id:`modern-${chapter.id}`,title:chapter.title,description:chapter.description,type:'Chapter',subject:'History',chapter:'Modern History',meta:`${chapter.topics} topics · ${chapter.progress}%`,icon:'🇮🇳',route:chapterRoute(chapter)};chapter.favorite?window.RupaiFavorites?.add(item):window.RupaiFavorites?.remove(item.id);persist();sparkle(control);showToast(chapter.favorite?'Added to Favorites ❤️':'Removed from Favorites')}
function addSurface({x,y,w,h,label,href,onClick,className='ui-tile',tilt='0deg'}){const layer=document.querySelector('#interactionLayer'),control=document.createElement(href?'a':'button');if(href)control.href=href;else control.type='button';control.className=className;control.setAttribute('aria-label',label);Object.assign(control.style,{left:`${x/10.24}%`,top:`${y/15.36}%`,width:`${w/10.24}%`,height:`${h/15.36}%`,backgroundSize:`${1024/w*100}% ${1536/h*100}%`,backgroundPosition:`${x/(1024-w)*100}% ${y/(1536-h)*100}%`});control.style.setProperty('--tilt',tilt);if(onClick)control.addEventListener('click',()=>onClick(control));layer.appendChild(control);return control}
function addMask({x,y,w,h}){const mask=document.createElement('span');mask.className='chapter-mask';Object.assign(mask.style,{left:`${x/10.24}%`,top:`${y/15.36}%`,width:`${w/10.24}%`,height:`${h/15.36}%`});document.querySelector('#interactionLayer').appendChild(mask)}
function buildInteractions(){
  const side=[['Home','index.html'],['All Subjects','subjects.html'],['My Notes','index.html?panel=My%20Notes'],['Favorites','favorites.html'],['Bookmark','index.html?panel=Bookmarks'],['Curiosity World','index.html?panel=Curiosity%20World'],['Ask Curio','index.html?panel=Ask%20Curio'],['Calculator','calculator/rupais-world-calculator-live.html'],['Daily Goals','index.html?panel=Daily%20Goals'],['Progress','index.html?panel=Study%20Progress'],['Achievements','index.html?panel=Achievements'],['Settings','index.html?panel=Settings'],['Theme','index.html?panel=Themes'],['Help and Support','index.html?panel=Help%20%26%20Support']];side.forEach(([label,href],index)=>addSurface({x:7,y:194+index*70,w:159,h:66,label,href}));
  addSurface({x:895,y:20,w:58,h:58,label:'Search Modern History',onClick:()=>{renderSearch();document.querySelector('#searchDialog').showModal();document.querySelector('#searchQuery').focus()}});
  addSurface({x:959,y:20,w:57,h:58,label:'Modern History menu',onClick:()=>document.querySelector('#menuDialog').showModal()});
  [['Tables',197,333,166],['Squares',390,333,171],['Cubes',583,333,170],['Mixed Challenge',772,333,224]].forEach(([label,x,y,w])=>addSurface({x,y,w,h:57,label,href:'calculator/rupais-world-calculator-live.html'}));
  [[185,410,151],[336,410,148],[484,410,182],[666,410,157],[823,410,184]].forEach(([x,y,w],index)=>addSurface({x,y,w,h:78,label:['Total Chapters','Topics','Total Study Time','Your Score','Your Streak'][index],className:'stat-tile'}));
  const rects=[[187,499,385,163],[586,499,418,163],[187,673,385,155],[586,673,418,155],[187,837,385,139],[586,837,418,139],[187,987,385,139],[586,987,418,139],[187,1135,385,134],[586,1135,418,134]];
  rects.forEach((rect,index)=>{const [x,y,w,h]=rect,chapter=chapters[index];addMask({x,y,w,h});addSurface({x,y,w,h,label:`Open ${chapter.title}`,className:'chapter-tile',tilt:x<500?'2.2deg':'-2.2deg',onClick:()=>openChapter(chapter)});addSurface({x:x+w-40,y:y+5,w:36,h:37,label:`Favorite ${chapter.title}`,className:'chapter-control ui-tile',onClick:control=>toggleFavorite(chapter,control)});const toolY=y+h-36,toolWidth=(w*.56)/4;['Notes','Videos','Maps','Ask Curio'].forEach((tool,n)=>addSurface({x:x+6+n*toolWidth,y:toolY,w:toolWidth,h:32,label:`${tool}: ${chapter.title}`,className:'chapter-control ui-tile',onClick:()=>openTool(tool,chapter)}));addSurface({x:x+w-102,y:y+h-40,w:98,h:36,label:`Continue ${chapter.title}`,className:'chapter-control ui-tile',onClick:()=>openChapter(chapter)})});
  const last=chapters[10];addMask({x:187,y:1278,w:544,h:106});addSurface({x:187,y:1278,w:544,h:106,label:`Open ${last.title}`,className:'chapter-tile',onClick:()=>openChapter(last)});addSurface({x:747,y:1278,w:258,h:106,label:'Ask Curio, your Modern History friend',className:'chapter-control ui-tile',onClick:()=>openTool('Ask Curio',last)});
  addSurface({x:187,y:1396,w:817,h:91,label:'Start Mixed Challenge',href:'calculator/rupais-world-calculator-live.html'});
  const bottom=[['Home','index.html'],['Subjects','subjects.html'],['Curio','index.html?panel=Ask%20Curio'],['Calculator','calculator/rupais-world-calculator-live.html'],['Notes','index.html?panel=My%20Notes'],['Profile','index.html?panel=Profile']];bottom.forEach(([label,href],index)=>addSurface({x:index*(1024/6),y:1488,w:1024/6,h:48,label,href}));
}
function resultButton(chapter){return `<button type="button" data-chapter="${chapter.id}"><strong>${chapter.number}. ${chapter.title}</strong><small>${chapter.description} · ${chapter.difficulty} · ${chapter.progress}%</small></button>`}
function renderSearch(value=''){const q=value.trim().toLowerCase(),results=chapters.filter(chapter=>!q||[chapter.title,chapter.description,'notes videos maps images'].join(' ').toLowerCase().includes(q));document.querySelector('#searchResults').innerHTML=results.map(resultButton).join('')||'<p>No Modern History result found.</p>'}
function filtered(){const form=new FormData(document.querySelector('#filterForm')),status=form.get('status'),difficulty=form.get('difficulty');return chapters.filter(chapter=>(difficulty==='all'||chapter.difficulty===difficulty)&&(status==='all'||status==='completed'&&chapter.progress===100||status==='not-started'&&chapter.progress===0||status==='learning'&&chapter.progress>0&&chapter.progress<100||status==='favorite'&&chapter.favorite))}
function sorted(){const mode=document.querySelector('#sortBy').value;return [...chapters].sort((a,b)=>mode==='progress'?b.progress-a.progress:mode==='recent'?String(b.lastOpened||'').localeCompare(String(a.lastOpened||'')):mode==='alphabetical'?a.title.localeCompare(b.title):a.number-b.number)}
function wireDialogs(){document.querySelectorAll('.dialog-x').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));document.querySelector('#searchForm').addEventListener('submit',event=>{event.preventDefault();renderSearch(document.querySelector('#searchQuery').value)});document.querySelector('#searchQuery').addEventListener('input',event=>renderSearch(event.target.value));document.querySelector('#filterForm').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#filterResults').innerHTML=filtered().map(resultButton).join('')||'<p>No chapter matches this filter.</p>'});document.querySelector('#sortForm').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#sortResults').innerHTML=sorted().map(resultButton).join('')});document.querySelectorAll('.result-list').forEach(list=>list.addEventListener('click',event=>{const button=event.target.closest('[data-chapter]');if(button){const chapter=chapters.find(item=>item.id===button.dataset.chapter);if(chapter)openChapter(chapter)}}));document.querySelector('.menu-list').addEventListener('click',async event=>{const button=event.target.closest('[data-menu]');if(!button)return;const action=button.dataset.menu;if(action==='filter'){document.querySelector('#menuDialog').close();document.querySelector('#filterDialog').showModal()}else if(action==='sort'){document.querySelector('#menuDialog').close();document.querySelector('#sortDialog').showModal()}else if(action==='download'){chapters.forEach(chapter=>chapter.downloaded=true);persist();showToast('Modern History chapters downloaded')}else if(action==='share'){try{if(navigator.share)await navigator.share({title:'Modern History | Rupai’s World',url:location.href});else{await navigator.clipboard.writeText(location.href);showToast('Page link copied')}}catch{showToast('Share cancelled')}}else if(action==='bookmark'){localStorage.setItem('rupaiModernHistoryBookmark','true');showToast('Modern History bookmarked 🔖')}else if(action==='revision'){location.href='index.html?panel=Revision%20Mode&subject=History&period=Modern%20History'}})}
function wireMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const page=document.querySelector('.modern-page'),cards=[...document.querySelectorAll('.chapter-tile')],controls=[...document.querySelectorAll('.chapter-tile,.ui-tile,.stat-tile')];let frame=0,lastEvent;page.addEventListener('pointermove',event=>{lastEvent=event;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;cards.forEach(card=>{const rect=card.getBoundingClientRect(),near=lastEvent.clientX>=rect.left-45&&lastEvent.clientX<=rect.right+45&&lastEvent.clientY>=rect.top-45&&lastEvent.clientY<=rect.bottom+45;if(!near){card.classList.remove('proximity-active');return}const nx=Math.max(-.5,Math.min(.5,(lastEvent.clientX-rect.left)/rect.width-.5)),ny=Math.max(-.5,Math.min(.5,(lastEvent.clientY-rect.top)/rect.height-.5));card.style.setProperty('--move-x',`${nx*11}px`);card.style.setProperty('--move-y',`${-12+ny*4}px`);card.style.setProperty('--move-rx',`${-ny*15}deg`);card.style.setProperty('--move-ry',`${nx*15}deg`);card.classList.add('proximity-active')})})});page.addEventListener('pointerleave',()=>cards.forEach(card=>card.classList.remove('proximity-active')));controls.forEach(control=>control.addEventListener('pointerdown',event=>{const rect=page.getBoundingClientRect(),ripple=document.createElement('i');ripple.className='motion-ripple';ripple.style.left=`${(event.clientX-rect.left)/rect.width*100}%`;ripple.style.top=`${(event.clientY-rect.top)/rect.height*100}%`;document.querySelector('#interactionLayer').appendChild(ripple);setTimeout(()=>ripple.remove(),600)}))}
buildInteractions();wireDialogs();wireMotion();
