const assert=require('assert'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');let raw=null;const window={localStorage:{getItem:()=>raw,setItem:(_,v)=>raw=v},dispatchEvent(){}};const c=vm.createContext({window,localStorage:window.localStorage,crypto:crypto.webcrypto,CustomEvent:function(){},console,URLSearchParams});for(const f of ['studio/store.js','studio/curio-runtime-service.js','studio/adaptive-learning-service.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);const S=window.TeachCurioStore,R=window.TeachCurioRuntime,A=window.TeachCurioAdaptive,s=S.read();
s.projects.push({id:'lesson1',title:'Adaptive Science',subject:'Science'});s.lessonDrafts.push({id:'draft1',projectId:'lesson1',sections:[{id:'main',type:'main_explanation',title:'Explanation',content:{english:'Normal English explanation',hinglish:'Hinglish explanation'}}]});s.learningEnhancements.push({id:'enh1',projectId:'lesson1',blocks:[{id:'memory',type:'memory_tricks',currentContent:{english:'Remember the cycle.'}},{id:'example',type:'real_life_examples',currentContent:{english:'A practical example.'}},{id:'summary',type:'quick_summary',currentContent:{english:'A short recap.'}}]});s.educationalVisuals.push({id:'diagram1',projectId:'lesson1',category:'diagram',title:'Cycle diagram',description:'Stages',altText:'Cycle stages',reviewStatus:'approved'});s.quizzes.push({id:'quiz1',projectId:'lesson1',title:'Science Quiz'});s.quizQuestions.push({id:'question1',quizId:'quiz1',prompt:'Question'});s.curioTeachingPlans.push({id:'base',projectId:'lesson1',title:'Base Plan',status:'approved',createdAt:'2026-01-01'});['introduction','definition','main_explanation','example','diagram','memory_trick','quiz','summary'].forEach((stepType,i)=>s.curioTeachingSteps.push({id:`s${i}`,planId:'base',stepType,order:i,title:stepType,purpose:stepType,required:!['diagram'].includes(stepType)}));S.write(s);
assert.equal(A.mastery('new_student','lesson1').level,'not_started');assert.equal(A.difficulty('new_student','lesson1').mode,'simple');
A.saveProfile('visual_student',{learningStyle:'visual',preferredLanguage:'hinglish',readingLevel:'simple_hinglish',accessibility:{largeText:true,highContrast:true,reducedMotion:true,simplifiedUi:true,captionFirst:true}});const visualPlan=A.adaptPlan('lesson1','visual_student','base'),visualSteps=S.read().curioTeachingSteps.filter(x=>x.planId===visualPlan.id).sort((a,b)=>a.order-b.order);assert.equal(visualSteps[0].stepType,'diagram');assert(A.delivery('visual_student').accessibility.largeText);assert.equal(A.delivery('visual_student').language,'hinglish');
A.saveProfile('reading_student',{learningStyle:'reading',preferredLanguage:'english',readingLevel:'detailed_english'});const readingPlan=A.adaptPlan('lesson1','reading_student','base'),readingSteps=S.read().curioTeachingSteps.filter(x=>x.planId===readingPlan.id).sort((a,b)=>a.order-b.order);assert(['introduction','definition','main_explanation'].includes(readingSteps[0].stepType));
A.saveProfile('practice_student',{learningStyle:'practice'});const practicePlan=A.adaptPlan('lesson1','practice_student','base'),practiceSteps=S.read().curioTeachingSteps.filter(x=>x.planId===practicePlan.id).sort((a,b)=>a.order-b.order);assert(['example','quiz'].includes(practiceSteps[0].stepType));
let failed=A.start('lesson1','weak_student','base');failed=R.jump(failed.session.id,failed.steps.find(x=>x.stepType==='quiz').id);failed=A.quizResult(failed.session.id,{score:35,correct:1,wrong:3,skipped:1});assert(['memory_trick','example'].includes(failed.currentStep.stepType));assert.equal(A.mastery('weak_student','lesson1').level,'needs_revision');assert(A.dashboard('weak_student').weakTopics.length===1);assert(S.read().adaptiveDecisions.some(x=>x.studentId==='weak_student'&&x.action==='remediation'));
let passed=A.start('lesson1','strong_student','base');passed=R.jump(passed.session.id,passed.steps.find(x=>x.stepType==='quiz').id);passed=A.quizResult(passed.session.id,{score:90,correct:4,wrong:0,skipped:0});assert.equal(A.mastery('strong_student','lesson1').level,'good');assert(S.read().adaptiveDecisions.some(x=>x.studentId==='strong_student'&&x.action==='continue'));
let resumed=A.start('lesson1','resume_student','base');resumed=R.pause(resumed.session.id);assert.equal(R.latest('lesson1').session.status,'paused');resumed=R.resume(resumed.session.id);assert.equal(resumed.session.status,'in_progress');const dash=A.dashboard('visual_student');assert(dash.decisions.some(x=>x.type==='plan_order'));console.log('Adaptive learning tests passed: visual, reading, practice, mastery, weak topics, quiz fail/pass, resume, language, accessibility, dashboard.');
