const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),yesterday=new Date(Date.now()-86400000).toISOString(),old=new Date(Date.now()-16*86400000).toISOString();
const state={projects:[{id:'weak',title:'Stone Tools',subject:'History'},{id:'strong',title:'Cave Art',subject:'History'},{id:'stale',title:'Old Discovery',subject:'History'},{id:'next',title:'Fire Discovery',subject:'History'}]};
const reader={version:1,preferences:{},progress:[{userId:'student',projectId:'weak',percentage:45,readingSeconds:600,updatedAt:yesterday},{userId:'student',projectId:'strong',percentage:100,readingSeconds:900,updatedAt:old},{userId:'student',projectId:'stale',percentage:100,readingSeconds:300,updatedAt:old}],bookmarks:[{userId:'student',projectId:'weak'}],sectionProgress:[],completions:[{userId:'student',projectId:'strong',completedAt:old},{userId:'student',projectId:'stale',completedAt:old}],notes:[{userId:'student',projectId:'weak',createdAt:yesterday}],highlights:[{userId:'student',projectId:'weak',createdAt:yesterday}],quizAttempts:[{userId:'student',projectId:'weak',score:40,createdAt:yesterday},{userId:'student',projectId:'strong',score:95,createdAt:old}]};
const conversation={version:1,sessions:[{id:'s',userId:'student',projectId:'weak'}],messages:[{sessionId:'s',role:'user',lessonId:'weak',intent:'explain_again'},{sessionId:'s',role:'user',lessonId:'weak',intent:'simplify'}]};
localStorage.setItem('rupaiStudentReader:v1',JSON.stringify(reader));localStorage.setItem('rupaiCurioConversation:v1',JSON.stringify(conversation));
const window={localStorage,TeachCurioStore:{read:()=>JSON.parse(JSON.stringify(state))}},context=vm.createContext({window,localStorage,console,Date});for(const file of ['student-reader-service.js','curio-learning-intelligence-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});const L=window.RupaiCurioLearningIntelligence;
L.recordLessonOpen('student','weak');L.recordSearch('student','tools',['weak']);L.recordSearch('student','stone tools',['weak']);
const profile=L.profile('student');assert.equal(profile.lessonsOpened,3);assert.equal(profile.lessonsCompleted,2);assert.equal(profile.quizAttempts,2);assert.equal(profile.quizAccuracy,68);assert.equal(profile.bookmarks,1);assert.equal(profile.notesCreated,1);assert.equal(profile.highlights,1);assert.equal(profile.searchHistory.length,2);assert.equal(profile.localOnly,true);assert.equal(profile.telemetry,false);
const weak=L.weakTopics('student');assert.equal(weak[0].projectId,'weak');assert.equal(weak[0].priority.level,'High');assert.ok(weak[0].priority.reasons.includes('quiz average below 60%'));assert.ok(weak[0].priority.reasons.includes('repeated local searches'));assert.ok(weak[0].priority.reasons.includes('repeated Explain Again or Simplify'));
const strong=L.strongTopics('student');assert.equal(strong[0].projectId,'strong');assert.ok(['Strong','Mastered'].includes(strong[0].confidence.level));
const advice=L.suggestions('student');assert.equal(advice.find(x=>x.projectId==='weak').when,'Review Today');assert.ok(advice.some(x=>x.type==='forgotten'&&x.projectId==='stale'));
const recommendations=L.recommendations('student');assert.ok(recommendations.some(x=>/requested extra explanation/.test(x.text)));assert.ok(recommendations.some(x=>/improving in Cave Art/.test(x.text)));assert.equal(L.motivation('student'),'Time for revision.');
const dashboard=L.dashboard('student');assert.equal(dashboard.privacy.cloud,false);assert.equal(dashboard.privacy.uploads,false);assert.ok(dashboard.recommendedNextLesson);assert.match(dashboard.scoring,/Transparent rules/);
console.log('Phase 11C tests passed: local profile, learning evidence, weak and strong topics, confidence levels, adaptive revision timing, priorities, evidence-based recommendations, motivation, dashboard and privacy.');
