const assert=require('assert'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');let raw=null;const window={localStorage:{getItem:()=>raw,setItem:(_,v)=>raw=v},dispatchEvent(){}};const c=vm.createContext({window,localStorage:window.localStorage,crypto:crypto.webcrypto,CustomEvent:function(){},console});for(const f of ['studio/store.js','studio/curio-brain-service.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);const S=window.TeachCurioStore,B=window.TeachCurioBrain,s=S.read();
function lesson(id,title,subject,text,blocks=[]){s.projects.push({id,title,subject,description:text,chapterHint:'',creatorNotes:'',status:'draft',createdAt:'2026-01-01',updatedAt:'2026-01-01'});s.lessonDrafts.push({id:`d_${id}`,projectId:id,status:'draft',sections:text?[{id:`sec_${id}`,title:'Explanation',content:{english:text}}]:[]});s.learningEnhancements.push({id:`e_${id}`,projectId:id,blocks:blocks.map((type,i)=>({id:`${id}_${i}`,type,status:'draft',currentContent:{english:`Meaningful ${type} content explaining this learning component clearly.`}}))});}
lesson('empty','Empty Lesson','','');lesson('history','Ancient Civilizations','History','Events occurred in 2600 BCE and 1900 BCE near important river sites in India.',['important_points']);lesson('science','Water Cycle','Science','The process has stages. First evaporation, then condensation, finally precipitation.',['definition','real_life_examples']);lesson('geo','River Regions','Geography','This lesson explains river location, mountain region and climate map evidence.',['quick_summary']);lesson('mixed','Maths in Science','Mathematics Science','Calculate energy using a formula and explain the scientific process.',['definition']);S.write(s);
const empty=B.run('empty');assert(empty.decisions.some(x=>x.type==='add_explanation'));assert.equal(empty.readiness.status,'early_draft');
const history=B.run('history');assert.equal(history.snapshot.classification.subjectType,'history');assert(history.decisions.some(x=>x.type==='add_timeline'));assert(history.decisions.some(x=>x.type==='add_map'));
const science=B.run('science');assert.equal(science.snapshot.classification.subjectType,'science');assert(science.decisions.some(x=>x.type==='add_diagram'));
const geo=B.run('geo');assert.equal(geo.snapshot.classification.subjectType,'geography');assert(geo.decisions.some(x=>x.type==='add_map'));
const mixed=B.run('mixed');assert.equal(mixed.snapshot.classification.subjectType,'mixed_subject');
const override=B.classify(B.aggregate('mixed'),{subjectType:'polity',learningNature:'fact_heavy',contentForm:'explanation',overrideReason:'Creator confirmed'});assert.equal(override.subjectType,'polity');assert.equal(override.basis,'creator_override');
const decision=history.decisions[0];B.respond(decision.id,'dismiss','Not appropriate for this lesson');assert.equal(B.result(history.run.id).decisions.find(x=>x.id===decision.id).status,'dismissed');const task=B.createTask(history.decisions.find(x=>x.type==='add_timeline').id);assert.equal(task.linkedWorkspace,'educational-visuals.html');
const first=history.steps[1];B.moveStep(first.id,-1);assert.equal(B.result(history.run.id).steps[0].id,first.id);
B.profile('science',['highly_visual','minimal_text','detailed_explanations']);const science2=B.run('science');assert(science2.conflicts.length===1);assert(B.provider().available===false);assert(B.provider().message.includes('not configured'));
const before=B.run('geo').decisions.length;B.toggleRule('location_map',false);const after=B.run('geo').decisions.length;assert(after<before);B.toggleRule('location_map',true);assert(B.history('history').total>=1);console.log('Curio Brain tests passed: empty, history, science, geography, mixed, override, workflow, conflict, rule toggle, no-provider.');
