const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),navigator={onLine:true},location={hostname:'127.0.0.1'},window={localStorage,navigator,location,crypto:webcrypto,dispatchEvent(){},addEventListener(){}};
const context=vm.createContext({window,localStorage,navigator,location,crypto:webcrypto,structuredClone,CustomEvent:function(){},console,Date});
for(const file of ['studio/store.js','studio/ai-provider-service.js','studio/curio-brain-decision-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const S=window.TeachCurioStore,B=window.TeachCurioBrainDecision,student={userId:'student_6d',permissions:['curio.brain.use','curio.brain.explanation.read','curio.brain.override.own']},creator={userId:'creator_6d',permissions:['curio.decision.audit','curio.rules.manage','curio.brain.use']};
function seed(){const s=S.read();['History','Geography','Science','Mathematics','Language'].forEach((subject,i)=>s.projects.push({id:`p${i+1}`,title:[`Ancient History`,`River Geography`,`Plate Tectonics`,`Ratios`,`Grammar`][i],subject,status:i===0?'completed':'draft',createdAt:new Date(2026,0,i+1).toISOString()}));s.lessonDrafts.push({id:'lesson_science',projectId:'p3',status:'approved',approvedVersionId:'v1',versions:[{id:'v1',sections:[{id:'sec1',title:'Plate Tectonics'}]}]});s.visualAssets.push({id:'visual_science',originProjectId:'p3',title:'Plate Diagram',reviewStatus:'approved'});s.knowledgeRelationships.push(
{id:'r1',from:'Volcanoes',to:'Plate Tectonics',type:'prerequisite',status:'approved',fromSubject:'Science',toSubject:'Science'},
{id:'r2',from:'Plate Tectonics',to:'Earthquakes',type:'cause_and_effect',status:'verified',fromSubject:'Science',toSubject:'Science'},
{id:'r3',from:'Ancient History',to:'River Geography',type:'related_concept',approved:true,fromSubject:'History',toSubject:'Geography',crossSubject:true},
{id:'r4',from:'Fractions',to:'Ratios',type:'prerequisite',status:'draft'},
{id:'r5',from:'Ratios',to:'Percentages',type:'leads_to',status:'creator_approved',fromSubject:'Mathematics',toSubject:'Mathematics'});
s.studentMasteries.push({id:'m1',studentId:'student_6d',concept:'Volcanoes',score:.3},{id:'m2',studentId:'strong',concept:'Volcanoes',score:.9},{id:'m3',studentId:'student_6d',concept:'Plate Tectonics',score:.35});s.revisionSchedules.push({id:'rev1',studentId:'student_6d',concept:'Plate Tectonics',dueAt:'2026-06-01T00:00:00.000Z'});s.curioConversationPatterns=[{id:'pref1',userId:'student_6d',patternType:'visual_first',status:'confirmed'},{id:'pref2',userId:'student_6d',patternType:'story_based',status:'deleted',deletedAt:new Date().toISOString()}];S.write(s)}
seed();
const noHistory=B.decide({studentId:'new_student',projectId:'p5',concept:'Grammar',approvedEvidence:[{id:'p5',summary:'Approved language lesson'}]}, {...student,userId:'new_student'});assert.equal(noHistory.decision.explanationStyle,'standard');assert.ok(['medium','insufficient_evidence'].includes(noHistory.decision.confidence));
const weak=B.prerequisiteCheck({studentId:'student_6d',concept:'Plate Tectonics'},student);assert.equal(weak.outcome,'prerequisite_review_recommended');assert.deepEqual(weak.weakPrerequisites,['Volcanoes']);
const strong=B.prerequisiteCheck({studentId:'strong',concept:'Plate Tectonics'},{...student,userId:'strong'});assert.equal(strong.outcome,'ready');
const science=B.decide({studentId:'student_6d',projectId:'p3',concept:'Plate Tectonics',approvedEvidence:[{id:'sec1',summary:'Approved science section'}],offline:true},student);assert.equal(science.decision.recommendedAction,'revise_earlier_concept');assert.equal(science.decision.explanationStyle,'visual_first');assert.equal(science.decision.providerRequirement,'none');assert.equal(science.revision.needed,true);assert.equal(science.provider.configured,false);assert.match(science.provider.message,/Advanced AI interpretation is not configured/);
const cross=B.decide({studentId:'student_6d',projectId:'p1',concept:'Ancient History',approvedEvidence:[{id:'p1',summary:'Approved history lesson'}]},student);assert.ok(cross.connections.some(x=>x.crossSubject&&x.to==='River Geography'));assert.ok(cross.curiosity.every(x=>x.optional));
assert.equal(B.connections('Ratios','student_6d',student).some(x=>x.id==='r4'),false);assert.ok(B.connections('Ratios','student_6d',student).some(x=>x.id==='r5'));
const minor=B.misconception({studentId:'student_6d',concept:'Ratios',expectedIdea:'Ratios compare quantities',confirmedResponse:'Ratio compare quantity',minorError:true},student);assert.equal(minor.state,'no_misconception_detected');
const repeated=B.misconception({studentId:'student_6d',concept:'Plate Tectonics',expectedIdea:'Plates move and interact',confirmedResponse:'Plates never move',conflictingIdeas:['never move'],previousEvidence:[{verified:true}]},student);assert.equal(repeated.state,'repeated_misconception');
const remediation=B.remediationPlan({studentId:'student_6d',concept:'Plate Tectonics',previousStrategies:['visual_explanation'],availableResources:[{type:'visual'}]},student);assert.notEqual(remediation.strategy,'visual_explanation');assert.equal(remediation.understandingCheck.required,true);
const missing=B.decide({studentId:'student_6d',projectId:null,concept:'Unknown Concept'},student);assert.equal(missing.decision.recommendedAction,'cannot_answer_from_approved_evidence');assert.equal(missing.decision.confidence,'insufficient_evidence');
const unclear=B.decide({studentId:'student_6d',projectId:null,concept:'',approvedEvidence:[]},student);assert.equal(unclear.decision.recommendedAction,'ask_for_clarification');
const override=B.override(science.decision.id,'student_6d',{action:'skip_revision',note:'Continue now'},student);assert.equal(override.permanentPreference,false);
assert.throws(()=>B.inspect('student_6d',{userId:'other',permissions:[]}),/only your own/);assert.ok(B.inspect('student_6d',creator).decisions.length);
const rules=B.rules(creator),pack=rules.packs[0],v2=B.saveRuleVersion(pack.id,{rules:['creator test rule'],reason:'QA'},creator),restored=B.restoreRuleVersion(pack.id,1,creator);assert.equal(v2.version,2);assert.equal(restored.version,3);assert.match(restored.reason,/Restored/);
const state=S.read();assert.ok(state.curioBrainContextSnapshots.some(x=>x.offline===true&&x.privacy.otherLearnerDataExcluded));assert.ok(state.curioCrossSubjectConnections.length);assert.ok(state.curioDecisionExplanations.every(x=>x.screenReaderText));assert.ok(science.nextLesson.projectId);assert.equal(JSON.stringify(state).includes('emotion'),false);
console.log('Curio Brain decision tests passed: new/returning learners; History, Geography, Science, Mathematics and Language; strong/weak prerequisites; overdue revision; confirmed/deleted preferences; approved relationship boundaries; misconceptions; varied remediation; resources; next lesson; cross-subject curiosity; overrides; low confidence; offline/no-provider; access control; rule version restore; screen-reader explanations and memory safety.');
