const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),window={localStorage,crypto:webcrypto,dispatchEvent(){},addEventListener(){}},context=vm.createContext({window,localStorage,crypto:webcrypto,structuredClone,console,CustomEvent:function(){}});
for(const file of ['studio/store.js','studio/knowledge-graph-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const S=window.TeachCurioStore,G=window.TeachCurioKnowledgeGraph,creator={userId:'creator_7a',permissions:['studio.access','curio.brain.use','curio.brain.review','curio.rules.manage']},student={userId:'student_7a',permissions:['curio.brain.use']};
function seed(){const s=S.read();s.projects.push({id:'history',title:'River Civilizations',subject:'History',status:'structure_ready'},{id:'geography',title:'Monsoon Geography',subject:'Geography',status:'structure_ready'},{id:'science',title:'Climate Science',subject:'Science',status:'structure_ready'},{id:'math',title:'Climate Data Mathematics',subject:'Mathematics',status:'structure_ready'});s.lessonStructures.push({id:'structure_history',projectId:'history',approvalStatus:'approved',nodes:[{id:'settlements',nodeType:'concept',title:'Settlements',verificationStatus:'user_approved'},{id:'agriculture',nodeType:'topic',title:'Agriculture',verificationStatus:'user_approved'},{id:'rivers',nodeType:'concept',title:'Rivers',verificationStatus:'user_approved'}]},{id:'structure_geo',projectId:'geography',approvalStatus:'approved',nodes:[{id:'monsoon',nodeType:'concept',title:'Monsoon',verificationStatus:'user_approved'},{id:'weather',nodeType:'concept',title:'Weather',verificationStatus:'user_approved'},{id:'climate',nodeType:'concept',title:'Climate',verificationStatus:'user_approved'}]},{id:'structure_science',projectId:'science',approvalStatus:'approved',nodes:[{id:'water_cycle',nodeType:'concept',title:'Water Cycle',verificationStatus:'user_approved'}]},{id:'structure_math',projectId:'math',approvalStatus:'approved',nodes:[{id:'graphs',nodeType:'concept',title:'Graphs and Averages',verificationStatus:'user_approved'}]});S.write(s)}
seed();const synced=G.sync(creator);assert.equal(synced.nodeCount,12);assert.ok(synced.nodes.every(x=>x.id&&x.sourceId&&x.type));assert.ok(synced.nodes.find(x=>x.title==='Monsoon').verified);
const riverMonsoon=G.addRelationship({from:'Rivers',to:'Monsoon',type:'geographical_relationship',evidence:'Creator verified: seasonal monsoon rainfall changes river flow.',sourceReference:'geo-source-1'},creator);assert.equal(riverMonsoon.crossSubject,true);assert.equal(riverMonsoon.fromSubject,'History');assert.equal(riverMonsoon.toSubject,'Geography');
G.addRelationship({from:'Monsoon',to:'Agriculture',type:'cause',evidence:'Creator-approved lesson explains rainfall effects on agriculture.'},creator);G.addRelationship({from:'Agriculture',to:'Settlements',type:'historical_influence',evidence:'Approved history material connects farming with settled communities.'},creator);G.addRelationship({from:'Water Cycle',to:'Monsoon',type:'prerequisite',evidence:'Approved science lesson supplies the water-cycle prerequisite.'},creator);G.addRelationship({from:'Graphs and Averages',to:'Climate',type:'mathematical_dependency',evidence:'Approved lesson uses graphs and averages to interpret climate records.'},creator);G.addRelationship({from:'Weather',to:'Climate',type:'commonly_confused_with',evidence:'Approved geography notes distinguish short-term weather from long-term climate.',clarification:'Weather is short-term atmospheric condition; climate is a long-term pattern.'},creator);G.addRelationship({from:'Climate',to:'Monsoon',type:'related_concept',evidence:'Approved geography lesson studies monsoon within regional climate.'},creator);
assert.throws(()=>G.addRelationship({from:'Monsoon',to:'Water Cycle',type:'prerequisite',evidence:'Would reverse the approved prerequisite.'},creator),/circular prerequisite/);assert.throws(()=>G.addRelationship({from:'Rivers',to:'Climate',type:'similarity',evidence:''},creator),/evidence note/);assert.equal(G.addRelationship({from:'Rivers',to:'Monsoon',type:'geographical_relationship',evidence:'Duplicate'},creator).id,riverMonsoon.id);
const map=G.neighbourhood({center:'Monsoon',depth:2},student);assert.equal(map.center.title,'Monsoon');assert.ok(map.nodes.some(x=>x.title==='Rivers'));assert.ok(map.nodes.some(x=>x.title==='Agriculture'));assert.ok(map.relationships.every(x=>x.status==='approved'));assert.equal(map.relationships.find(x=>x.id===riverMonsoon.id).crossSubject,true);
let prerequisites=G.prerequisites('student_7a','Monsoon',student);assert.equal(prerequisites.outcome,'review_recommended');assert.equal(prerequisites.recommendations[0].node.title,'Water Cycle');assert.equal(prerequisites.forcedNavigation,false);let s=S.read();s.conceptMemories.push({id:'memory_water',studentId:'student_7a',conceptId:'water_cycle',status:'mastered'});S.write(s);prerequisites=G.prerequisites('student_7a','Monsoon',student);assert.equal(prerequisites.outcome,'ready');
assert.equal(G.confidence('student_7a','Water Cycle',student).confidence,'learned');assert.equal(G.confidence('student_7a','Monsoon',student).confidence,'uncertain');s=S.read();s.studentMasteries.push({id:'mastery_monsoon',studentId:'student_7a',concept:'Monsoon',score:.45});S.write(s);assert.equal(G.confidence('student_7a','Monsoon',student).confidence,'needs_revision');
const revision=G.revisionLinks('student_7a','Rivers',student);assert.ok(revision.some(x=>x.node.title==='Monsoon'&&x.confidence==='needs_revision'));assert.equal(new Set(revision.map(x=>x.node.id)).size,revision.length);const misconceptions=G.misconceptions('Weather',student);assert.equal(misconceptions[0].confusedWith,'Climate');assert.match(misconceptions[0].clarification,/short-term/);const curiosity=G.curiosity('Monsoon',student);assert.ok(curiosity.length<=3&&curiosity.every(x=>x.optional&&x.evidence));assert.equal(new Set(curiosity.map(x=>x.node.id)).size,curiosity.length);assert.ok(curiosity.some(x=>/connects to|enjoy|important later/.test(x.prompt)));
const learning=G.learningContext('student_7a','Monsoon',student);assert.equal(learning.providerRequired,false);assert.equal(learning.confidence.confidence,'needs_revision');assert.ok(learning.approvedConnections.length);assert.match(G.list(student).provider.message,/No AI provider is required/);
assert.throws(()=>G.addRelationship({from:'Rivers',to:'Climate',type:'related_concept',evidence:'Test'},student),/Creator review permission/);assert.throws(()=>G.list({userId:'outsider',permissions:[]}),/permission/);assert.equal(S.read().knowledgeRelationships.some(x=>x.status==='approved'&&!x.evidence),false);
console.log('Knowledge Graph tests passed: approved content sync, lesson/topic/concept nodes, cross-subject links, cycle-safe prerequisites, optional navigation, confidence evidence, revision links, misconceptions, bounded curiosity, interactive neighbourhood data, offline provider independence and access control.');
