const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),window={localStorage,crypto:webcrypto,dispatchEvent(){},addEventListener(){}},context=vm.createContext({window,localStorage,crypto:webcrypto,structuredClone,console,CustomEvent:function(){}});for(const file of ['studio/store.js','studio/knowledge-graph-service.js','studio/learning-path-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const S=window.TeachCurioStore,G=window.TeachCurioKnowledgeGraph,P=window.TeachCurioLearningPaths,creator={userId:'creator_path',permissions:['curio.brain.use','curio.brain.review','curio.decision.audit']},learner={userId:'learner_path',permissions:['curio.brain.use']};
function seed(){const s=S.read();s.projects.push({id:'history_path',title:'Early Human History',subject:'History',status:'structure_ready'});s.lessonStructures.push({id:'structure_path',projectId:'history_path',approvalStatus:'approved',nodes:[{id:'stone',nodeType:'concept',title:'Stone Age',verificationStatus:'user_approved'},{id:'agriculture_path',nodeType:'concept',title:'Agriculture',verificationStatus:'user_approved'},{id:'civilization',nodeType:'concept',title:'Civilization',verificationStatus:'user_approved'},{id:'indus',nodeType:'concept',title:'Indus Valley',verificationStatus:'user_approved'},{id:'archaeology',nodeType:'concept',title:'Archaeology',verificationStatus:'user_approved'}]});S.write(s);G.sync(creator);G.addRelationship({from:'Stone Age',to:'Agriculture',type:'prerequisite',evidence:'Creator-approved historical learning order.'},creator);G.addRelationship({from:'Agriculture',to:'Civilization',type:'prerequisite',evidence:'Creator-approved history lesson connects farming before civilization.'},creator);G.addRelationship({from:'Civilization',to:'Indus Valley',type:'prerequisite',evidence:'Creator-approved curriculum places civilization foundations first.'},creator);G.addRelationship({from:'Archaeology',to:'Indus Valley',type:'related_concept',evidence:'Approved lesson uses archaeology to study the Indus Valley.'},creator)}
seed();let goal=P.saveGoal(learner.userId,{type:'ssc_preparation',title:'SSC Preparation',prioritySubjects:['History'],targetNodeId:'Indus Valley'},learner);assert.equal(goal.type,'ssc_preparation');assert.throws(()=>P.saveGoal(learner.userId,{type:'fake_goal'},learner),/supported learning goal/);
let result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'beginner'},learner);assert.equal(result.paths.length,3);assert.deepEqual(result.paths.map(x=>x.variant),['foundation_sequence','fastest','connected_application']);assert.ok(result.paths.every(x=>x.targetTitle==='Indus Valley'&&x.providerUsed===false));let primary=result.paths[0];assert.deepEqual(primary.steps.slice(0,4).map(x=>x.title),['Stone Age','Agriculture','Civilization','Indus Valley']);assert.equal(primary.steps.find(x=>x.title==='Stone Age').locked,false);assert.equal(primary.steps.find(x=>x.title==='Agriculture').locked,true);assert.equal(result.recommendation.nextTitle,'Stone Age');assert.match(result.recommendation.message,/ready for the next lesson/i);assert.equal(result.provider.configured,false);
let update=P.updateProgress(learner.userId,'Stone Age',{state:'completed',score:.9},learner);assert.equal(update.unlocks.find(x=>x.title==='Agriculture').unlocked,true);result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'beginner'},learner);primary=result.paths[0];assert.ok(!primary.steps.some(x=>x.title==='Stone Age'));assert.equal(primary.steps.find(x=>x.title==='Agriculture').locked,false);assert.equal(result.recommendation.nextTitle,'Agriculture');
P.updateProgress(learner.userId,'Agriculture',{state:'partial',score:.55},learner);result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'beginner',goal:'fast_revision'},learner);assert.equal(result.recommendation.nextTitle,'Agriculture');assert.match(result.recommendation.message,/revise this topic first/i);assert.equal(result.paths[0].steps.find(x=>x.title==='Agriculture').kind,'revision');assert.equal(result.paths[0].steps.find(x=>x.title==='Civilization').locked,true);
P.updateProgress(learner.userId,'Agriculture',{state:'completed',score:.85},learner);result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'intermediate',goal:'school_learning'},learner);assert.equal(result.recommendation.nextTitle,'Civilization');assert.equal(result.paths[0].steps.find(x=>x.title==='Civilization').locked,false);P.updateProgress(learner.userId,'Civilization',{state:'completed'},learner);result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'advanced',goal:'general_knowledge'},learner);assert.equal(result.recommendation.nextTitle,'Indus Valley');assert.equal(result.paths[0].steps.find(x=>x.title==='Indus Valley').locked,false);
P.updateProgress(learner.userId,'Indus Valley',{state:'skipped',reason:'Learner chose to return later.'},learner);let progress=P.progress(learner.userId,learner);assert.equal(progress.completed,3);assert.equal(progress.skipped,1);assert.ok(progress.masteryPercent>0);assert.equal(P.inspect(learner.userId,learner).localOnly,true);assert.ok(P.inspect(learner.userId,learner).recommendations.length>=4);
P.updateProgress(learner.userId,'Indus Valley',{state:'completed'},learner);result=P.generate({studentId:learner.userId,target:'Indus Valley',level:'beginner',goal:'curiosity_mode'},learner);assert.equal(result.paths[0].steps.length,0);assert.match(result.recommendation.message,/complete|another goal/i);assert.equal(result.progress.recommendedNextMilestone,null);
assert.throws(()=>P.generate({studentId:learner.userId,target:'Unknown',level:'beginner'},learner),/existing target concept/);assert.throws(()=>P.inspect(learner.userId,{userId:'other',permissions:[]}),/only your own/);assert.equal(/guilt|disappointed|must/i.test(S.read().learningPathRecommendations.map(x=>x.message).join(' ')),false);
console.log('Learning Path tests passed: beginner/intermediate/advanced variants, alternative routes, prerequisite locks, unlock updates, revision-first balance, five goals, mastered exclusion, partial/skipped/completed progress, next milestones, safe motivation, local-only execution and access control.');
