const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),window={localStorage,crypto:webcrypto,dispatchEvent(){},addEventListener(){}};
const context=vm.createContext({window,localStorage,crypto:webcrypto,structuredClone,CustomEvent:function(){},console,Date});
for(const file of ['studio/store.js','studio/motivation-support-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const S=window.TeachCurioStore,M=window.TeachCurioMotivation,actor={userId:'learner',permissions:[]},DAY=86400000,day=n=>new Date(Date.now()-n*DAY).toISOString();
let s=S.read();s.curioLearningPatterns=[{id:'visual',userId:'learner',patternType:'visual_first',status:'confirmed',useAllowed:true},{id:'deleted',userId:'learner',patternType:'story_based',status:'confirmed',useAllowed:true,deletedAt:day(1)}];S.write(s);
M.record('learner',{type:'study_activity',evidenceId:'study_today',createdAt:day(0)},actor);M.record('learner',{type:'study_activity',evidenceId:'study_yesterday',createdAt:day(1)},actor);M.record('learner',{type:'study_activity',evidenceId:'study_two_days',createdAt:day(2)},actor);assert.equal(M.streak('learner',new Date().toISOString(),actor).current,3);assert.equal(M.streak('learner',new Date().toISOString(),actor).pressureFree,true);
const mistake=M.support('learner',{context:'mistake'},actor);assert.match(mistake.message,/Good attempt/);assert.equal(mistake.inferredEmotion,false);assert.equal(mistake.providerUsed,false);
assert.match(M.support('learner',{context:'quiz_failed'},actor).message,/not a judgement/);assert.match(M.support('learner',{context:'partially_correct'},actor).message,/part of the idea/);assert.match(M.support('learner',{context:'basic_question'},actor).message,/Every expert started/);assert.match(M.support('learner',{context:'curiosity'},actor).message,/deeper questions|Curiosity/);assert.match(M.support('learner',{context:'difficult_lesson_completed'},actor).message,/persisted/);
const breakSuggestion=M.support('learner',{context:'persistence',sessionMinutes:50},actor);assert.equal(breakSuggestion.optional,true);assert.match(breakSuggestion.habitSuggestion,/optional/);assert.match(M.support('learner',{context:'persistence',recentDifficultyCount:3},actor).habitSuggestion,/Your choice/);
for(let i=1;i<=30;i++)M.record('learner',{type:'lesson_completed',lessonId:`lesson_${i}`,evidenceId:`lesson_${i}`,createdAt:day(i%3)},actor);M.record('learner',{type:'correct_answer',evidenceId:'first_correct'},actor);M.record('learner',{type:'quiz_passed',difficulty:'hard',evidenceId:'hard_quiz'},actor);M.record('learner',{type:'revision_completed',evidenceId:'revision'},actor);M.record('learner',{type:'chapter_completed',evidenceId:'chapter'},actor);M.record('learner',{type:'subject_completed',evidenceId:'subject'},actor);
let milestones=M.milestones('learner',{reducedMotion:false},actor);for(const type of ['three_lessons','seven_lessons','thirty_lessons','first_correct_answer','difficult_quiz_passed','revision_completed','chapter_completed','subject_completed'])assert.ok(milestones.items.some(x=>x.type===type));assert.ok(milestones.newItems.some(x=>x.animation==='gentle_confetti'));const count=milestones.items.length;milestones=M.milestones('learner',{},actor);assert.equal(milestones.newItems.length,0);assert.equal(milestones.items.length,count);
M.record('returning',{type:'study_activity',evidenceId:'old',createdAt:day(10)},{userId:'returning'});assert.match(M.support('returning',{context:'returning',at:new Date().toISOString()},{userId:'returning'}).message,/Welcome back/);assert.doesNotMatch(M.support('returning',{context:'returning'},{userId:'returning'}).message,/Where were you/i);
const beginner=M.support('beginner',{context:'persistence'},{userId:'beginner'});assert.match(beginner.message,/Every expert started/);let state=S.read();state.studentMasteries.push({id:'advanced_score',studentId:'advanced',score:.95});S.write(state);assert.match(M.support('advanced',{context:'correct_answer'},{userId:'advanced'}).message,/more challenging/);
for(const unsafe of ['You are bad at this.','You will never understand.','I am your therapist.','I have feelings.','You must keep your streak.'])assert.equal(M.safetyCheck(unsafe).safe,false);assert.equal(M.safetyCheck('You have not mastered this yet. This becomes easier with practice.').safe,true);
assert.throws(()=>M.status('learner',{userId:'other',permissions:[]}),/only your own/);const status=M.status('learner',actor);assert.equal(status.localOnly,true);assert.match(status.message,/not a therapist/);assert.equal(S.read().motivationLearningEvents.filter(x=>x.evidenceId==='lesson_1').length,1);
console.log('Motivation support tests passed: mistakes, quiz failure, partial answers, basic questions, curiosity, persistence, returning learners, optional healthy habits, confirmed preferences, beginner/advanced adaptation, 3/7/30 lesson streak milestones, chapter/subject/correct-answer/difficult-quiz/revision celebrations, reduced-pressure deduplication, safety boundaries, local-only evidence and access control.');
