const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Storage{constructor(){this.d={}}get length(){return Object.keys(this.d).length}key(i){return Object.keys(this.d)[i]??null}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}removeItem(k){delete this.d[k]}}
const localStorage=new Storage(),state={projects:[{id:'ready',title:'Ready Lesson',subject:'History'},{id:'draft',title:'Draft Lesson',subject:'Science'}],lessonDrafts:[{id:'ready-draft',projectId:'ready',status:'approved',sections:[{id:'one',title:'One',content:{english:'Approved content.'}}]},{id:'draft-only',projectId:'draft',status:'draft',sections:[{id:'hidden',content:{english:'Hidden draft.'}}]}],lessonStructures:[],visualAssets:[],visualAssetReferences:[],learningEnhancements:[],quizzes:[],quizQuestions:[],quizOptions:[]};
const navigator={serviceWorker:null,storage:{estimate:async()=>({usage:10,quota:100})}},window={localStorage,navigator,TeachCurioStore:{read:()=>JSON.parse(JSON.stringify(state))}},context=vm.createContext({window,localStorage,navigator,console,Blob,Date,Intl,JSON,Promise,setTimeout,clearTimeout,encodeURIComponent});
for(const file of['student-reader-service.js','student-dashboard-service.js','offline-library-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
localStorage.setItem('rupaiStudentReader:v1',JSON.stringify({version:1,preferences:null,progress:null,notes:{bad:true},bookmarks:[],sectionProgress:[],completions:[],highlights:[],quizAttempts:[]}));const safe=window.RupaiStudentReader._readState();assert.deepEqual(Array.from(safe.progress),[]);assert.deepEqual(Array.from(safe.notes),[]);assert.equal(safe.preferences.theme,'light');assert.match(localStorage.getItem('rupaiStudentReader:v1'),/"progress":null/);
localStorage.setItem('rupaiStudentDashboard:v1',JSON.stringify({version:1,dailyGoals:null}));assert.equal(window.RupaiStudentDashboard.goals('student').length,4);
const catalog=window.RupaiOfflineLibrary.catalog();assert.deepEqual(Array.from(catalog.map(x=>x.id)),['ready']);assert.equal(catalog.some(x=>x.id==='draft'),false);
localStorage.setItem('rupaiStudentReader:v1',JSON.stringify({version:1,notes:[{id:'n1'}],progress:[],bookmarks:[],sectionProgress:[],completions:[],highlights:[],quizAttempts:[]}));localStorage.setItem('rupaiIdentity:v2',JSON.stringify({token:'never export'}));const backup=window.RupaiOfflineLibrary.exportBackup();assert(backup.data['rupaiStudentReader:v1']);assert(!backup.data['rupaiIdentity:v2']);assert.throws(()=>window.RupaiOfflineLibrary.validateBackup({...backup,version:999}),/unsupported/);assert.throws(()=>window.RupaiOfflineLibrary.validateBackup({format:'bad',version:1,data:{}}),/not a valid/);
const sw=fs.readFileSync('service-worker.js','utf8');assert.match(sw,/phase15b-rc1/);assert.match(sw,/phase14c-v3/);for(const file of['student-dashboard-service.js','student-discovery-service.js','curio-guided-learning-service.js','curio-conversation-service.js','student-session-continuity.js','curio-learning-intelligence.css','student-settings.js'])assert(sw.includes(`'./${file}'`),`Offline shell missing ${file}`);
for(const file of['student-reader.html','student-dashboard.html','student-learning-coach.html','student-memory-dashboard.html','student-progress-dashboard.html','student-study-planner.html','student-settings.html']){const html=fs.readFileSync(file,'utf8');for(const match of html.matchAll(/(?:src|href)="([^"]+\.(?:js|css))(?:\?[^"#]*)?"/g)){const ref=match[1];if(ref.startsWith('http')||ref.startsWith('studio/')&&ref!=='studio/store.js'&&ref!=='studio/auth.js')continue;assert(sw.includes(`'./${ref}'`),`Offline shell missing ${ref} from ${file}`)}}
console.log('Phase 15B tests passed: partial-record recovery without destructive writes, legacy goals recovery, draft-free offline catalog, protected backup validation, release-candidate cache versioning and complete Student App shell dependencies.');
