const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}removeItem(k){delete this.d[k]}}
const localStorage=new Storage(),state={projects:[],lessonDrafts:[],lessonStructures:[],visualAssets:[],visualAssetReferences:[],learningEnhancements:[],quizzes:[],quizQuestions:[],quizOptions:[]};
const window={localStorage,TeachCurioStore:{read:()=>JSON.parse(JSON.stringify(state))}},context=vm.createContext({window,localStorage,console,Blob,Date,Intl});
for(const file of['student-reader-service.js','student-dashboard-service.js','student-discovery-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
state.projects.push({id:'approved',title:'Stone Age',subject:'History'},{id:'draft',title:'Secret Draft',subject:'History'},{id:'removed',title:'Removed Lesson',subject:'Science',deletedAt:'2026-01-01'});
state.lessonDrafts.push({id:'approved-draft',projectId:'approved',status:'approved',sections:[{id:'intro',title:'Introduction',content:{english:'Creator-approved lesson text.',hinglish:'Creator-approved Hinglish text.'}}]},{id:'draft-only',projectId:'draft',status:'draft',sections:[{id:'hidden',title:'Hidden',content:{english:'Unapproved material.'}}]});
const R=window.RupaiStudentReader,D=window.RupaiStudentDashboard,X=window.RupaiStudentDiscovery;
assert.equal(R.lesson('draft').empty,true);assert.equal(R.lesson('draft').sections.length,0);assert.deepEqual(Array.from(R.availableLessons().map(x=>x.id)),['approved']);assert.equal(R.isAvailable('approved'),true);assert.equal(R.isAvailable('draft'),false);
R.saveProgress('student','approved',{percentage:44,scrollY:80,readingSeconds:30});R.saveProgress('student','draft',{percentage:70,scrollY:90,readingSeconds:20});
assert.equal(D.recentLessons('student').length,1);assert.equal(D.recentLessons('student')[0].projectId,'approved');assert.equal(D.search('student','Secret Draft').length,0);assert.equal(X.search('student','Secret Draft').length,0);assert.equal(X.search('student','Stone Age')[0].projectId,'approved');
const before=JSON.stringify(R._readState());window.RupaiMemoryProfile={ensure:()=>({preferredLanguage:'Hinglish',explanationDepth:'Normal',learningStyles:[],favoriteSubjects:[],currentSubjects:[],studyGoals:[]})};vm.runInContext(fs.readFileSync('student-personalization-service.js','utf8'),context,{filename:'student-personalization-service.js'});const personalized=R.lesson('approved');assert.equal(personalized.blocks[0].content,'Creator-approved Hinglish text.');assert.equal(JSON.stringify(R._readState()),before);
const readerSource=fs.readFileSync('student-reader.js','utf8');assert.equal((readerSource.match(/function updateProgress\(/g)||[]).length,1);assert(!/cloud sync|cross-device continuity|production hosting/i.test(fs.readFileSync('student-reader-service.js','utf8')));
console.log('Phase 15A tests passed: approved-content visibility, draft exclusion, shared learning records, language identity safety, discovery integration and duplicate progress-handler removal.');
