const fs=require('fs'),vm=require('vm'),assert=require('assert');
class Storage{constructor(){this.d={}}get length(){return Object.keys(this.d).length}key(i){return Object.keys(this.d)[i]??null}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}removeItem(k){delete this.d[k]}}
const localStorage=new Storage(),state={projects:[],lessonDrafts:[],lessonStructures:[],visualAssets:[],visualAssetReferences:[],educationalVisuals:[],learningEnhancements:[],knowledgeRelationships:[],quizzes:[],quizQuestions:[],quizOptions:[]};
state.projects.push({id:'lesson',title:'Stone Age',subject:'History',chapterHint:'Early Humans',difficulty:'Easy',relatedTopics:['Cave Art']},{id:'related',title:'Cave Art',subject:'History'},{id:'private',title:'Creator Draft',subject:'Science'});
state.lessonDrafts.push({id:'lesson-draft',projectId:'lesson',status:'approved',sections:[{id:'intro',title:'Introduction',content:{english:'Early humans made tools and learned to control fire.',hinglish:'Early humans ne tools banaye aur fire control karna seekha.'}},{id:'example',title:'Daily Life',blockType:'activity',content:{english:'Observe how a modern tool makes work easier.'},question:'Which tool helps you today?'}]},{id:'related-draft',projectId:'related',status:'approved',sections:[{id:'art',title:'Cave Art',content:{english:'Cave paintings record parts of early life.'}}]},{id:'private-draft',projectId:'private',status:'draft',sections:[{id:'secret',content:{english:'Private creator material.'}}]});
state.learningEnhancements.push({id:'enh',projectId:'lesson',blocks:[{id:'important',type:'important_points',status:'user_approved',english:['Stone tools supported hunting and food preparation.']},{id:'example-real',type:'real_life_examples',status:'user_approved',english:['A kitchen knife is a modern tool example.']}]});
state.knowledgeRelationships.push({from:'Stone Age',to:'Cave Art',status:'approved'});state.quizzes.push({id:'quiz',projectId:'lesson',status:'approved'});state.quizQuestions.push({id:'question',quizId:'quiz',type:'mcq',prompt:'Which material was used for early tools?',explanation:'Stone was widely used.'});state.quizOptions.push({id:'stone',questionId:'question',text:'Stone',isCorrect:true},{id:'plastic',questionId:'question',text:'Plastic',isCorrect:false});
const navigator={serviceWorker:null,storage:{estimate:async()=>({usage:100,quota:1000})}},window={localStorage,navigator,TeachCurioStore:{read:()=>JSON.parse(JSON.stringify(state))},RupaiAuth:{readSession:()=>({userId:'student'})}},context=vm.createContext({window,localStorage,navigator,console,Blob,Date,Intl,JSON,Promise,setTimeout,clearTimeout,encodeURIComponent});
const load=file=>vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});for(const file of['student-reader-service.js','student-dashboard-service.js','curio-guided-learning-service.js','curio-conversation-service.js','offline-library-service.js'])load(file);
const R=window.RupaiStudentReader,D=window.RupaiStudentDashboard,C=window.RupaiCurioConversation,G=window.RupaiCurioGuide,O=window.RupaiOfflineLibrary,user='student';
assert.deepEqual(Array.from(R.availableLessons().map(x=>x.id)),['lesson','related']);assert.equal(R.isAvailable('private'),false);assert.equal(R.lesson('private').empty,true);const lesson=R.lesson('lesson');assert.equal(lesson.subject,'History');assert.equal(lesson.chapter,'Early Humans');assert(lesson.blocks.some(x=>x.type==='activity'));assert(lesson.blocks.some(x=>x.type==='important'));
localStorage.setItem('rupaiMemoryProfile:v1',JSON.stringify({version:1,profiles:[{userId:user,preferredLanguage:'Hinglish',explanationDepth:'Normal',learningStyles:[],favoriteSubjects:[],currentSubjects:[],studyGoals:[]}]}));window.RupaiMemoryProfile={ensure:()=>({preferredLanguage:'Hinglish',explanationDepth:'Normal',learningStyles:[],favoriteSubjects:[],currentSubjects:[],studyGoals:[]})};load('student-personalization-service.js');assert.match(R.lesson('lesson').blocks[0].content,/fire control/);
R.saveProgress(user,'lesson',{percentage:62,scrollY:840,readingSeconds:420});R.saveBookmark(user,'lesson',{sectionId:'intro',scrollY:220});const note=R.addNote(user,'lesson',{sectionId:'intro',body:'Fire provided warmth and safety.'});R.addHighlight(user,'lesson',{sectionId:'intro',quote:'learned to control fire'});const check=R.knowledgeChecks('lesson')[0];assert.equal(R.evaluateCheck(check,'stone').correct,true);const attempt=R.saveQuizAttempt(user,'lesson',[{correct:true}]);assert.equal(attempt.score,100);R.completeSection(user,'lesson','intro');R.completeLesson(user,'lesson');
assert.match(C.ask(user,'lesson',{question:'Explain again',sectionId:'intro'}).assistant.content,/fire control/);assert.match(C.ask(user,'lesson',{question:'Give another example'}).assistant.content,/kitchen knife/);assert.equal(C.ask(user,'lesson',{question:'Related topic'}).assistant.action.topics[0].title,'Cave Art');assert(G.studyAdvice('lesson',user).some(x=>/knowledge check|notes/i.test(x)));
const dashboard=D.dashboard(user,'Rupai');assert(dashboard.recent.some(x=>x.projectId==='lesson'));assert(dashboard.bookmarks.some(x=>x.projectId==='lesson'));assert(dashboard.notes.some(x=>x.id===note.id));assert.equal(D.search(user,'Creator Draft').length,0);assert(D.search(user,'Stone Age').some(x=>x.projectId==='lesson'));
const before=localStorage.getItem('rupaiStudentReader:v1'),backup=O.exportBackup();assert(backup.data['rupaiStudentReader:v1']);assert(!JSON.stringify(backup).includes('Private creator material'));const report=O.validateBackup(backup);assert(report.valid);O.restoreBackup(backup);assert.equal(localStorage.getItem('rupaiStudentReader:v1'),before);assert.throws(()=>O.validateBackup({...backup,version:2}),/unsupported/);assert.throws(()=>O.validateBackup({format:'broken',version:1,data:{}}),/not a valid/);
load('student-reader-service.js');const restored=window.RupaiStudentReader;assert.equal(restored.progress(user,'lesson').percentage,62);assert.equal(restored.notes(user,'lesson')[0].body,'Fire provided warmth and safety.');assert.equal(restored.bookmark(user,'lesson').sectionId,'intro');assert.equal(restored.highlights(user,'lesson').length,1);assert.equal(restored.completion(user,'lesson').badge,'Lesson Complete');assert.equal(restored._readState().quizAttempts.length,1);
console.log('Phase 15C final journey passed: approved creator content, draft privacy, metadata, language, learning blocks, notes/bookmarks/highlights, quiz, progress, Curio grounding, related topics, dashboard discovery, backup/restore and reload persistence.');
