const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}}
const localStorage=new Storage(),navigator={onLine:false},window={localStorage,navigator,crypto:webcrypto,dispatchEvent(){},addEventListener(){}},context=vm.createContext({window,localStorage,navigator,crypto:webcrypto,structuredClone,console,CustomEvent:function(){}});
for(const file of ['studio/store.js','studio/visual-studio-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
const S=window.TeachCurioStore,V=window.TeachCurioVisualStudio,creator={userId:'creator8b',permissions:['studio.access','visual.request.create','visual.prompt.edit','visual.output.review']},student={userId:'student',permissions:['lesson.read']};
const lesson='In 1857 and 1947, a river route connected the north and south regions. Because one event leads to another, the process has steps: first observe then compare differences. The water cycle repeats and returns to its first stage. A hierarchy has parent, child and branch structures. Types and categories classify related concepts. This story scene describes a person and event. The object has parts and an inside structure. '.repeat(4);
let s=S.read();s.projects.push({id:'p8b',ownerId:'creator8b',title:'Integrated Visual Lesson',subject:'History'});s.lessonDrafts.push({id:'d8b',projectId:'p8b',sections:[{id:'sec8b',paragraph:{english:lesson}}]});s.visualAssets.push({id:'a1',originProjectId:'p8b',title:'River map',assetType:'map',status:'draft',fileSize:10000,fingerprint:'same'},{id:'a2',originProjectId:'p8b',title:'River map copy',assetType:'map',status:'approved',source:'Creator upload',copyrightStatus:'creator_owned',altText:'Map of a river route.',fileSize:20000,fingerprint:'same'});s.visualAssetReferences.push({id:'r1',assetId:'a2',projectId:'p8b'});S.write(s);
assert.throws(()=>V.detect('p8b',student),/permission/);const recs=V.detect('p8b',creator),types=new Set(recs.map(x=>x.type));for(const type of V.TYPES)assert.ok(types.has(type),`missing recommendation ${type}`);assert.ok(recs.every(x=>x.reason&&x.evidenceContentIds.includes('sec8b')&&x.confidence==='rule_based'));
const plan=V.createPlan('p8b',{visualType:'timeline',title:'History timeline',educationalPurpose:'Show chronology'},creator);assert.equal(plan.providerUsed,false);assert.throws(()=>V.addScene(plan.id,{title:'No purpose'},creator),/required/);const one=V.addScene(plan.id,{title:'Opening',subject:'History',characters:'Learner, Curio',objects:['map'],environment:'classroom',cameraAngle:'wide',mood:'curious',lighting:'daylight',style:'educational',aspectRatio:'16:9',educationalPurpose:'Introduce the route'},creator),two=V.addScene(plan.id,{title:'Sequence',educationalPurpose:'Order the dates'},creator);assert.equal(V.updateScene(one.id,{title:'Opening route'},creator).title,'Opening route');assert.equal(V.moveScene(two.id,-1,creator)[0].id,two.id);
const pv1=V.savePrompt(plan.id,{subject:'River route',style:'flat educational',composition:'Map left, timeline right',importantObjects:'river, dates',restrictions:'no logos, no copyrighted characters',educationalNotes:'Labels must be readable'},creator),pv2=V.savePrompt(plan.id,{subject:'River route revised',style:'diagram',composition:'Centered route',approved:true},creator);assert.equal(pv1.version,1);assert.equal(pv2.version,2);assert.equal(pv2.status,'creator_approved');assert.equal(pv2.providerUsed,false);
for(const builderType of V.BUILDERS){const d=V.createDiagram(plan.id,{builderType,title:`${builderType} plan`,nodes:[{title:'Start'},{title:'End'}],links:[{fromIndex:0,toIndex:1,label:'next'}]},creator);assert.equal(d.nodes.length,2);assert.equal(d.links.length,1)}V.createDiagram(plan.id,{builderType:'flowchart',title:'Label validation',nodes:[{}]},creator);V.updateScene(one.id,{aspectRatio:'3:2'},creator);
let assets=V.assets('p8b',{query:'river',limit:10},creator);assert.equal(assets.total,2);assert.equal(assets.items.find(x=>x.id==='a2').usageCount,1);assert.equal(assets.items.find(x=>x.id==='a2').approved,true);const usage=V.recordAssetUsage('a2',plan.id,creator);assert.equal(usage.usageType,'visual_plan_reference');assert.equal(V.recordAssetUsage('a2',plan.id,creator).id,usage.id);assets=V.assets('p8b',{query:'river'},creator);assert.equal(assets.items.find(x=>x.id==='a2').usageCount,2);const review=V.review(plan.id,creator);for(const type of ['missing_alt_text','low_resolution_risk','unapproved_asset','duplicate_asset','wrong_aspect_ratio','missing_label'])assert.ok(review.findings.some(x=>x.type===type),type);assert.equal(review.legalComplianceClaimed,false);
const queued=V.queueExport(plan.id,{format:'json_plan'},creator);assert.equal(queued.status,'prepared_plan_only');assert.equal(queued.published,false);assert.equal(queued.creatorApprovalRequired,true);const full=V.get(plan.id,creator);assert.equal(full.scenes.length,2);assert.equal(full.prompts.length,2);assert.equal(full.diagrams.length,V.BUILDERS.length+1);assert.equal(full.exports.length,1);
const ps=V.providerStatus();assert.equal(ps.configured,false);assert.equal(ps.used,false);assert.equal(ps.outputRequiresCreatorApproval,true);assert.equal(ps.noCopyrightedAssetGeneration,true);assert.equal(ps.message,'AI image generation is not configured. Visual Studio is preparing creator-approved visual plans.');assert.ok(ps.interfaces.every(x=>x.configured===false));assert.equal(S.read().visualAssets.length,2);assert.equal(S.read().visualStudioUsageHistory.length,1);assert.equal(S.read().visualStudioExportQueue.some(x=>x.published),false);
console.log('Phase 8B Visual Studio tests passed: explainable type detection, creator-controlled plans, scenes and reorder, immutable prompt versions, seven diagram planners, reusable asset search and usage, review validation, plan-only export, provider-independent interfaces, permissions and no auto-generation/publishing.');
