const assert=require('assert'),fs=require('fs'),vm=require('vm'),{webcrypto}=require('crypto'),{performance}=require('perf_hooks');
class Storage{constructor(){this.d={}}getItem(k){return this.d[k]??null}setItem(k,v){this.d[k]=String(v)}removeItem(k){delete this.d[k]}}
class Recognition{static last=null;constructor(){Recognition.last=this;this.continuous=false}start(){this.started=true}stop(){this.stopped=true}abort(){this.aborted=true}result(text,final=true){this.onresult?.({resultIndex:0,results:[Object.assign([{transcript:text,confidence:.9}],{isFinal:final})]})}end(){this.onend?.()}}
class Utterance{constructor(text){this.text=text;this.rate=1;this.pitch=1;this.volume=1}}
class Synthesis{constructor(){this.current=null;this.speaking=false;this.paused=false}getVoices(){return[{voiceURI:'voice-en',name:'English',lang:'en-IN'}]}speak(u){this.current=u;this.speaking=true;u.onstart?.()}pause(){this.paused=true}resume(){this.paused=false}cancel(){this.current=null;this.speaking=false;this.paused=false}}
const localStorage=new Storage(),synth=new Synthesis(),navigator={onLine:true,mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})}},location={hostname:'127.0.0.1'};
const window={localStorage,navigator,location,crypto:webcrypto,performance,isSecureContext:true,SpeechRecognition:Recognition,SpeechSynthesisUtterance:Utterance,speechSynthesis:synth,dispatchEvent(){},addEventListener(){}};
const context=vm.createContext({window,localStorage,navigator,location,crypto:webcrypto,performance,structuredClone,TextEncoder,TextDecoder,URL,URLSearchParams,console,setTimeout,clearTimeout,setInterval,clearInterval,CustomEvent:function(){},SpeechSynthesisUtterance:Utterance});
for(const file of ['studio/store.js','studio/ai-provider-service.js','studio/curio-conversation-service.js','studio/voice-intelligence-service.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
window.TeachCurioAdaptiveTeaching={teachingChoice:(userId,projectId)=>({id:'adaptive_local',userId,projectId,strategy:'explanation_first'})};
window.TeachCurioMemory={continuity:userId=>({studentId:userId,currentLessonId:'project_voice',pendingRevision:[]})};
window.TeachCurioBrainDecision={decide:input=>({decision:{id:'brain_local',recommendedAction:'explain',providerRequirement:'none',currentConcept:input.concept}})};
window.TeachCurioConversationOrchestrator={orchestrate:async(conversationId,userId,text)=>({state:'completed',message:{id:'answer_local',content:`Approved local response: ${text}`},provider:null})};
vm.runInContext(fs.readFileSync('studio/voice-conversation-controller.js','utf8'),context,{filename:'studio/voice-conversation-controller.js'});
const Store=window.TeachCurioStore,C=window.TeachCurioConversation,V=window.TeachCurioVoice,VC=window.TeachCurioVoiceConversation;
C.visualRecommendation=(projectId,type)=>({available:true,asset:{id:type==='map'?'map1':'image1',title:type==='map'?'Approved rain map':'Approved cycle image'}});C.quizLink=projectId=>({available:true,quizId:'quiz1',url:`quiz.html?project=${projectId}`});
const actor={userId:'voice_student',permissions:['voice.input.use','voice.output.use','voice.transcript.read.own','voice.session.read.own','curio.brain.use']};
function seed(){const s=Store.read();s.projects.push({id:'project_voice',title:'Water Cycle',status:'draft'});s.lessonDrafts.push({id:'lesson_voice',projectId:'project_voice',status:'approved',approvedVersionId:'v1',versions:[{id:'v1',sections:[{id:'p1',title:'Evaporation',paragraph:{english:'Heat changes water into vapour.',sourceReferences:[{sourceId:'source1'}]}}]}]});s.visualAssets.push({id:'image1',originProjectId:'project_voice',assetType:'illustration',title:'Approved cycle image',reviewStatus:'approved'});s.visualAssets.push({id:'map1',originProjectId:'project_voice',assetType:'map',title:'Approved rain map',reviewStatus:'approved'});s.quizzes.push({id:'quiz1',projectId:'project_voice',status:'approved'});Store.write(s)}
(async()=>{
  seed();const conversation=C.createConversation({userId:actor.userId,projectId:'project_voice',preferredLanguage:'english'}),started=VC.start({userId:actor.userId,conversationId:conversation.id,projectId:'project_voice',timeoutMinutes:2},actor),id=started.session.id;
  assert.equal(started.session.state,'idle');assert.equal(started.session.microphoneActive,false);assert.equal(VC.status(id,actor.userId,actor).safety.alwaysListening,false);assert.equal(VC.status(id,actor.userId,actor).safety.explicitActivationRequired,true);assert.match(VC.status(id,actor.userId,actor).provider.message,/not configured/i);
  assert.equal((await VC.activate(id,actor.userId,actor)).state,'activation_required');assert.equal(Recognition.last,null);
  assert.equal((await VC.activate(id,actor.userId,actor,{explicitActivation:true})).state,'idle');
  V.consent(actor.userId,{type:'microphone',granted:true,remember:true,dataCategories:['microphone_audio_during_active_listening','confirmed_transcript']},actor);
  assert.equal((await VC.activate(id,actor.userId,actor,{explicitActivation:true})).state,'listening');assert.equal(VC.snapshot(id,actor.userId,actor).session.microphoneActive,true);
  const paused=VC.pauseListening(id,actor.userId,actor);assert.equal(paused.session.state,'paused');assert.equal(paused.session.microphoneActive,false);assert.equal((await VC.resumeListening(id,actor.userId,actor)).session.state,'idle');assert.equal(VC.snapshot(id,actor.userId,actor).session.microphoneActive,false);
  const text=await VC.submitText(id,actor.userId,'Explain evaporation',actor,{speak:false,concept:'Evaporation'});assert.match(text.turn.responseText,/Approved local response/);assert.equal(text.turn.brainDecisionId,'brain_local');assert.equal(text.turn.adaptiveDecisionId,'adaptive_local');assert.equal(text.turn.memoryContextUsed,true);assert.equal(text.turn.providerUsed,false);
  const example=await VC.submitText(id,actor.userId,'Give me an example',actor,{speak:false});assert.equal(example.turn.command,'give_example');assert.match(example.turn.responseText,/Approved local response/);
  const image=await VC.submitText(id,actor.userId,'Show image',actor,{speak:false});assert.equal(image.result.action.available,true);assert.equal(image.result.action.asset.id,'image1');
  const map=await VC.submitText(id,actor.userId,'Open map',actor,{speak:false});assert.equal(map.result.action.available,true);assert.equal(map.result.action.asset.id,'map1');
  const quiz=await VC.submitText(id,actor.userId,'Start quiz',actor,{speak:false});assert.equal(quiz.result.action.available,true);assert.match(quiz.result.action.url,/quiz/);
  assert.equal((await VC.submitText(id,actor.userId,'Stop quiz',actor,{speak:false})).turn.command,'stop_quiz');
  const spoken=await VC.submitText(id,actor.userId,'Explain condensation',actor,{speak:true});assert.equal(spoken.turn.spoken,true);const interrupted=VC.interrupt(id,actor.userId,actor);assert.equal(interrupted.session.microphoneActive,false);assert.equal(interrupted.turns.at(-1).interrupted,true);
  assert.equal((await VC.narration(id,actor.userId,'project_voice',actor,{paragraphId:'p1'})).state,'speaking');assert.equal(VC.pauseNarration(id,actor.userId,actor),true);assert.equal(VC.resumeNarration(id,actor.userId,actor),true);assert.equal(VC.repeatParagraph(id,actor.userId,actor).state,'speaking');VC.interrupt(id,actor.userId,actor);
  const pref=VC.preferences(actor.userId,{language:'hinglish',voiceId:'voice-en',speed:.8,pitch:1.1,volume:.7,narrationStyle:'teacher_curio',explanationDepth:'simple'},actor);assert.equal(pref.inputLanguage,'hinglish');assert.equal(pref.speakingRate,.8);assert.equal(pref.personality,'teacher_curio');
  VC.stop(id,actor.userId,actor);assert.equal(VC.snapshot(id,actor.userId,actor).session.state,'stopped');assert.equal(VC.recover(id,actor.userId,actor).session.state,'idle');
  let s=Store.read(),record=s.unifiedVoiceSessions.find(x=>x.id===id);record.timeoutAt=new Date(Date.now()-1000).toISOString();Store.write(s);assert.deepEqual(VC.expire(),[id]);assert.equal(VC.snapshot(id,actor.userId,actor).session.state,'timed_out');assert.equal(VC.recover(id,actor.userId,actor).session.state,'idle');assert.equal(VC.end(id,actor.userId,actor).session.state,'ended');assert.throws(()=>VC.recover(id,actor.userId,actor),/cannot be resumed/);
  assert.throws(()=>VC.snapshot(id,actor.userId,{userId:'other'}),/only your own/);assert.equal(Store.read().unifiedVoiceContextSnapshots.every(x=>x.approvedContextOnly),true);assert.equal(VC.fallbackMessage(),'Voice recognition is unavailable on this device. Keyboard input and visible transcripts remain available.');
  console.log('Unified voice conversation controller tests passed: explicit microphone activation, permission, session lifecycle, timeout recovery, local pipeline, brain/memory/adaptive context, commands, narration, interruption, personalization, accessibility fallback and safety.');
})().catch(error=>{console.error(error);process.exitCode=1});
