window.MATH_FUN_FACTS = [
  // Arithmetic
  "Zero is neither positive nor negative.",
  "Adding zero leaves a number unchanged.",
  "Multiplying any number by zero gives zero.",
  "One is the only positive integer with exactly one positive divisor.",
  "The sum of the first n odd numbers is n squared.",
  "An even number is divisible by 2.",
  "The product of two odd numbers is always odd.",
  "The product of two even numbers is always even.",
  "A number is divisible by 3 when its digits add to a multiple of 3.",
  "A number is divisible by 9 when its digits add to a multiple of 9.",
  "A number ending in 0 or 5 is divisible by 5.",
  "Every whole number is either even or odd.",
  "The equals sign was introduced by Robert Recorde in 1557.",
  "The word hundred comes from an old word meaning a count of one hundred.",
  "A googol is 1 followed by 100 zeros.",
  "A googolplex is 1 followed by a googol zeros.",
  "The Roman numeral system has no standard symbol for zero.",
  "In base 10, moving a decimal one place changes value by a factor of 10.",
  "The sum of the angles around a point is 360 degrees.",
  "Any number raised to the power zero equals 1, except the indeterminate case 0^0.",

  // Algebra
  "Algebra uses symbols to describe patterns that work for many numbers.",
  "The word algebra comes from the Arabic title Al-jabr.",
  "A variable is a symbol that can represent a changing value.",
  "An equation is balanced when both sides have the same value.",
  "Doing the same valid operation to both sides preserves an equation.",
  "A linear graph forms a straight line.",
  "The slope of a horizontal line is zero.",
  "Parallel nonvertical lines have equal slopes.",
  "Perpendicular slopes multiply to -1 when both slopes exist.",
  "The graph of y = x squared is called a parabola.",
  "A quadratic equation can have zero, one, or two real solutions.",
  "The discriminant reveals how many real roots a quadratic has.",
  "Expanding (a + b) squared gives a squared + 2ab + b squared.",
  "The difference of two squares factors as (a - b)(a + b).",
  "An exponent tells how many times a factor is multiplied by itself.",
  "Negative exponents represent reciprocals.",
  "Logarithms undo exponentiation.",
  "An inequality compares values that may not be equal.",
  "Absolute value measures distance from zero.",
  "A function gives exactly one output for each allowed input.",

  // Geometry
  "A triangle's interior angles add to 180 degrees in flat geometry.",
  "A quadrilateral's interior angles add to 360 degrees.",
  "A pentagon has five sides and five vertices.",
  "A regular hexagon can be divided into six equilateral triangles.",
  "A circle has infinitely many lines of symmetry.",
  "The diameter of a circle is twice its radius.",
  "Pi is the ratio of a circle's circumference to its diameter.",
  "The area of a circle is pi times the radius squared.",
  "A sphere has no edges and no vertices.",
  "A cube has 6 faces, 12 edges, and 8 vertices.",
  "A tetrahedron has four triangular faces.",
  "The shortest path between two points in flat space is a straight line.",
  "Similar shapes have equal corresponding angles.",
  "Congruent shapes have the same size and shape.",
  "The Pythagorean theorem applies to right triangles.",
  "A tangent touches a circle at exactly one point locally.",
  "A chord joins two points on a circle.",
  "An ellipse has two focal points.",
  "A Mobius strip has only one side and one boundary edge.",
  "Honeybees build hexagonal cells that use space efficiently.",

  // Trigonometry and calculus
  "Sine, cosine, and tangent connect angles with side ratios.",
  "The sine of 30 degrees is one half.",
  "The cosine of 60 degrees is one half.",
  "The tangent of 45 degrees is 1.",
  "Sine and cosine repeat every 360 degrees.",
  "The identity sine squared plus cosine squared equals 1.",
  "Radians measure angles using the radius of a circle.",
  "A full turn is 2 pi radians.",
  "Calculus studies change and accumulation.",
  "A derivative measures an instantaneous rate of change.",
  "An integral can measure accumulated area.",
  "Differentiation and integration are linked by the Fundamental Theorem of Calculus.",
  "The derivative of a constant is zero.",
  "The derivative of x squared is 2x.",
  "The area under a velocity graph can represent distance traveled.",
  "A limit describes what a function approaches.",
  "Infinite series can add infinitely many terms to a finite value.",
  "The geometric series 1/2 + 1/4 + 1/8 + ... equals 1.",
  "Calculus helps predict motion, growth, and changing temperatures.",
  "Trigonometry helps surveyors measure inaccessible distances.",

  // Number theory
  "A prime number has exactly two positive divisors.",
  "Two is the only even prime number.",
  "Every integer greater than 1 has a unique prime factorization.",
  "There are infinitely many prime numbers.",
  "Twin primes differ by 2, such as 11 and 13.",
  "A perfect number equals the sum of its proper positive divisors.",
  "Six is the smallest perfect number because 1 + 2 + 3 = 6.",
  "Twenty-eight is the second perfect number.",
  "A square number can be arranged as a square array of dots.",
  "Triangular numbers can be arranged as triangular dot patterns.",
  "Every square number has an odd number of positive divisors.",
  "Consecutive integers are always coprime.",
  "The greatest common divisor of coprime numbers is 1.",
  "Modular arithmetic is sometimes called clock arithmetic.",
  "On a 12-hour clock, 10 + 5 lands on 3.",
  "Fermat numbers have the form 2 raised to a power of 2, plus 1.",
  "A palindrome number reads the same forward and backward.",
  "The number 1729 is expressible as two cubes in two different ways.",
  "The decimal expansion of 1/3 repeats forever.",
  "Irrational numbers cannot be written as a ratio of two integers.",

  // Patterns and puzzles
  "The Fibonacci sequence begins 0, 1, 1, 2, 3, 5, 8.",
  "Each Fibonacci number is the sum of the previous two.",
  "Pascal's triangle contains the counting numbers along its second diagonal.",
  "The rows of Pascal's triangle add to powers of 2.",
  "Pascal's triangle hides the Fibonacci sequence in its shallow diagonals.",
  "A magic square has equal row, column, and diagonal sums.",
  "The classic 3 by 3 magic square uses the numbers 1 through 9.",
  "Sudoku is a logic puzzle, not an arithmetic test.",
  "A Latin square uses each symbol once in every row and column.",
  "The Tower of Hanoi with n disks needs at least 2^n - 1 moves.",
  "A chessboard has 64 small squares.",
  "Counting every possible square on a chessboard gives 204 squares.",
  "A standard domino set with values 0 through 6 has 28 tiles.",
  "The handshake problem counts pairs using triangular numbers.",
  "Fractals show repeating detail at different scales.",
  "The Koch snowflake has a finite area but an infinite perimeter.",
  "The Sierpinski triangle repeats the same triangular pattern.",
  "The Collatz process starts by halving evens and tripling odds plus one.",
  "A maze can be modeled as a network called a graph.",
  "The four-color theorem says four colors suffice for any flat map.",

  // Famous mathematicians
  "Euclid's Elements organized much of ancient Greek geometry.",
  "Archimedes estimated pi using polygons.",
  "Aryabhata wrote influential works on arithmetic and astronomy.",
  "Brahmagupta described arithmetic rules involving zero and negative numbers.",
  "Al-Khwarizmi's name inspired the word algorithm.",
  "Fibonacci helped popularize Hindu-Arabic numerals in Europe.",
  "Rene Descartes connected algebra and geometry with coordinates.",
  "Pierre de Fermat made major contributions to number theory.",
  "Blaise Pascal worked on probability, geometry, and calculating machines.",
  "Isaac Newton developed powerful methods of calculus.",
  "Gottfried Wilhelm Leibniz introduced much of modern calculus notation.",
  "Leonhard Euler popularized symbols such as e and f(x).",
  "Carl Friedrich Gauss made discoveries in algebra, geometry, and number theory.",
  "Sophie Germain contributed to number theory and elasticity.",
  "Ada Lovelace described an algorithm for Babbage's Analytical Engine.",
  "George Boole created an algebra that became vital to digital logic.",
  "Florence Nightingale used statistics to improve public health.",
  "Srinivasa Ramanujan discovered remarkable identities and number patterns.",
  "Emmy Noether linked symmetry with conservation laws.",
  "Katherine Johnson used mathematics for early spaceflight trajectories.",

  // Mathematical history and discoveries
  "Ancient Babylonians used a base-60 number system.",
  "Our 60-minute hour reflects ancient base-60 counting.",
  "The Hindu-Arabic numeral system made place-value calculation efficient.",
  "Zero works both as a number and as a placeholder in place value.",
  "Negative numbers were once called absurd by some mathematicians.",
  "The symbol for infinity became popular in the seventeenth century.",
  "The plus and minus signs appeared in European print in the late 1400s.",
  "Coordinate geometry lets equations describe shapes.",
  "Non-Euclidean geometry studies spaces where Euclid's parallel rule changes.",
  "Set theory gives mathematics a language for collections.",
  "Boolean algebra uses values such as true and false.",
  "The abacus has supported calculation for thousands of years.",
  "Logarithm tables once turned multiplication into addition.",
  "Slide rules were important calculation tools before electronic calculators.",
  "The first electronic computers relied heavily on binary arithmetic.",
  "Binary uses only the digits 0 and 1.",
  "Hexadecimal uses sixteen symbols and is common in computing.",
  "The International Mathematical Olympiad began in 1959.",
  "The Fields Medal recognizes major achievements by young mathematicians.",
  "Mathematical notation helps ideas cross language barriers.",

  // Real-life applications
  "GPS uses geometry, precise timing, and relativity corrections.",
  "Bridges are designed using geometry, algebra, and calculus.",
  "Music rhythms can be described with fractions.",
  "Musical pitch is connected to frequency ratios.",
  "Architects use scale drawings to represent large buildings.",
  "Maps use coordinate systems to describe locations.",
  "Cryptography uses number theory to protect information.",
  "Computer graphics use matrices to rotate and resize objects.",
  "Search engines use mathematical ranking methods.",
  "Weather forecasting solves mathematical models of the atmosphere.",
  "Medical imaging relies on geometry and mathematical reconstruction.",
  "Epidemiologists use models to study how diseases spread.",
  "Engineers use calculus to optimize shapes and systems.",
  "Sports statistics help compare player performance.",
  "Cooking often uses ratios, fractions, and unit conversions.",
  "Bank interest calculations use exponential growth.",
  "Animation uses coordinates to move characters frame by frame.",
  "Robots use geometry to plan paths and avoid obstacles.",
  "QR codes use error-correcting mathematics to recover damaged data.",
  "Digital photos store colors as numerical values.",

  // Records and curiosities
  "Pi has infinitely many nonrepeating decimal digits.",
  "Euler's number e is approximately 2.71828.",
  "The golden ratio is approximately 1.618.",
  "The square root of 2 is irrational.",
  "The imaginary unit i satisfies i squared = -1.",
  "Complex numbers have real and imaginary parts.",
  "Euler's identity links e, pi, i, 1, and 0.",
  "A line segment contains infinitely many points.",
  "Between any two different real numbers lies another real number.",
  "Some infinities are larger than other infinities.",
  "A countable infinity can be paired with the counting numbers.",
  "The set of real numbers is uncountable.",
  "There are exactly five Platonic solids.",
  "A regular polygon can have any whole number of sides greater than two.",
  "A chiliagon is a polygon with 1,000 sides.",
  "A googol is far larger than estimates of atoms in the observable universe.",
  "Kaprekar's constant is 6174 for a famous four-digit routine.",
  "The number 1089 appears in a classic reverse-and-subtract trick.",
  "Point nine repeating is exactly equal to 1.",
  "Zero factorial equals 1.",

  // Probability and data
  "Probability ranges from 0 for impossible to 1 for certain.",
  "A fair coin has a one-half chance of landing heads.",
  "Two fair coin tosses have four equally likely ordered outcomes.",
  "A standard die has an average roll of 3.5 over many trials.",
  "The chance of rolling a total of 7 with two dice is one sixth.",
  "The birthday paradox reaches over 50 percent with just 23 people.",
  "Independent events do not change each other's probabilities.",
  "The mean is found by dividing a total by the number of values.",
  "The median is the middle value after sorting.",
  "The mode is the value that appears most often.",
  "Range is the difference between the largest and smallest values.",
  "A histogram groups numerical data into intervals.",
  "A scatter plot can reveal relationships between two variables.",
  "Correlation does not by itself prove causation.",
  "A larger random sample often gives a more stable estimate.",
  "Outliers can strongly affect the mean.",
  "The median is often resistant to extreme outliers.",
  "Expected value is a probability-weighted average.",
  "The normal distribution has a symmetric bell shape.",
  "Randomness can create short-term streaks even in fair experiments."
];
