(function(){
  'use strict';const C=TeachCurioConversation,S=TeachCurioStore,session=window.__curioSession,$=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const params=new URLSearchParams(location.search);let conversationId=params.get('conversation'),busy=false,activeExecution=null;
  const labels=v=>v.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase()),toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
  function setup(){
    const data=S.read(),projects=data.projects.filter(x=>!x.deletedAt);$('#project').innerHTML='<option value="">No lesson selected</option>'+projects.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('');if(params.get('project'))$('#project').value=params.get('project');
    $('#mode').innerHTML=C.MODES.map(x=>`<option value="${x}">${labels(x)}</option>`).join('');$('#language').innerHTML=C.LANGUAGES.map(x=>`<option value="${x}">${labels(x)}</option>`).join('');$('#level').innerHTML=C.LEVELS.map(x=>`<option value="${x}">${labels(x)}</option>`).join('');$('#mode').value='solve_doubt';$('#level').value='standard';
    const profile=data.studentLearningProfiles?.find(x=>x.studentId===session.userId);if(profile){$('#language').value=C.LANGUAGES.includes(profile.preferredLanguage)?profile.preferredLanguage:'english';$('#level').value=profile.detailLevel==='detailed'?'detailed':'standard';document.body.classList.toggle('large-text',profile.accessibility?.largeText);document.body.classList.toggle('high-contrast',profile.accessibility?.highContrast)}
    const noProvider=RupaiAI.dashboard().noProvider;$('#providerNotice').textContent=noProvider?"AI teaching is not configured. Curio can still help using approved Rupai's World lessons and learning tools.":'A configured provider may be used only after safety, privacy, grounding and budget checks.';
    bind();refreshList();if(conversationId)load();else newConversation();
  }
  function newConversation(){
    const data=S.read(),identity=RupaiAuth.getCurrentUser?.(),profile=identity?.profile||data.profiles?.find(x=>x.userId===session.userId),c=C.createConversation({userId:session.userId,projectId:$('#project').value||null,teachingMode:$('#mode').value,preferredLanguage:$('#language').value,explanationLevel:$('#level').value,ageGroup:profile?.ageGroup||'unknown',memoryPermissionState:'not_asked'});conversationId=c.id;history.replaceState(null,'',`ask-curio.html?conversation=${c.id}`);refreshList();load();
  }
  function refreshList(){const rows=C.listConversations(session.userId);$('#conversationList').innerHTML=rows.map(x=>`<button class="conversation-item ${x.id===conversationId?'active':''}" data-conversation="${x.id}">${esc(x.currentTeachingGoal||'Learning conversation')}<small>${labels(x.teachingMode)} · ${new Date(x.lastActiveAt).toLocaleDateString()}</small></button>`).join('')||'<p>No conversations yet.</p>';document.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>{conversationId=b.dataset.conversation;history.replaceState(null,'',`ask-curio.html?conversation=${conversationId}`);load();refreshList()})}
  function load(){const view=C.getConversation(conversationId,session.userId),c=view.conversation;$('#project').value=c.projectId||'';$('#mode').value=c.teachingMode;$('#language').value=c.preferredLanguage;$('#level').value=c.explanationLevel;$('#contextConsent').checked=c.contextSharingAllowed;renderMessages(view.messages);renderSuggestions()}
  function renderSuggestions(){const q=C.suggestedQuestions($('#project').value);$('#suggestions').innerHTML=q.map(x=>`<button type="button">${esc(x)}</button>`).join('');$('#suggestions').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{$('#question').value=q[i];$('#question').focus()})}
  function renderMessages(messages){$('#messages').innerHTML=messages.length?messages.map(message).join(''):'<div class="message"><h3>Curio</h3><p>Ask an educational question. I will prefer approved lesson content and show where the answer came from.</p></div>';$('#messages').scrollTop=$('#messages').scrollHeight;document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{$('#reportMessage').value=b.dataset.report;$('#reportDialog').showModal()})}
  function message(m){const structured=m.structuredContent||{},visual=structured.suggestedVisual;return`<article class="message ${m.role==='student'?'student':'curio'}"><h3>${m.role==='student'?'You':'Curio'}</h3><p>${esc(m.content)}</p>${structured.followUpQuestion?`<p class="follow-up">${esc(structured.followUpQuestion)}</p>`:''}${visual?`<div class="visual-card"><strong>${esc(visual.title)}</strong><p>${esc(visual.reason)}</p></div>`:''}${m.role==='curio'?`<div class="trust"><span>${esc(m.trustLabel||'Learning support')}</span>${m.provider?.name?`<span>Provider: ${esc(m.provider.name)}</span>`:''}${m.sourceReferences?.length?`<span>${m.sourceReferences.length} source reference(s)</span>`:''}</div><div class="message-actions"><button data-report="${m.id}">Report issue</button></div>`:''}</article>`}
  async function submit(e){e.preventDefault();if(busy)return;busy=true;activeExecution=null;$('#messages').setAttribute('aria-busy','true');$('#progress').textContent='Preparing · Retrieving lesson context · Reviewing safety';e.submitter.disabled=true;$('#stop').disabled=true;const question=$('#question').value;try{C.updateConversation(conversationId,session.userId,{teachingMode:$('#mode').value,preferredLanguage:$('#language').value,explanationLevel:$('#level').value,contextSharingAllowed:$('#contextConsent').checked});const result=await C.ask(conversationId,session.userId,question,{streaming:true,onExecution:id=>{activeExecution=id;$('#stop').disabled=!id;$('#progress').textContent='Waiting for provider · Generating'},onChunk:event=>{$('#progress').textContent=`Generating · ${event.content.length} confirmed characters`}});$('#question').value='';load();$('#progress').textContent=result.state==='complete'?'Complete':labels(result.state)}catch(error){$('#progress').textContent=`Failed: ${error.message}`}finally{busy=false;activeExecution=null;$('#stop').disabled=true;e.submitter.disabled=false;$('#messages').setAttribute('aria-busy','false');refreshList()}}
  function bind(){
    $('#newConversation').onclick=newConversation;$('#composer').onsubmit=submit;['project','mode','language','level'].forEach(id=>$('#'+id).onchange=()=>{if(conversationId)C.updateConversation(conversationId,session.userId,{projectId:$('#project').value,teachingMode:$('#mode').value,preferredLanguage:$('#language').value,explanationLevel:$('#level').value});renderSuggestions()});
    $('#contextConsent').onchange=()=>{C.updateConversation(conversationId,session.userId,{contextSharingAllowed:$('#contextConsent').checked});C.setConsent(session.userId,{type:'provider_context',granted:$('#contextConsent').checked,dataCategories:['learning_preferences','concept_mastery']})};
    $('#openLesson').onclick=()=>{$('#project').value?location.href=`lesson.html?project=${encodeURIComponent($('#project').value)}`:toast('Choose a lesson first.')};$('#launchQuiz').onclick=()=>{const x=C.quizLink($('#project').value);x.available?location.href=x.url:toast(x.message)};$('#findVisual').onclick=()=>{const x=C.visualRecommendation($('#project').value,$('#question').value);toast(x.available?`Approved visual: ${x.asset.title}`:(x.task?.message||x.message||'No approved visual matched.'))};$('#summarize').onclick=()=>{const x=C.summarize(conversationId,session.userId);toast(`Summary saved: ${x.questionsAnswered} answer(s).`)};
    $('#stop').onclick=()=>{if(activeExecution&&RupaiAI.cancel(activeExecution))$('#progress').textContent='Cancelled — partial text was not marked complete.'};$('#reportForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;C.reportCorrection({conversationId,userId:session.userId,messageId:$('#reportMessage').value,category:$('#reportCategory').value,details:$('#reportDetails').value});toast('Report added to creator review.');$('#reportDetails').value=''};
  }
  document.addEventListener('DOMContentLoaded',setup);
})();
