(function(){
  const store=()=>window.TeachCurioStore, quizService=()=>window.TeachCurioQuiz;
  const uid=prefix=>`${prefix}_${crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)}`, now=()=>new Date().toISOString(), clone=value=>JSON.parse(JSON.stringify(value));
  const objective=new Set(['mcq','multiple_correct','true_false','fill_blank','match_following','arrange_order','image_based','map_based','timeline','assertion_reason']);
  const terminal=new Set(['submitted','auto_graded','awaiting_manual_review','fully_reviewed']);
  const clean=value=>String(value??'').replace(/[<>]/g,'').trim();
  const arraysEqual=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
  const tagValue=(tags,prefix)=>{const item=(tags||[]).find(tag=>tag.toLowerCase().startsWith(`${prefix}:`));return item?item.slice(prefix.length+1).trim():'Untagged';};
  function snapshot(){return store().read();}
  function quizVersion(data,quiz){
    const existing=data.quizVersions.filter(v=>v.quizId===quiz.id).sort((a,b)=>b.version-a.version)[0];
    if(existing)return existing;
    const questions=data.quizQuestions.filter(q=>q.quizId===quiz.id&&!q.deletedAt).sort((a,b)=>a.sortOrder-b.sortOrder),ids=new Set(questions.map(q=>q.id));
    return{id:uid('quiz_version'),quizId:quiz.id,version:1,kind:'attempt_snapshot',quiz:clone(quiz),questions:clone(questions),options:clone(data.quizOptions.filter(o=>ids.has(o.questionId))),createdAt:now()};
  }
  function attemptsFor(quizId,studentId){return snapshot().quizAttempts.filter(a=>a.quizId===quizId&&(!studentId||a.studentId===studentId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
  function attemptFor(id){return snapshot().quizAttempts.find(a=>a.id===id)||null;}
  function payload(id,includeKeys=false){
    const data=snapshot(),attempt=data.quizAttempts.find(a=>a.id===id);if(!attempt)throw new Error('Attempt not found.');
    const questions=clone(attempt.questionSnapshot||[]),options=clone(attempt.optionSnapshot||[]);
    if(!includeKeys){questions.forEach(q=>{q.interactionItems=clone(q.answerConfig?.items||q.answerConfig?.leftItems||[]);delete q.correctText;delete q.answerConfig;});options.forEach(o=>{delete o.isCorrect;delete o.explanation;});}
    return{attempt:clone(attempt),questions,options,answers:clone(data.attemptAnswers.filter(a=>a.attemptId===id)),states:clone(data.attemptQuestionStates.filter(s=>s.attemptId===id))};
  }
  function startAttempt(quizId,studentId='guest',config={}){
    const data=snapshot(),quiz=data.quizzes.find(q=>q.id===quizId);if(!quiz)throw new Error('Quiz not found.');
    const open=data.quizAttempts.find(a=>a.quizId===quizId&&a.studentId===studentId&&['in_progress','paused'].includes(a.status));
    if(open)return open;
    const version=quizVersion(data,quiz),base=version.questions.filter(q=>!q.deletedAt).sort((a,b)=>a.sortOrder-b.sortOrder);
    let questions=clone(base);
    if(config.questionIds)questions=questions.filter(q=>config.questionIds.includes(q.id));
    if(quiz.randomizeQuestions||config.randomize)questions=questions.sort(()=>Math.random()-.5);
    const optionIds=new Set(questions.map(q=>q.id)),options=clone(version.options.filter(o=>optionIds.has(o.questionId)));
    const stamp=now(),prior=data.quizAttempts.filter(a=>a.quizId===quizId&&a.studentId===studentId).length;
    const attempt={id:uid('attempt'),studentId,guestId:studentId.startsWith('guest')?studentId:undefined,quizId,quizVersionId:version.id,quizVersionNumber:version.version,lessonId:quiz.lessonDraftId,projectId:quiz.projectId,subject:config.subject||'',chapter:config.chapter||'',quizMode:config.mode||quiz.mode,startTime:stamp,endTime:null,status:'in_progress',currentQuestionPosition:0,marksObtained:0,maximumMarks:questions.reduce((n,q)=>n+q.marks,0),negativeMarks:0,accuracy:0,timeSpentSeconds:0,completionPercentage:0,attemptNumber:prior+1,submissionState:'local_draft',reviewState:'not_required',timerEndsAt:config.timeLimitSeconds?new Date(Date.now()+config.timeLimitSeconds*1000).toISOString():null,pausedAt:null,pausedSeconds:0,questionSnapshot:questions,optionSnapshot:options,settingsSnapshot:{showAnswers:config.showAnswers||'after_submission',allowHints:config.allowHints??quiz.mode!=='exam',allowPause:config.allowPause??quiz.mode!=='exam',partialCredit:config.partialCredit!==false},sourceAttemptId:config.sourceAttemptId||null,createdAt:stamp,updatedAt:stamp};
    data.quizAttempts.push(attempt);questions.forEach((q,index)=>data.attemptQuestionStates.push({id:uid('question_state'),attemptId:attempt.id,questionId:q.id,position:index,status:index===0?'current':'unanswered',markedForReview:false,timeSpentSeconds:0,createdAt:stamp,updatedAt:stamp}));
    event(data,attempt,'quiz_started',{quizVersionId:version.id});store().write(data);return attempt;
  }
  function saveAnswer(attemptId,questionId,value){
    const data=snapshot(),attempt=data.quizAttempts.find(a=>a.id===attemptId);if(!attempt||attempt.status!=='in_progress')throw new Error('This attempt is not accepting answers.');
    if(!attempt.questionSnapshot.some(q=>q.id===questionId))throw new Error('Question is not part of this attempt.');
    let answer=data.attemptAnswers.find(a=>a.attemptId===attemptId&&a.questionId===questionId),stamp=now();
    const response=Array.isArray(value)?value.map(clean):clean(value);
    if(!answer){answer={id:uid('answer'),attemptId,questionId,response,createdAt:stamp,updatedAt:stamp};data.attemptAnswers.push(answer);}else Object.assign(answer,{response,updatedAt:stamp});
    const state=data.attemptQuestionStates.find(s=>s.attemptId===attemptId&&s.questionId===questionId);if(state){state.status=(Array.isArray(response)?response.length:Boolean(response))?'answered':'unanswered';state.updatedAt=stamp;}
    updateCompletion(data,attempt);store().write(data);return answer;
  }
  function setQuestionState(attemptId,questionId,changes){const data=snapshot(),attempt=data.quizAttempts.find(a=>a.id===attemptId);if(!attempt||attempt.status!=='in_progress')throw new Error('Attempt is not active.');const state=data.attemptQuestionStates.find(s=>s.attemptId===attemptId&&s.questionId===questionId);if(!state)throw new Error('Question state not found.');Object.assign(state,changes,{id:state.id,attemptId,questionId,updatedAt:now()});if(Number.isInteger(changes.position))attempt.currentQuestionPosition=changes.position;attempt.updatedAt=now();store().write(data);return state;}
  function pause(id){const data=snapshot(),a=data.quizAttempts.find(x=>x.id===id);if(!a||a.status!=='in_progress'||!a.settingsSnapshot.allowPause)throw new Error('This attempt cannot be paused.');a.status='paused';a.pausedAt=now();a.updatedAt=now();store().write(data);return a;}
  function resume(id){const data=snapshot(),a=data.quizAttempts.find(x=>x.id===id);if(!a||a.status!=='paused')throw new Error('Paused attempt not found.');const seconds=Math.max(0,Math.round((Date.now()-Date.parse(a.pausedAt))/1000));a.pausedSeconds+=seconds;if(a.timerEndsAt)a.timerEndsAt=new Date(Date.parse(a.timerEndsAt)+seconds*1000).toISOString();a.status='in_progress';a.pausedAt=null;a.updatedAt=now();store().write(data);return a;}
  function gradeQuestion(question,options,response,partialEnabled=true){
    const method=question.answerConfig?.gradingMethod||(['long_answer','very_short'].includes(question.type)?'manual_review':question.type==='multiple_correct'?'partial_credit':'all_or_nothing');
    if(method==='manual_review'||!objective.has(question.type))return{status:'awaiting_review',earned:0,correct:false,partial:false};
    const given=Array.isArray(response)?response.map(String):clean(response),correctOptions=options.filter(o=>o.isCorrect).map(o=>o.id);
    let ratio=0;
    if(['mcq','true_false','image_based','assertion_reason'].includes(question.type))ratio=correctOptions.includes(String(given))?1:0;
    else if(question.type==='multiple_correct'){const selected=[...new Set(Array.isArray(given)?given:[])],hits=selected.filter(id=>correctOptions.includes(id)).length,wrong=selected.filter(id=>!correctOptions.includes(id)).length;ratio=method==='partial_credit'&&partialEnabled?Math.max(0,(hits-wrong)/correctOptions.length):(selected.length===correctOptions.length&&selected.every(id=>correctOptions.includes(id))?1:0);}
    else if(question.type==='fill_blank'){const accepted=question.answerConfig?.acceptedAnswers||String(question.correctText||'').split('|');const normalized=v=>question.answerConfig?.caseSensitive?clean(v):clean(v).toLowerCase();ratio=accepted.map(normalized).includes(normalized(given))?1:0;}
    else if(['match_following','arrange_order','timeline'].includes(question.type)){const expected=question.answerConfig?.correctOrder||question.answerConfig?.pairs||String(question.correctText||'').split('|').map(clean),actual=Array.isArray(given)?given:[];const matches=actual.filter((v,i)=>String(v)===String(expected[i])).length;ratio=(method==='per_correct_pair'||method==='per_correct_position'||method==='partial_credit')&&partialEnabled?matches/Math.max(1,expected.length):(arraysEqual(actual.map(String),expected.map(String))?1:0);}
    else ratio=clean(given).toLowerCase()===clean(question.correctText).toLowerCase()?1:0;
    const earned=Math.min(question.marks,Math.max(-question.negativeMarks,ratio>0?question.marks*ratio:-question.negativeMarks));
    return{status:'graded',earned:Number(earned.toFixed(2)),correct:ratio===1,partial:ratio>0&&ratio<1,ratio};
  }
  function submitAttempt(id,reason='student'){
    const data=snapshot(),attempt=data.quizAttempts.find(a=>a.id===id);if(!attempt)throw new Error('Attempt not found.');if(terminal.has(attempt.status))return attempt;if(!['in_progress','paused'].includes(attempt.status))throw new Error('Attempt cannot be submitted.');
    const answers=data.attemptAnswers.filter(a=>a.attemptId===id),stamp=now();let earned=0,negative=0,correct=0,attempted=0,manual=0,partial=0;
    attempt.questionSnapshot.forEach(question=>{const answer=answers.find(a=>a.questionId===question.id),opts=attempt.optionSnapshot.filter(o=>o.questionId===question.id),result=gradeQuestion(question,opts,answer?.response,attempt.settingsSnapshot.partialCredit);if(answer&&(Array.isArray(answer.response)?answer.response.length:Boolean(answer.response)))attempted++;if(result.status==='awaiting_review'){manual++;data.manualReviews.push({id:uid('manual_review'),attemptId:id,questionId:question.id,studentResponse:clone(answer?.response||''),expectedAnswer:question.correctText||'',rubric:clone(question.answerConfig?.rubric||{}),referenceSectionId:question.referenceSectionId||null,maximumMarks:question.marks,suggestedAiScore:null,creatorAwardedMarks:null,creatorFeedback:'',status:'awaiting_review',createdAt:stamp,updatedAt:stamp});}else{earned+=result.earned;if(result.earned<0)negative+=Math.abs(result.earned);if(result.correct)correct++;if(result.partial)partial++;}
      data.gradingResults.push({id:uid('grading'),attemptId:id,questionId:question.id,status:result.status,marksAwarded:result.earned,maximumMarks:question.marks,correct:result.correct,partialCredit:result.partial||false,gradedBy:'rule_engine',gradedAt:stamp});
    });
    attempt.endTime=stamp;attempt.timeSpentSeconds=Math.max(0,Math.round((Date.parse(stamp)-Date.parse(attempt.startTime))/1000)-attempt.pausedSeconds);attempt.marksObtained=Number(earned.toFixed(2));attempt.negativeMarks=Number(negative.toFixed(2));attempt.accuracy=attempt.questionSnapshot.length?Number((correct/attempt.questionSnapshot.length*100).toFixed(1)):0;attempt.completionPercentage=100;attempt.status=manual?'awaiting_manual_review':'auto_graded';attempt.submissionState='confirmed';attempt.reviewState=manual?'pending':'final';attempt.submissionReason=reason;attempt.finalSubmissionAt=stamp;attempt.updatedAt=stamp;attempt.partialCount=partial;
    calculateInsights(data,attempt);updateQuestionStats(data,attempt);event(data,attempt,'quiz_completed',{score:attempt.marksObtained,maximumMarks:attempt.maximumMarks});audit(data,'attempt_submitted',id,{reason});store().write(data);return attempt;
  }
  function reviewManual(reviewId,marks,feedback,reviewer='creator'){
    const data=snapshot(),review=data.manualReviews.find(r=>r.id===reviewId);if(!review)throw new Error('Review not found.');const awarded=Number(marks);if(!Number.isFinite(awarded)||awarded<0||awarded>review.maximumMarks)throw new Error('Awarded marks are invalid.');
    review.creatorAwardedMarks=awarded;review.creatorFeedback=clean(feedback);review.status='reviewed';review.reviewedBy=reviewer;review.updatedAt=now();
    const grade=data.gradingResults.find(g=>g.attemptId===review.attemptId&&g.questionId===review.questionId);grade.marksAwarded=awarded;grade.status='reviewed';grade.gradedBy=reviewer;grade.gradedAt=now();
    const attempt=data.quizAttempts.find(a=>a.id===review.attemptId),pending=data.manualReviews.some(r=>r.attemptId===attempt.id&&r.status!=='reviewed');attempt.marksObtained=Number(data.gradingResults.filter(g=>g.attemptId===attempt.id).reduce((n,g)=>n+g.marksAwarded,0).toFixed(2));attempt.status=pending?'awaiting_manual_review':'fully_reviewed';attempt.reviewState=pending?'pending':'final';attempt.updatedAt=now();audit(data,'manual_grade_changed',review.id,{marks:awarded,reviewer});store().write(data);return review;
  }
  function resultFor(id){const data=snapshot(),attempt=data.quizAttempts.find(a=>a.id===id);if(!attempt)throw new Error('Attempt not found.');return{attempt:clone(attempt),answers:clone(data.attemptAnswers.filter(a=>a.attemptId===id)),grades:clone(data.gradingResults.filter(g=>g.attemptId===id)),reviews:clone(data.manualReviews.filter(r=>r.attemptId===id)),performances:clone(data.topicPerformances.filter(p=>p.attemptId===id)),recommendations:clone(data.revisionRecommendations.filter(r=>r.attemptId===id))};}
  function calculateInsights(data,attempt){
    const grades=data.gradingResults.filter(g=>g.attemptId===attempt.id),answers=data.attemptAnswers.filter(a=>a.attemptId===attempt.id),groups=new Map();
    attempt.questionSnapshot.forEach(q=>{const keys=[['subject',tagValue(q.tags,'subject')],['chapter',tagValue(q.tags,'chapter')],['topic',tagValue(q.tags,'topic')],['subtopic',tagValue(q.tags,'subtopic')],['difficulty',q.difficulty],['bloom',q.bloomLevel],['type',q.type]];keys.forEach(([kind,name])=>{const key=`${kind}:${name}`,v=groups.get(key)||{kind,name,questions:[],marks:0,max:0,time:0};v.questions.push(q);const g=grades.find(x=>x.questionId===q.id);v.marks+=g?.marksAwarded||0;v.max+=q.marks;v.time+=data.attemptQuestionStates.find(s=>s.attemptId===attempt.id&&s.questionId===q.id)?.timeSpentSeconds||0;groups.set(key,v);});});
    groups.forEach(v=>data.topicPerformances.push({id:uid('performance'),attemptId:attempt.id,studentId:attempt.studentId,kind:v.kind,name:v.name,attempted:v.questions.filter(q=>answers.some(a=>a.questionId===q.id)).length,correct:v.questions.filter(q=>grades.find(g=>g.questionId===q.id)?.correct).length,accuracy:v.questions.length?Number((v.questions.filter(q=>grades.find(g=>g.questionId===q.id)?.correct).length/v.questions.length*100).toFixed(1)):0,averageMarks:v.max?Number((v.marks/v.max*100).toFixed(1)):0,averageTimeSeconds:v.questions.length?Math.round(v.time/v.questions.length):0,createdAt:now()}));
    const topicRows=[...groups.values()].filter(v=>['topic','subtopic'].includes(v.kind));
    topicRows.forEach(v=>{const accuracy=v.questions.length?grades.filter(g=>v.questions.some(q=>q.id===g.questionId)&&g.correct).length/v.questions.length*100:0,history=data.topicPerformances.filter(p=>p.studentId===attempt.studentId&&p.kind===v.kind&&p.name===v.name),evidence=[];if(accuracy<60)evidence.push(`${Math.round(accuracy)}% accuracy`);if(v.questions.length<2)return;const score=Math.max(0,Math.min(100,100-accuracy+(history.length>1?10:0)));let weak=data.weakTopics.find(w=>w.studentId===attempt.studentId&&w.kind===v.kind&&w.name===v.name);const status=score<20?'mastered':history.length>1&&accuracy>=60?'improving':weak?'needs_revision':'newly_identified';const record={studentId:attempt.studentId,kind:v.kind,name:v.name,weaknessScore:Number(score.toFixed(1)),evidence,numberOfAttempts:history.length,lastAttemptedAt:attempt.endTime,status,improvementState:status};if(weak)Object.assign(weak,record);else data.weakTopics.push({id:uid('weak_topic'),...record});
      if(score>=40){data.revisionRecommendations.push({id:uid('recommendation'),attemptId:attempt.id,studentId:attempt.studentId,type:'revise_section',title:`Revise ${v.name}`,reason:`${grades.filter(g=>v.questions.some(q=>q.id===g.questionId)&&!g.correct).length} of ${v.questions.length} questions in ${v.name} need reinforcement.`,targetType:v.kind,targetName:v.name,dueAt:new Date(Date.now()+(score>=70?1:3)*86400000).toISOString(),status:'pending',createdAt:now()});event(data,attempt,'weak_topic_detected',{kind:v.kind,name:v.name,score});}
    });
    const past=data.quizAttempts.filter(a=>a.studentId===attempt.studentId&&terminal.has(a.status)),avg=past.length?past.reduce((n,a)=>n+(a.maximumMarks?a.marksObtained/a.maximumMarks*100:0),0)/past.length:0,hard=attempt.questionSnapshot.filter(q=>q.difficulty==='hard').length,level=past.length<1?'not_attempted':past.length<2?'beginning':avg<50?'learning':avg<65?'developing':avg<80||!hard?'proficient':'mastered';let mastery=data.studentMasteries.find(m=>m.studentId===attempt.studentId&&m.projectId===attempt.projectId);const evidence={attempts:past.length,averageScore:Number(avg.toFixed(1)),hardQuestions:hard,lastAttemptAt:attempt.endTime};if(mastery)Object.assign(mastery,{level,evidence,updatedAt:now()});else data.studentMasteries.push({id:uid('mastery'),studentId:attempt.studentId,projectId:attempt.projectId,level,evidence,createdAt:now(),updatedAt:now()});
  }
  function updateQuestionStats(data,attempt){attempt.questionSnapshot.forEach(q=>{const grade=data.gradingResults.find(g=>g.attemptId===attempt.id&&g.questionId===q.id),answered=data.attemptAnswers.some(a=>a.attemptId===attempt.id&&a.questionId===q.id),state=data.attemptQuestionStates.find(s=>s.attemptId===attempt.id&&s.questionId===q.id);let stat=data.questionStatistics.find(s=>s.questionId===q.id);if(!stat){stat={id:uid('question_stat'),questionId:q.id,quizId:attempt.quizId,attempts:0,correct:0,incorrect:0,skipped:0,totalTimeSeconds:0,totalMarks:0,optionSelections:{},createdAt:now()};data.questionStatistics.push(stat);}stat.attempts++;if(!answered)stat.skipped++;else if(grade?.correct)stat.correct++;else stat.incorrect++;stat.totalTimeSeconds+=state?.timeSpentSeconds||0;stat.totalMarks+=grade?.marksAwarded||0;stat.correctPercentage=Number((stat.correct/stat.attempts*100).toFixed(1));stat.skipPercentage=Number((stat.skipped/stat.attempts*100).toFixed(1));stat.averageTimeSeconds=Math.round(stat.totalTimeSeconds/stat.attempts);stat.warning=stat.attempts<5?null:stat.correctPercentage>95?'possibly_too_easy':stat.correctPercentage<20?'possibly_too_hard':null;stat.updatedAt=now();});}
  function adaptiveSelection(quizId,studentId,count=10){const data=snapshot(),questions=data.quizQuestions.filter(q=>q.quizId===quizId&&!q.deletedAt),weak=data.weakTopics.filter(w=>w.studentId===studentId&&['newly_identified','needs_revision'].includes(w.status)).sort((a,b)=>b.weaknessScore-a.weaknessScore),selected=[];weak.forEach(w=>questions.filter(q=>(q.tags||[]).some(t=>t.toLowerCase()===`${w.kind}:${w.name}`.toLowerCase())).forEach(q=>{if(selected.length<count&&!selected.includes(q))selected.push(q);}));questions.sort((a,b)=>a.difficultyWeight-b.difficultyWeight).forEach(q=>{if(selected.length<count&&!selected.includes(q))selected.push(q);});const log={id:uid('adaptive_log'),quizId,studentId,selectedQuestionIds:selected.map(q=>q.id),reason:weak.length?`Prioritized weak area: ${weak[0].name}`:'Balanced practice because no stable weak topic exists yet.',rulesVersion:1,createdAt:now()};data.adaptiveSelectionLogs.push(log);store().write(data);return log;}
  function retake(attemptId,kind){const old=attemptFor(attemptId);if(!old)throw new Error('Attempt not found.');const data=snapshot(),grades=data.gradingResults.filter(g=>g.attemptId===attemptId),answers=data.attemptAnswers.filter(a=>a.attemptId===attemptId);let ids=null;if(kind==='incorrect')ids=grades.filter(g=>!g.correct).map(g=>g.questionId);if(kind==='unanswered')ids=old.questionSnapshot.filter(q=>!answers.some(a=>a.questionId===q.id)).map(q=>q.id);if(kind==='adaptive')ids=adaptiveSelection(old.quizId,old.studentId,Math.min(10,old.questionSnapshot.length)).selectedQuestionIds;return startAttempt(old.quizId,old.studentId,{questionIds:ids,mode:kind==='adaptive'?'revision':old.quizMode,sourceAttemptId:old.id,randomize:true});}
  function analytics(quizId){const data=snapshot(),attempts=data.quizAttempts.filter(a=>a.quizId===quizId&&terminal.has(a.status)),scores=attempts.map(a=>a.maximumMarks?a.marksObtained/a.maximumMarks*100:0).sort((a,b)=>a-b);return{totalAttempts:attempts.length,completionRate:data.quizAttempts.filter(a=>a.quizId===quizId).length?Number((attempts.length/data.quizAttempts.filter(a=>a.quizId===quizId).length*100).toFixed(1)):0,averageScore:scores.length?Number((scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1)):0,medianScore:scores.length?Number((scores[Math.floor((scores.length-1)/2)]+scores[Math.ceil((scores.length-1)/2)])/2):0,averageTimeSeconds:attempts.length?Math.round(attempts.reduce((n,a)=>n+a.timeSpentSeconds,0)/attempts.length):0,highest:scores.length?scores[scores.length-1]:0,lowest:scores.length?scores[0]:0,awaitingReview:data.manualReviews.filter(r=>attempts.some(a=>a.id===r.attemptId)&&r.status!=='reviewed').length,questionStatistics:clone(data.questionStatistics.filter(s=>s.quizId===quizId)),weakTopics:clone(data.weakTopics),attempts:clone(attempts.slice(0,100))};}
  function updateCompletion(data,attempt){const answers=data.attemptAnswers.filter(a=>a.attemptId===attempt.id&&(!Array.isArray(a.response)?Boolean(a.response):a.response.length));attempt.completionPercentage=attempt.questionSnapshot.length?Number((answers.length/attempt.questionSnapshot.length*100).toFixed(1)):0;attempt.updatedAt=now();}
  function event(data,attempt,type,details){data.progressEvents.push({id:uid('progress_event'),studentId:attempt.studentId,projectId:attempt.projectId,quizId:attempt.quizId,attemptId:attempt.id,type,details,createdAt:now()});}
  function audit(data,type,entityId,details){data.assessmentAuditLogs.push({id:uid('audit'),type,entityId,details,createdAt:now()});}
  window.TeachCurioAssessment={startAttempt,attemptFor,attemptsFor,payload,saveAnswer,setQuestionState,pause,resume,submitAttempt,gradeQuestion,reviewManual,resultFor,retake,adaptiveSelection,analytics};
})();
