(function(){
  const A=window.RupaiAuth,$=selector=>document.querySelector(selector),params=new URLSearchParams(location.search);
  const screen=$('#screen'),errors=$('#errorSummary'),returnTo=A.safeReturn(params.get('returnTo'),'index.html');
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const go=view=>{location.href=`auth.html?view=${encodeURIComponent(view)}&returnTo=${encodeURIComponent(returnTo)}`};
  function showError(error){errors.hidden=false;errors.textContent=error?.message||'Something went wrong. Please try again.';errors.focus();}
  function clearError(){errors.hidden=true;errors.textContent='';}
  function passwordField(name,label='Password',autocomplete='current-password'){return `<label>${label}<span class="password-row"><input name="${name}" type="password" autocomplete="${autocomplete}" minlength="${A.config.minimumPasswordLength}" maxlength="256" aria-describedby="passwordHelp" required><button type="button" data-show-password>Show</button></span></label>`}
  function wirePassword(){document.querySelectorAll('[data-show-password]').forEach(button=>button.onclick=()=>{const input=button.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';button.textContent=input.type==='password'?'Show':'Hide';});}
  function heading(title,lead){return `<h2>${title}</h2><p class="lead">${lead}</p>`}
  function renderSignIn(){
    screen.innerHTML=`${heading('Welcome back','Sign in to your development account on this device.')}<form class="auth-form" id="signIn"><label>Email<input name="email" type="email" autocomplete="username" required></label>${passwordField('password')}<label class="check"><input name="remember" type="checkbox"><span>Remember this session on this device</span></label><button class="primary">Sign in</button><div class="form-actions"><button type="button" class="link-button" data-go="forgot">Forgot password?</button><button type="button" class="link-button" data-go="signup">Create student account</button></div><p class="fine-print">Local sign-in does not provide cloud backup or multi-device access.</p></form><button class="secondary" id="guest">Continue as guest</button>`;
    wirePassword();wireLinks();$('#guest').onclick=()=>{A.startGuest();location.href=returnTo};
    $('#signIn').onsubmit=async event=>{event.preventDefault();clearError();const button=event.submitter;button.disabled=true;button.textContent='Signing in…';try{const data=new FormData(event.currentTarget);await A.signIn({email:data.get('email'),password:data.get('password'),remember:data.get('remember')==='on'});location.href=returnTo}catch(error){showError(error);button.disabled=false;button.textContent='Sign in';}};
  }
  function renderSignUp(){
    screen.innerHTML=`${heading('Create a student account','Public registration always starts with the Student role. Creator, teacher and administrator access requires approval.')}<form class="auth-form" id="signUp"><label>Display name<input name="displayName" autocomplete="name" maxlength="80" required></label><label>Email<input name="email" type="email" autocomplete="username" required></label>${passwordField('password','Password','new-password')}<p id="passwordHelp" class="fine-print">Use at least ${A.config.minimumPasswordLength} characters. Long passwords and password-manager paste are supported.</p><label>How will you use Rupai’s World?<select name="intendedUsage"><option value="learning">Learn as a student</option><option value="creator_interest">Interested in creator access</option><option value="teacher_interest">Interested in teacher access</option><option value="guardian_interest">Support a learner</option></select></label><p class="fine-print">All public accounts remain Student accounts until an authorized invitation or approval is completed.</p><label>Age group<select name="ageGroup"><option value="unknown">Prefer not to say</option><option value="child">Child</option><option value="teen">Teen</option><option value="adult">Adult</option></select></label><label class="check"><input name="terms" type="checkbox" required><span>I accept the current Terms for this local development account.</span></label><label class="check"><input name="privacy" type="checkbox" required><span>I accept the current Privacy notice.</span></label><button class="primary">Create student account</button><button type="button" class="link-button" data-go="signin">Already have an account?</button></form>`;
    wirePassword();wireLinks();$('#signUp').onsubmit=async event=>{event.preventDefault();clearError();const button=event.submitter;button.disabled=true;try{const data=new FormData(event.currentTarget);await A.signUp({displayName:data.get('displayName'),email:data.get('email'),password:data.get('password'),intendedUsage:data.get('intendedUsage'),ageGroup:data.get('ageGroup'),termsAccepted:data.get('terms')==='on',privacyAccepted:data.get('privacy')==='on'});await A.signIn({email:data.get('email'),password:data.get('password'),remember:true});renderMigration()}catch(error){showError(error);button.disabled=false;}};
  }
  function renderMigration(){
    const found=A.findLocalData();if(!found.found){location.href=returnTo;return}
    screen.innerHTML=`${heading('Learning data found','Learning data was found on this device. It will never be attached automatically.')}<section class="status-panel"><strong>Available local records</strong><p>${Object.entries(found.counts).filter(([,count])=>count).map(([key,count])=>`${esc(key)}: ${count}`).join('<br>')}</p></section><div class="choice-grid"><button class="primary" data-migrate="attach">Attach to account</button><button class="secondary" data-migrate="review">Review data</button><button class="secondary" data-migrate="keep_separate">Keep separate</button><button class="secondary" data-migrate="skip">Skip for now</button></div><button class="link-button" id="backup">Export backup first</button>`;
    $('[data-migrate="review"]').onclick=()=>alert(JSON.stringify(found.counts,null,2));
    document.querySelectorAll('[data-migrate]:not([data-migrate="review"])').forEach(button=>button.onclick=()=>{try{A.migrateLocalData(button.dataset.migrate);location.href=returnTo}catch(error){showError(error)}});
    $('#backup').onclick=()=>download('rupais-world-account-backup.json',A.exportAccountData());
  }
  function renderForgot(){const status=A.requestPasswordReset();screen.innerHTML=`${heading('Reset password','Password recovery requires a real email provider.')}<section class="status-panel"><strong>Email delivery unavailable</strong><p>${esc(status.message)}</p></section><button class="secondary" data-go="signin">Back to sign in</button>`;wireLinks()}
  function renderVerify(){const status=A.verifyEmail();screen.innerHTML=`${heading('Verify email','Verification is prepared for a future authentication provider.')}<section class="status-panel"><strong>Local development account</strong><p>${esc(status.message)}</p></section><button class="secondary" data-go="signin">Back to sign in</button>`;wireLinks()}
  function renderDenied(){screen.innerHTML=`${heading('Access denied','Your account is signed in but does not have permission to open that page.')}<section class="status-panel"><strong>Permission required</strong><p>Ask an authorized administrator to approve the required role. Student and guardian accounts cannot access creator tools.</p></section><button class="primary" onclick="location.href='../index.html'">Go to Rupai’s World</button><button class="secondary" id="different">Use a different account</button>`;$('#different').onclick=()=>{A.signOut();go('signin')}}
  function renderPending(){screen.innerHTML=`${heading('Account restricted','This account is suspended, deactivated, or waiting for deletion review.')}<section class="status-panel"><p>Access is blocked locally. A future production service will provide recovery and support workflows.</p></section><button class="secondary" id="out">Sign out</button>`;$('#out').onclick=()=>{A.signOut();go('signin')}}
  function renderExpired(){screen.innerHTML=`${heading('Session expired','For your protection, this local session is no longer active.')}<button class="primary" data-go="signin">Sign in again</button>`;wireLinks()}
  function renderSetup(){screen.innerHTML=`${heading('Set up the local workspace owner','This one-time controlled setup creates the first Creator account on this device. It does not create a cloud account.')}<form class="auth-form" id="ownerSetup"><label>Display name<input name="displayName" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="username" required></label>${passwordField('password','Password','new-password')}<p id="passwordHelp" class="fine-print">Use at least ${A.config.minimumPasswordLength} characters. The password is transformed with browser cryptography before local storage.</p><button class="primary">Create local workspace owner</button><button type="button" class="link-button" data-go="welcome">Cancel</button></form>`;wirePassword();wireLinks();$('#ownerSetup').onsubmit=async event=>{event.preventDefault();clearError();const d=new FormData(event.currentTarget),button=event.submitter;button.disabled=true;try{await A.bootstrapDevelopmentOwner({displayName:d.get('displayName'),email:d.get('email'),password:d.get('password')});await A.signIn({email:d.get('email'),password:d.get('password'),remember:true});location.href=returnTo}catch(error){showError(error);button.disabled=false;}}}
  function renderWelcome(){screen.innerHTML=`${heading('Choose how to continue','Accounts are local-development only until a production provider is connected.')}<div class="choice-grid"><button class="primary" data-go="signin">Sign in</button><button class="secondary" data-go="signup">Create student account</button><button class="secondary" id="guest">Guest Mode</button><button class="secondary" data-go="verify">Email verification</button>${A.developmentSetupAvailable()?'<button class="secondary" data-go="setup">Set up local workspace owner</button>':''}</div>`;wireLinks();$('#guest').onclick=()=>{A.startGuest();location.href=returnTo}}
  function wireLinks(){document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>go(button.dataset.go))}
  function download(name,text){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
  function render(){clearError();const view=params.get('view')||'welcome';({signin:renderSignIn,signup:renderSignUp,forgot:renderForgot,reset:renderForgot,verify:renderVerify,pending:renderPending,denied:renderDenied,expired:renderExpired,migration:renderMigration,setup:renderSetup,welcome:renderWelcome}[view]||renderWelcome)()}
  function offline(){const banner=$('#offline');banner.hidden=navigator.onLine!==false}window.addEventListener('online',offline);window.addEventListener('offline',offline);offline();render();
})();
