(function(){
  'use strict';
  const G=TeachCurioKnowledgeGraph,session=window.__knowledgeSession,$=q=>document.querySelector(q),actor=()=>({userId:session.userId,permissions:session.permissions||[]}),escape=value=>{const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML},pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());let current=null;
  function notice(message,error=false){$('#notice').textContent=message;$('#notice').classList.toggle('error',error)}
  function fill(){const data=G.list(actor());$('#nodeOptions').innerHTML=data.nodes.map(x=>`<option value="${escape(x.title)}">${escape(x.type)} · ${escape(x.subject||'No subject')}</option>`).join('');$('#relationshipForm [name=type]').innerHTML=data.types.map(x=>`<option value="${x}">${pretty(x)}</option>`).join('');notice(data.provider.message);return data}
  function link(item,extra=''){return`<div class="insight"><button data-node="${escape(item.node?.title)}">${escape(item.node?.title||'Unknown concept')}</button>${extra}</div>`}
  function render(center){const student=$('#student').value.trim()||'student_placeholder',map=G.neighbourhood({center,depth:Number($('#depth').value)},actor());if(!map.center){notice(map.message,true);return}current=map.center.title;$('#search').value=current;$('#mapTitle').textContent=current;$('#mapCount').textContent=`${map.nodes.length} nodes · ${map.relationships.length} links`;$('#graph').innerHTML=map.nodes.map(node=>{const links=map.relationships.filter(x=>x.fromNodeId===node.id||x.toNodeId===node.id),cross=links.some(x=>x.crossSubject);return`<button class="graph-node ${node.id===map.center.id?'center':''} ${cross?'cross':''}" data-node="${escape(node.title)}" role="treeitem" aria-expanded="${node.id===map.center.id}"><strong>${escape(node.title)}</strong><small>${pretty(node.type)} · ${escape(node.subject||'Subject not set')}</small><small>${links.length} verified link${links.length===1?'':'s'}</small></button>`}).join('');
    const prereq=G.prerequisites(student,map.center.id,actor());$('#prerequisites').innerHTML=prereq.recommendations.length?prereq.recommendations.map(x=>link(x,`<small>${pretty(x.confidence)} · Optional review</small>`)).join(''):`<p class="empty-copy">${pretty(prereq.outcome)}. Navigation is never forced.</p>`;
    const revision=G.revisionLinks(student,map.center.id,actor());$('#revision').innerHTML=revision.length?revision.map(x=>link(x,`<small>${pretty(x.type)} · ${pretty(x.confidence)}</small>`)).join(''):'<p class="empty-copy">No connected concept currently has verified revision evidence.</p>';
    const mistakes=G.misconceptions(map.center.id,actor());$('#misconceptions').innerHTML=mistakes.length?mistakes.map(x=>`<div class="insight"><b>${escape(x.concept)} vs ${escape(x.confusedWith)}</b><small>${escape(x.clarification)}</small></div>`).join(''):'<p class="empty-copy">No approved misconception link is recorded.</p>';
    const curiosity=G.curiosity(map.center.id,actor());$('#curiosity').innerHTML=curiosity.length?curiosity.map(x=>link(x,`<small>${escape(x.prompt)} Optional.</small>`)).join(''):'<p class="empty-copy">No verified curiosity path is available.</p>';
    const confidence=G.confidence(student,map.center.id,actor());$('#confidence').innerHTML=`<p class="status-${confidence.confidence}"><b>${pretty(confidence.confidence)}</b></p><p>${escape(confidence.reason)}</p><small>${confidence.evidenceCount} local evidence record${confidence.evidenceCount===1?'':'s'} · Never fabricated</small>`;
    document.querySelectorAll('[data-node]').forEach(button=>button.onclick=()=>render(button.dataset.node));notice(`Showing verified connections for ${current}. Click any node to expand it.`)
  }
  $('#sync').onclick=()=>{const out=G.sync(actor());fill();notice(`${out.nodeCount} lesson and structure nodes synchronised from local approved content.`);if(out.nodes[0])render(out.nodes[0].title)};$('#open').onclick=()=>render($('#search').value);$('#search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();render(e.target.value)}};$('#depth').onchange=()=>current&&render(current);$('#add').onclick=()=>$('#relationshipDialog').showModal();$('#relationshipForm').onsubmit=e=>{if(e.submitter?.value!=='approve')return;e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{G.addRelationship(data,actor());e.currentTarget.reset();$('#relationshipDialog').close();fill();render(data.from);notice('Creator-verified relationship approved and added to the graph.')}catch(error){notice(error.message,true)}};
  document.addEventListener('DOMContentLoaded',()=>{fill();const synced=G.sync(actor());fill();if(synced.nodes[0])render(synced.nodes[0].title);else notice('Create and approve a lesson structure to begin the knowledge map.')});
})();
