(function(){
  'use strict';
  const G=TeachCurioKnowledgeGraph,P=TeachCurioLearningPaths,session=window.__pathSession,$=q=>document.querySelector(q),actor=()=>({userId:session.userId,permissions:session.permissions||[]}),esc=value=>{const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML},pretty=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());let lastInput=null;
  function setup(){G.sync(actor());const graph=G.list(actor()),nodes=graph.nodes.filter(x=>x.verified&&['chapter','topic','subtopic','concept'].includes(x.type));$('#pathNodes').innerHTML=nodes.map(x=>`<option value="${esc(x.title)}">${esc(x.subject||'No subject')} · ${pretty(x.type)}</option>`).join('');if(nodes[0])$('#target').value=nodes[0].title;$('#provider').textContent='Learning paths use local progress and creator-approved dependencies. No AI provider is connected.';renderProgress(P.progress($('#student').value,actor()))}
  function renderProgress(p){$('#completed').textContent=p.completed;$('#partial').textContent=p.partial;$('#skipped').textContent=p.skipped;$('#revisionCount').textContent=p.needsRevision;$('#mastery').textContent=`${p.masteryPercent}%`}
  function step(row,path){const locked=row.locked,actions=locked?'<span class="lock">Complete prerequisites first</span>':`<div class="step-actions"><button data-progress="completed" data-node="${row.nodeId}">Complete</button><button data-progress="partial" data-node="${row.nodeId}">Partially learned</button><button data-progress="needs_revision" data-node="${row.nodeId}">Revise</button><button data-progress="skipped" data-node="${row.nodeId}">Skip for now</button></div>`;return`<article class="path-step ${locked?'locked':''} ${row.kind==='revision'?'revision':''} ${row.state==='completed'?'completed':''}" data-order="${row.order}"><strong>${esc(row.title)}</strong><small>${esc(row.subject||'Subject not set')} · ${pretty(row.kind)} · ${pretty(row.state)}</small><small>${esc(row.reason)}</small>${actions}</article>`}
  function render(result){renderProgress(result.progress);const r=result.recommendation;$('#recommendation').innerHTML=`<h2>${esc(r.nextTitle||r.milestone||'Path complete')}</h2><p>${esc(r.message)}</p><small>${esc(r.reason)} · ${pretty(r.goal)} · Local evidence only</small>`;$('#paths').innerHTML=result.paths.map(path=>`<article class="path-card"><h2>${pretty(path.variant)}</h2><p>${pretty(path.level)} · ${pretty(path.goal)} · ${path.steps.length} remaining step${path.steps.length===1?'':'s'}</p>${path.steps.length?path.steps.map(row=>step(row,path)).join(''):'<p>This route has no unfinished evidence-backed steps.</p>'}</article>`).join('');document.querySelectorAll('[data-progress]').forEach(button=>button.onclick=()=>{P.updateProgress(lastInput.studentId,button.dataset.node,{state:button.dataset.progress,reason:'Updated from the local Learning Paths workspace.'},actor());generate()})}
  function generate(){try{const studentId=$('#student').value.trim()||session.userId,target=$('#target').value.trim(),goal=$('#goal').value,level=$('#level').value;P.saveGoal(studentId,{type:goal,title:pretty(goal),targetNodeId:target},actor());lastInput={studentId,target,goal,level};render(P.generate(lastInput,actor()))}catch(error){$('#provider').textContent=error.message;$('#provider').classList.add('error')}}
  $('#generate').onclick=generate;$('#student').onchange=()=>renderProgress(P.progress($('#student').value.trim()||session.userId,actor()));document.addEventListener('DOMContentLoaded',setup);
})();
