(function(){
  if(!window.__studioSession)return;
  const $=selector=>document.querySelector(selector),store=window.TeachCurioStore,quizService=window.TeachCurioQuiz,writing=window.TeachCurioWriting,session=window.__studioSession;
  const state={projectId:new URLSearchParams(location.search).get('project'),page:1,pageSize:10,editingId:null,pendingPrompt:null};
  const TYPES={mcq:'Multiple Choice (MCQ)',multiple_correct:'Multiple Correct',true_false:'True / False',fill_blank:'Fill in the Blank',match_following:'Match the Following',arrange_order:'Arrange in Correct Order',image_based:'Image Based Question',map_based:'Map Based Question',timeline:'Timeline Question',assertion_reason:'Assertion & Reason',very_short:'Very Short Answer',long_answer:'Long Answer'};
  const esc=value=>{const node=document.createElement('div');node.textContent=value||'';return node.innerHTML;};
  const project=()=>store.getProject(state.projectId),quiz=()=>quizService.quizFor(state.projectId),draft=()=>writing.draftFor(state.projectId);
  function toast(message,error=false){const node=$('#toast');node.textContent=message;node.style.background=error?'#8d3348':'#41285f';node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3200);}
  function saveState(text,error=false){$('#saveState').textContent=text;$('#saveState').style.background=error?'#ffe0e0':'#e5f5eb';}
  function renderGate(){
    const current=quiz(),gate=$('#quizGate'),workspace=$('#quizWorkspace');
    if(current){gate.innerHTML='';workspace.hidden=false;return;}
    workspace.hidden=true;
    try{const approved=draft();if(!approved||approved.status!=='approved'||!approved.approvedVersionId)throw new Error('Approve the Lesson Draft before creating a quiz.');gate.innerHTML=`<section class="empty-quiz"><span class="eyebrow">Approved lesson ready</span><h2>Create its assessment</h2><p>Start manually, then optionally add AI-generated questions for a hybrid quiz.</p><button class="primary" id="createQuiz">Create Quiz</button></section>`;}
    catch(error){gate.innerHTML=`<section class="empty-quiz"><h2>Approved lesson required</h2><p>${esc(error.message)}</p><a class="secondary" href="lesson.html?project=${encodeURIComponent(state.projectId)}">Return to Lesson</a></section>`;}
  }
  function renderSettings(){
    const current=quiz();if(!current)return;$('#quizTitle').value=current.title;$('#quizMode').value=current.mode;$('#randomQuestions').checked=current.randomizeQuestions;$('#randomOptions').checked=current.randomizeOptions;
  }
  function renderQuestions(){
    const current=quiz();if(!current)return;const all=quizService.questionsFor(current.id),pages=Math.max(1,Math.ceil(all.length/state.pageSize));state.page=Math.min(state.page,pages);const list=all.slice((state.page-1)*state.pageSize,state.page*state.pageSize);
    $('#questionCount').textContent=all.length;
    $('#questionList').innerHTML=list.length?list.map((question,index)=>`<article class="question-card"><div class="question-number">${(state.page-1)*state.pageSize+index+1}</div><div><h3>${esc(question.prompt)}</h3><div class="question-meta"><span>${esc(TYPES[question.type])}</span><span>${question.difficulty}</span><span>${question.bloomLevel}</span><span>${question.marks} mark${question.marks===1?'':'s'}</span><span>${question.origin}</span>${question.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><div class="question-actions"><button class="secondary" data-edit="${question.id}">Edit</button><button class="secondary" data-duplicate="${question.id}">Duplicate</button><button class="secondary" data-move="${question.id}" data-direction="-1" aria-label="Move question up">↑</button><button class="secondary" data-move="${question.id}" data-direction="1" aria-label="Move question down">↓</button><button class="danger" data-delete="${question.id}">Delete</button></div></article>`).join(''):'<section class="empty-quiz"><h2>No questions yet</h2><p>Add every supported question type manually, or use the AI provider when connected.</p></section>';
    $('#pagination').innerHTML=Array.from({length:pages},(_,index)=>`<button class="secondary ${index+1===state.page?'active':''}" data-page="${index+1}">${index+1}</button>`).join('');
  }
  function render(){renderGate();if(quiz()){renderSettings();renderQuestions();}}
  function optionCount(type){return type==='true_false'?2:['mcq','multiple_correct','image_based','assertion_reason'].includes(type)?4:0;}
  function renderOptions(options=[]){
    const type=$('#questionType').value,count=optionCount(type),multiple=type==='multiple_correct';$('#correctTextField').hidden=Boolean(count);
    if(!count){$('#optionEditor').innerHTML='';return;}
    const values=type==='true_false'?(options.length?options:[{text:'True'},{text:'False'}]):options;
    $('#optionEditor').innerHTML=`<fieldset><legend>Answer options</legend>${Array.from({length:count},(_,index)=>{const item=values[index]||{};return`<div class="option-row"><input type="${multiple?'checkbox':'radio'}" name="correctOption" value="${index}" ${item.isCorrect?'checked':''} aria-label="Option ${index+1} is correct"><input name="optionText${index}" value="${esc(item.text||'')}" placeholder="Option ${index+1}" required><input name="optionExplanation${index}" value="${esc(item.explanation||'')}" placeholder="Why correct or wrong"></div>`;}).join('')}</fieldset>`;
  }
  function openQuestion(questionId=null){
    const form=$('#questionForm');form.reset();state.editingId=questionId;form.elements.id.value=questionId||'';$('#questionDialogTitle').textContent=questionId?'Edit Question':'Add Question';
    if(questionId){const question=quizService.questionsFor(quiz().id).find(item=>item.id===questionId);if(!question)return;Object.entries(question).forEach(([key,value])=>{if(form.elements[key]&&typeof value!=='object')form.elements[key].value=value??'';});form.elements.tags.value=question.tags.join(', ');renderOptions(quizService.optionsFor(questionId));}
    else{form.elements.difficulty.value='medium';form.elements.bloomLevel.value='understand';form.elements.marks.value=1;form.elements.negativeMarks.value=0;form.elements.timeLimitSeconds.value=0;form.elements.difficultyWeight.value=1;$('#questionType').value='mcq';renderOptions();}
    $('#questionDialog').showModal();
  }
  function formQuestion(){
    const form=$('#questionForm'),data=new FormData(form),type=data.get('type'),count=optionCount(type),correct=new Set(data.getAll('correctOption').map(Number)),options=Array.from({length:count},(_,index)=>({text:data.get(`optionText${index}`),isCorrect:correct.has(index),explanation:data.get(`optionExplanation${index}`)}));
    return{input:{type,prompt:data.get('prompt'),correctText:data.get('correctText'),explanation:data.get('explanation'),wrongAnswerExplanation:data.get('wrongAnswerExplanation'),hint:data.get('hint'),memoryTrick:data.get('memoryTrick'),referenceSectionId:data.get('referenceSectionId'),imageUrl:data.get('imageUrl'),difficulty:data.get('difficulty'),bloomLevel:data.get('bloomLevel'),marks:data.get('marks'),negativeMarks:data.get('negativeMarks'),timeLimitSeconds:data.get('timeLimitSeconds'),difficultyWeight:data.get('difficultyWeight'),tags:String(data.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),origin:'creator_added',status:'draft'},options};
  }
  function renderPreview(){
    const current=quiz(),questions=quizService.questionsFor(current.id),ordered=current.randomizeQuestions?[...questions].sort(()=>Math.random()-.5):questions;
    $('#previewTitle').textContent=current.title;$('#previewContent').innerHTML=ordered.length?ordered.map((question,index)=>{let options=quizService.optionsFor(question.id);if(current.randomizeOptions)options=[...options].sort(()=>Math.random()-.5);return`<article class="preview-question"><span class="eyebrow">${TYPES[question.type]} · ${question.marks} marks</span><h3>${index+1}. ${esc(question.prompt)}</h3>${question.imageUrl?`<img src="${esc(question.imageUrl)}" alt="Question reference image" onerror="this.replaceWith(Object.assign(document.createElement('p'),{textContent:'Broken image'}))">`:''}${options.map(option=>`<label class="preview-option"><input type="${question.type==='multiple_correct'?'checkbox':'radio'}" name="preview-${question.id}"> ${esc(option.text)}</label>`).join('')}${!options.length?'<textarea placeholder="Write your answer"></textarea>':''}${question.hint?`<details><summary>Hint</summary><p>${esc(question.hint)}</p></details>`:''}</article>`;}).join(''):'<div class="empty-quiz">No questions to preview.</div>';$('#previewDialog').showModal();
  }
  function renderLibrary(){
    const results=quizService.searchLibrary($('#librarySearch').value);$('#libraryList').innerHTML=results.length?results.map(question=>`<article class="library-item"><div><strong>${esc(question.prompt)}</strong><div class="question-meta"><span>${TYPES[question.type]}</span>${question.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><button class="secondary" data-reuse="${question.id}">Reuse</button></article>`).join(''):'<p>No matching questions.</p>';
  }
  function renderVersions(){const versions=quizService.versionsFor(quiz().id);$('#versionList').innerHTML=versions.map(version=>`<article class="version-item"><div><strong>Version ${version.version}</strong><small>${version.kind.replaceAll('_',' ')} · ${new Date(version.createdAt).toLocaleString()}</small></div><button class="secondary" data-restore="${version.id}">Restore</button></article>`).join('');}
  async function generateQuiz(){
    const approved=writing.approvedInput(state.projectId),lesson=draft(),enhancement=store.read().learningEnhancements.find(item=>item.projectId===state.projectId),prompt=window.TeachCurioPromptBuilder.buildQuiz(approved,lesson,enhancement,{mode:quiz().mode,count:10,questionTypes:Object.keys(TYPES)});
    state.pendingPrompt=prompt;const run=window.TeachCurioPromptBuilder.record(state.projectId,prompt,session.id,'generateQuiz');window.TeachCurioPromptBuilder.updateRun(run.id,'sent');$('#providerDialog').showModal();$('#providerTitle').textContent='Generating Quiz';$('#providerMessage').textContent='Using approved lesson and learning enhancements only.';
    try{const output=await window.TeachCurioAI.execute('generateQuiz',prompt),valid=window.TeachCurioAI.validateQuizOutput(output);quizService.importQuestions(state.projectId,valid.questions,session.id);window.TeachCurioPromptBuilder.updateRun(run.id,'completed');$('#providerDialog').close();render();toast('AI questions added. You can edit everything.');}
    catch(error){window.TeachCurioPromptBuilder.updateRun(run.id,'failed',error.message);$('#providerTitle').textContent=error.name==='StudioAiUnavailableError'?'AI quiz service is not connected yet.':'Quiz generation failed';$('#providerMessage').textContent=error.message;}
  }
  $('#quizGate').addEventListener('click',event=>{if(event.target.closest('#createQuiz'))try{quizService.createQuiz(state.projectId,{title:`${project().title} Quiz`,mode:'practice'},session.id);render();}catch(error){toast(error.message,true);}});
  ['quizTitle','quizMode','randomQuestions','randomOptions'].forEach(id=>$('#'+id).addEventListener('change',()=>{try{saveState('Saving…');quizService.updateQuiz(state.projectId,{title:$('#quizTitle').value,mode:$('#quizMode').value,randomizeQuestions:$('#randomQuestions').checked,randomizeOptions:$('#randomOptions').checked});saveState('Saved');}catch(error){saveState('Save Failed',true);toast(error.message,true);}}));
  $('#addQuestion').addEventListener('click',()=>openQuestion());$('#questionType').addEventListener('change',()=>renderOptions());
  $('#questionForm').addEventListener('submit',event=>{event.preventDefault();try{const {input,options}=formQuestion();if(state.editingId)quizService.updateQuestion(state.editingId,input,options,session.id);else quizService.addQuestion(state.projectId,input,options,session.id);$('#questionDialog').close();render();toast('Question saved.');}catch(error){toast(error.message,true);}});
  $('#questionList').addEventListener('click',event=>{const edit=event.target.closest('[data-edit]'),duplicate=event.target.closest('[data-duplicate]'),move=event.target.closest('[data-move]'),del=event.target.closest('[data-delete]');try{if(edit)openQuestion(edit.dataset.edit);else if(duplicate){quizService.duplicateQuestion(duplicate.dataset.duplicate,session.id);render();}else if(move){quizService.moveQuestion(move.dataset.move,Number(move.dataset.direction),session.id);render();}else if(del&&confirm('Delete this question? It remains available in version history.')){quizService.deleteQuestion(del.dataset.delete,session.id);render();}}catch(error){toast(error.message,true);}});
  $('#pagination').addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(button){state.page=Number(button.dataset.page);renderQuestions();}});
  $('#previewQuiz').addEventListener('click',renderPreview);$('#questionLibrary').addEventListener('click',()=>{renderLibrary();$('#libraryDialog').showModal();});$('#librarySearch').addEventListener('input',renderLibrary);
  $('#libraryList').addEventListener('click',event=>{const button=event.target.closest('[data-reuse]');if(!button)return;try{quizService.reuseQuestion(state.projectId,button.dataset.reuse,session.id);render();renderLibrary();toast('Question reused.');}catch(error){toast(error.message,true);}});
  $('#quizVersions').addEventListener('click',()=>{if(!quiz())return;renderVersions();$('#versionsDialog').showModal();});$('#versionList').addEventListener('click',event=>{const button=event.target.closest('[data-restore]');if(!button)return;try{quizService.restoreVersion(quiz().id,button.dataset.restore,session.id);$('#versionsDialog').close();render();toast('Quiz version restored.');}catch(error){toast(error.message,true);}});
  $('#generateQuiz').addEventListener('click',generateQuiz);$('#retryQuiz').addEventListener('click',generateQuiz);
  [['closeQuestion','questionDialog'],['cancelQuestion','questionDialog'],['closePreview','previewDialog'],['closeLibrary','libraryDialog'],['closeVersions','versionsDialog'],['closeProvider','providerDialog'],['returnQuiz','providerDialog']].forEach(([button,dialog])=>$('#'+button).addEventListener('click',()=>$('#'+dialog).close()));
  if(!state.projectId||!project()){document.body.innerHTML='<main><h1>Project not found</h1><a href="index.html">Return to Studio</a></main>';return;}
  $('#projectName').textContent=project().title;$('#backLesson').href=`lesson.html?project=${encodeURIComponent(state.projectId)}`;$('#lessonTab').href=`lesson.html?project=${encodeURIComponent(state.projectId)}`;$('#visualAssetsTab').href=`visual-assets.html?project=${encodeURIComponent(state.projectId)}`;$('#studentQuiz').href=`student-assessment.html?project=${encodeURIComponent(state.projectId)}`;$('#assessmentAnalytics').href=`assessment-analytics.html?project=${encodeURIComponent(state.projectId)}`;$('#questionType').innerHTML=Object.entries(TYPES).map(([value,label])=>`<option value="${value}">${label}</option>`).join('');const approved=draft()?.versions.find(item=>item.id===draft()?.approvedVersionId);$('#referenceSection').innerHTML='<option value="">No specific section</option>'+(approved?.sections||[]).filter(item=>!item.deletedAt).map(section=>`<option value="${section.id}">${esc(section.title)}</option>`).join('');render();
})();
