(function(){
  if(!window.__studioSession)return;
  const $=selector=>document.querySelector(selector), store=window.TeachCurioStore, service=window.TeachCurioStructure, session=window.__studioSession;
  const state={projectId:new URLSearchParams(location.search).get('project'),selectedId:null,tab:'metadata',query:'',filter:'all',collapsed:new Set(),deleteId:null,saveTimer:null};
  const labels={subject:'Subject',chapter:'Chapter',topic:'Topic',subtopic:'Subtopic',concept:'Concept',activity:'Activity',quizPlaceholder:'Quiz Placeholder'};
  const esc=value=>{const node=document.createElement('div');node.textContent=value||'';return node.innerHTML;};
  const project=()=>store.getProject(state.projectId), sources=()=>store.getProjectSources(state.projectId), structure=()=>service.ensure(state.projectId);
  function toast(message,error=false){const node=$('#toast');node.textContent=message;node.style.background=error?'#8d3348':'#41285f';node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3300);}
  function saved(){ $('#saveState').className='save-state saving';$('#saveState').textContent='Saving…';clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>{$('#saveState').className='save-state';$('#saveState').textContent='Saved';},450);}
  function descendants(nodes,id){const result=[];const visit=value=>nodes.filter(node=>node.parentId===value).sort((a,b)=>a.sortOrder-b.sortOrder).forEach(node=>{result.push(node);visit(node.id);});visit(id);return result;}
  function visibleNodes(){
    const data=structure(), result=[];const matches=node=>{const sourceText=node.sourceReferences.map(ref=>sources().find(item=>item.id===ref.sourceId)?.title||'').join(' ');const haystack=`${node.title} ${node.keywords.join(' ')} ${sourceText}`.toLowerCase();const queryOk=!state.query||haystack.includes(state.query);const filterOk=state.filter==='all'||(state.filter==='included'&&node.includeInNextPhase)||(state.filter==='excluded'&&!node.includeInNextPhase)||node.verificationStatus===state.filter||node.status===state.filter||node.origin===state.filter;return queryOk&&filterOk;};
    const visit=parentId=>data.nodes.filter(node=>(node.parentId||'')===(parentId||'')).sort((a,b)=>a.sortOrder-b.sortOrder).forEach(node=>{if(matches(node))result.push(node);if(!state.collapsed.has(node.id))visit(node.id);});visit();return result;
  }
  function renderTree(){
    const data=structure(), nodes=visibleNodes();$('#nodeCount').textContent=data.nodes.filter(node=>node.status!=='rejected').length;$('#reviewCount').textContent=data.nodes.filter(node=>node.verificationStatus==='needs_verification').length;$('#sourceCount').textContent=sources().length;
    if(!data.nodes.length){$('#structureTree').innerHTML='<div class="tree-empty"><div><b>✦</b><h3>Build the structure your way</h3><p>AI is optional. Start manually with a Subject, then add only the levels this lesson needs.</p><button class="primary" data-empty-add>Add Subject</button></div></div>';return;}
    $('#structureTree').innerHTML=nodes.length?nodes.map(node=>{const childCount=data.nodes.filter(item=>item.parentId===node.id).length;return `<div class="tree-node ${node.id===state.selectedId?'selected':''} ${node.status==='rejected'?'rejected':''}" role="treeitem" aria-level="${node.depth+1}" aria-selected="${node.id===state.selectedId}" data-node="${node.id}" style="margin-left:${Math.min(node.depth,6)*18}px" tabindex="0">
      <button data-collapse aria-label="${state.collapsed.has(node.id)?'Expand':'Collapse'} ${esc(node.title)}" ${childCount?'':'disabled'}>${childCount?(state.collapsed.has(node.id)?'＋':'−'):'·'}</button><div class="tree-copy"><strong>${esc(node.title)}</strong><small>${labels[node.nodeType]} · ${node.origin.replaceAll('_',' ')}</small></div>
      <div class="node-badges">${node.verificationStatus==='user_approved'?'<span class="node-badge approved">Approved</span>':''}${node.verificationStatus==='needs_verification'?'<span class="node-badge verify">Verify</span>':''}${!node.includeInNextPhase?'<span class="node-badge">Excluded</span>':''}</div></div>`;}).join(''):'<div class="review-empty">No structure items match this search or filter.</div>';
  }
  function parentOptions(node){
    const data=structure(), blocked=node?[node.id,...descendants(data.nodes,node.id).map(item=>item.id)]:[];
    return '<option value="">Structure root</option>'+data.nodes.filter(item=>!blocked.includes(item.id)&&item.status!=='rejected').map(item=>`<option value="${item.id}" ${item.id===node?.parentId?'selected':''}>${'— '.repeat(item.depth)}${esc(item.title)} (${labels[item.nodeType]})</option>`).join('');
  }
  function renderEditor(){
    const data=structure(),node=data.nodes.find(item=>item.id===state.selectedId);
    if(!node){$('#nodeEditor').innerHTML='<div class="editor-empty"><div><b>Choose an item</b><p>Edit its wording, hierarchy, review status and source links here.</p></div></div>';return;}
    $('#nodeEditor').innerHTML=`<form class="node-form" id="editorForm">
      <label>Title<input name="title" value="${esc(node.title)}" maxlength="140" aria-describedby="titleValidation"></label>
      <span class="field-error" id="titleValidation" hidden>A structure title is required.</span>
      ${node.originalTitle?`<small>Original wording: ${esc(node.originalTitle)}</small>`:''}
      <div class="two-fields"><label>Node type<select name="nodeType">${service.TYPES.map(type=>`<option value="${type}" ${type===node.nodeType?'selected':''}>${labels[type]}</option>`).join('')}</select></label><label>Parent<select name="parentId">${parentOptions(node)}</select></label></div>
      <label>Short description<textarea name="description" maxlength="500">${esc(node.description)}</textarea></label><label>Creator notes<textarea name="creatorNotes" maxlength="1000">${esc(node.creatorNotes)}</textarea></label>
      <div class="two-fields"><label>Verification<select name="verificationStatus"><option value="from_my_notes" ${node.verificationStatus==='from_my_notes'?'selected':''}>From My Notes</option><option value="needs_verification" ${node.verificationStatus==='needs_verification'?'selected':''}>Needs Verification</option><option value="user_approved" ${node.verificationStatus==='user_approved'?'selected':''}>User Approved</option><option value="curio_suggested" ${node.verificationStatus==='curio_suggested'?'selected':''}>Curio Suggested</option><option value="rejected" ${node.verificationStatus==='rejected'?'selected':''}>Rejected</option></select></label><label>Difficulty<select name="difficulty"><option value="">Not set</option>${['easy','medium','hard'].map(value=>`<option value="${value}" ${value===node.difficulty?'selected':''}>${value}</option>`).join('')}</select></label></div>
      <label>Keywords<input name="keywords" value="${esc(node.keywords.join(', '))}" placeholder="Comma-separated"></label><label>SSC relevance<input name="sscRelevance" value="${esc(node.sscRelevance)}"></label>
      <label class="toggle-row"><span>Include in next phase</span><input type="checkbox" name="includeInNextPhase" ${node.includeInNextPhase?'checked':''}></label>
      <label>Merge with<select name="mergeTarget"><option value="">Choose same-type item</option>${data.nodes.filter(item=>item.id!==node.id&&item.nodeType===node.nodeType&&item.status!=='rejected').map(item=>`<option value="${item.id}">${esc(item.title)}</option>`).join('')}</select></label>
      <fieldset><legend>Source references</legend><div class="source-reference-list">${sources().length?sources().map(source=>`<label><input type="checkbox" name="sourceIds" value="${source.id}" ${node.sourceReferences.some(ref=>ref.sourceId===source.id)?'checked':''}><span>${esc(source.title)}${source.primary?' · Primary':''}</span></label>`).join(''):'<p>No project sources are available.</p>'}</div></fieldset>
      <div class="editor-actions"><button type="submit" class="primary">Save Changes</button><button type="button" class="primary" data-accept>Accept</button><button type="button" class="secondary" data-add-child>Split / Add child</button><button type="button" class="secondary" data-duplicate>Duplicate</button><button type="button" class="secondary" data-merge>Merge</button><button type="button" class="secondary" data-regenerate>Regenerate item</button><button type="button" class="secondary" data-up>↑ Earlier</button><button type="button" class="secondary" data-down>↓ Later</button><button type="button" class="danger" data-reject>Reject</button><button type="button" class="danger" data-delete>Delete</button></div>
    </form>`;
  }
  function renderReview(){
    const data=structure(),node=data.nodes.find(item=>item.id===state.selectedId);
    if(state.tab==='metadata'){
      $('#reviewContent').innerHTML=`<form class="metadata-form" id="metadataForm"><label>Metadata type<select id="metadataType">${['keyword','important date','definition','person','place','event','SSC keyword','comparison','map mentioned','diagram mentioned','difficult concept','revision point','missing information'].map(type=>`<option>${type}</option>`).join('')}</select></label><label>Value<input id="metadataValue" required placeholder="Structured value only"></label><button class="secondary">＋ Add metadata</button></form><div class="metadata-list">${data.metadata.length?data.metadata.map(item=>`<article class="metadata-card" data-meta="${item.id}"><select data-meta-type><option>${esc(item.type)}</option>${['keyword','important date','definition','person','place','event','SSC keyword','comparison','map mentioned','diagram mentioned','difficult concept','revision point','missing information'].filter(type=>type!==item.type).map(type=>`<option>${type}</option>`).join('')}</select><input data-meta-value value="${esc(item.value)}"><select data-meta-node><option value="">Unassigned</option>${data.nodes.filter(n=>n.status!=='rejected').map(n=>`<option value="${n.id}" ${n.id===item.relatedNodeId?'selected':''}>${esc(n.title)}</option>`).join('')}</select><small>${item.verificationStatus.replaceAll('_',' ')}</small></article>`).join(''):'<div class="review-empty">No metadata has been extracted or added. Nothing is fabricated.</div>'}</div>`;
    } else if(state.tab==='verification'){
      const warnings=[...data.warnings,...data.suggestions];$('#reviewContent').innerHTML=warnings.length?warnings.map(item=>`<article class="metadata-card"><b>${esc(item.kind.replaceAll('_',' '))}</b><p>${esc(item.message)}</p><small>${item.status}</small></article>`).join(''):'<div class="review-empty"><b>No provider findings</b><p>Conflict detection and smart suggestions are ready to receive validated provider results. No fake warnings are shown.</p></div>';
    } else {
      const refs=node?.sourceReferences||[];$('#reviewContent').innerHTML=refs.length?refs.map(ref=>{const source=sources().find(item=>item.id===ref.sourceId);return source?`<article class="source-card-mini"><h3>${esc(source.title)}</h3><p>${source.kind} · ${source.primary?'Primary source':'Supporting source'}</p><button data-view-source="${source.id}">View Source</button></article>`:'';}).join(''):'<div class="review-empty">Select source references in the node editor to preserve traceability.</div>';
    }
  }
  function render(){const current=project();if(!current){document.body.innerHTML='<main class="missing-project"><h1>Project not found</h1><a href="index.html">Return to Studio</a></main>';return;}$('#projectName').textContent=current.title;$('#backMaterials').href=`upload.html?project=${encodeURIComponent(state.projectId)}`;const data=structure();$('#analysisStatus').textContent=data.approvalStatus==='approved'?'Approved structure':'Manual review';renderTree();renderEditor();renderReview();}
  function openNodeDialog(parentId){
    const data=structure(),parent=parentId?data.nodes.find(item=>item.id===parentId):null;const allowed=service.ALLOWED[parent?.nodeType||'root']||[];
    if(!allowed.length)return toast('This item cannot contain child nodes.',true);$('#newNodeType').innerHTML=allowed.map(type=>`<option value="${type}">${labels[type]}</option>`).join('');$('#newNodeParent').innerHTML=parentOptions();$('#newNodeParent').value=parentId||'';$('#newNodeTitle').value='';$('#nodeDialog').showModal();setTimeout(()=>$('#newNodeTitle').focus(),40);
  }
  function applyEditor(){
    const form=$('#editorForm');if(!form)return;const data=new FormData(form),node=structure().nodes.find(item=>item.id===state.selectedId);
    const titleInput=form.elements.title,titleError=form.querySelector('#titleValidation'),title=String(data.get('title')||'').trim();
    if(!title){titleInput.setAttribute('aria-invalid','true');titleError.hidden=false;titleInput.focus();return;}
    titleInput.removeAttribute('aria-invalid');titleError.hidden=true;
    try{const parentId=data.get('parentId')||undefined;if(parentId!==node.parentId)service.moveNode(state.projectId,node.id,parentId);service.updateNode(state.projectId,node.id,{title,nodeType:data.get('nodeType'),description:data.get('description'),creatorNotes:data.get('creatorNotes'),verificationStatus:data.get('verificationStatus'),status:data.get('verificationStatus')==='rejected'?'rejected':data.get('verificationStatus')==='user_approved'?'accepted':data.get('verificationStatus')==='needs_verification'?'needs_verification':'draft',difficulty:data.get('difficulty')||undefined,keywords:String(data.get('keywords')||'').split(',').map(x=>x.trim()).filter(Boolean),sscRelevance:data.get('sscRelevance'),includeInNextPhase:data.has('includeInNextPhase'),sourceReferences:data.getAll('sourceIds').map(sourceId=>({sourceId}))});saved();render();}catch(error){$('#saveState').className='save-state error';$('#saveState').textContent='Save failed';toast(error.message,true);renderEditor();}
  }
  $('#nodeForm').addEventListener('submit',event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();try{const result=service.addNode(state.projectId,{parentId:$('#newNodeParent').value||undefined,nodeType:$('#newNodeType').value,title:$('#newNodeTitle').value});state.selectedId=result.nodes[result.nodes.length-1].id;$('#nodeDialog').close();saved();render();}catch(error){toast(error.message,true);}});
  $('#addRoot').addEventListener('click',()=>openNodeDialog());$('#structureTree').addEventListener('click',event=>{if(event.target.closest('[data-empty-add]'))return openNodeDialog();const item=event.target.closest('[data-node]');if(!item)return;if(event.target.closest('[data-collapse]')){state.collapsed.has(item.dataset.node)?state.collapsed.delete(item.dataset.node):state.collapsed.add(item.dataset.node);}else state.selectedId=item.dataset.node;render();});
  $('#structureTree').addEventListener('keydown',event=>{if(event.target.matches('[data-node]')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();state.selectedId=event.target.dataset.node;render();}});
  $('#nodeEditor').addEventListener('submit',event=>{if(event.target.id!=='editorForm')return;event.preventDefault();applyEditor();});
  $('#nodeEditor').addEventListener('input',event=>{if(event.target.name!=='title')return;const error=$('#titleValidation');if(event.target.value.trim()){event.target.removeAttribute('aria-invalid');if(error)error.hidden=true;}});
  $('#nodeEditor').addEventListener('focusout',event=>{if(event.target.name!=='title'||event.target.value.trim())return;event.target.setAttribute('aria-invalid','true');const error=$('#titleValidation');if(error)error.hidden=false;});
  $('#nodeEditor').addEventListener('change',event=>{if(event.target.closest('#editorForm')&&event.target.name!=='title')applyEditor();});
  $('#nodeEditor').addEventListener('click',async event=>{const node=structure().nodes.find(item=>item.id===state.selectedId);if(!node)return;if(event.target.closest('[data-accept]')){service.updateNode(state.projectId,node.id,{status:'accepted',verificationStatus:'user_approved'});saved();render();}else if(event.target.closest('[data-reject]')){service.reject(state.projectId,node.id);saved();render();}else if(event.target.closest('[data-add-child]'))openNodeDialog(node.id);else if(event.target.closest('[data-duplicate]')){const result=service.duplicate(state.projectId,node.id);state.selectedId=result.nodes[result.nodes.length-1].id;saved();render();}else if(event.target.closest('[data-merge]')){const target=$('#editorForm [name="mergeTarget"]').value;if(!target)return toast('Choose a same-type item to merge with.',true);service.merge(state.projectId,node.id,target);state.selectedId=target;saved();render();}else if(event.target.closest('[data-up]')){service.reorder(state.projectId,node.id,-1);saved();render();}else if(event.target.closest('[data-down]')){service.reorder(state.projectId,node.id,1);saved();render();}else if(event.target.closest('[data-delete]')){state.deleteId=node.id;$('#confirmDelete').showModal();}else if(event.target.closest('[data-regenerate]')){try{await window.TeachCurioAI.provider.extractLessonStructure({projectId:state.projectId,nodeId:node.id,mode:'regenerate_single_node'});}catch(error){toast(error.name==='StudioAiUnavailableError'?'AI regeneration is not connected yet.':error.message,true);}}});
  $('#confirmDelete').addEventListener('close',()=>{if($('#confirmDelete').returnValue!=='delete')return;service.remove(state.projectId,state.deleteId);state.selectedId=null;saved();render();});
  document.querySelectorAll('.review-tabs button').forEach(button=>button.addEventListener('click',()=>{state.tab=button.dataset.tab;document.querySelectorAll('.review-tabs button').forEach(item=>item.classList.toggle('active',item===button));renderReview();}));
  $('#reviewContent').addEventListener('submit',event=>{if(event.target.id!=='metadataForm')return;event.preventDefault();if(!$('#metadataValue').value.trim())return;service.addMetadata(state.projectId,{type:$('#metadataType').value,value:$('#metadataValue').value,relatedNodeId:state.selectedId});saved();renderReview();});
  $('#reviewContent').addEventListener('change',event=>{const card=event.target.closest('[data-meta]');if(!card)return;service.updateMetadata(state.projectId,card.dataset.meta,{type:card.querySelector('[data-meta-type]').value,value:card.querySelector('[data-meta-value]').value,relatedNodeId:card.querySelector('[data-meta-node]').value||undefined});saved();});
  $('#reviewContent').addEventListener('click',event=>{const button=event.target.closest('[data-view-source]');if(!button)return;const source=sources().find(item=>item.id===button.dataset.viewSource);$('#sourceDetails').innerHTML=`<h2>${esc(source.title)}</h2><p>${source.kind} · Added ${new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(source.createdAt))}${source.primary?' · Primary Source':''}</p><p>${esc(source.creatorNotes)||'No source notes.'}</p>${source.textContent?`<pre class="source-original">${esc(source.textContent)}</pre>`:'<div class="review-empty">Exact excerpt mapping is unavailable. This reference points to the original source file metadata without inventing a quotation.</div>'}`;$('#sourceDialog').showModal();});
  $('#structureSearch').addEventListener('input',event=>{state.query=event.target.value.trim().toLowerCase();renderTree();});$('#structureFilter').addEventListener('change',event=>{state.filter=event.target.value;renderTree();});
  $('#approveButton').addEventListener('click',()=>{const check=service.validate(state.projectId),counts={subjects:check.included.filter(n=>n.nodeType==='subject').length,chapters:check.included.filter(n=>n.nodeType==='chapter').length,topics:check.included.filter(n=>n.nodeType==='topic').length,concepts:check.included.filter(n=>n.nodeType==='concept').length,excluded:structure().nodes.filter(n=>!n.includeInNextPhase||n.status==='rejected').length};$('#approvalSummary').innerHTML=`<div class="approval-stats"><span><b>${counts.subjects}</b><br>Subjects</span><span><b>${counts.chapters}</b><br>Chapters</span><span><b>${counts.topics}</b><br>Topics</span><span><b>${counts.concepts}</b><br>Concepts</span><span><b>${counts.excluded}</b><br>Excluded</span><span><b>${structure().warnings.filter(w=>w.status==='open').length}</b><br>Warnings</span></div>${check.errors.length?`<div class="approval-errors">${check.errors.map(esc).join('<br>')}</div>`:'<p>Approval creates a protected StructureVersion. It will not generate lesson content.</p>'}`;$('#confirmApproval').disabled=!check.valid;$('#approvalDialog').showModal();});
  $('#confirmApproval').addEventListener('click',()=>{try{service.approve(state.projectId,session.id);$('#approvalDialog').close();saved();render();toast('Structure approved. Phase 3B was not started.');}catch(error){toast(error.message,true);}});$('#cancelApproval').addEventListener('click',()=>$('#approvalDialog').close());$('#closeApproval').addEventListener('click',()=>$('#approvalDialog').close());
  $('#versionsButton').addEventListener('click',()=>{const versions=structure().versions;$('#versionList').innerHTML=versions.length?versions.slice().reverse().map(version=>`<article class="version-card"><div><h3>Version ${version.version} · ${version.kind}</h3><p>${version.nodes.length} items · ${new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(version.createdAt))}</p></div><button class="secondary" data-restore="${version.id}">Restore draft</button></article>`).join(''):'<div class="review-empty">No approved versions yet. Draft edits are already saved.</div>';$('#versionDialog').showModal();});
  $('#versionList').addEventListener('click',event=>{const button=event.target.closest('[data-restore]');if(!button)return;service.restore(state.projectId,button.dataset.restore);state.selectedId=null;$('#versionDialog').close();saved();render();toast('Version restored as a new draft.');});$('#closeVersions').addEventListener('click',()=>$('#versionDialog').close());$('#closeSource').addEventListener('click',()=>$('#sourceDialog').close());
  $('#saveDraft').addEventListener('click',()=>{try{store.updateProject(state.projectId,{});saved();toast('Structure draft saved.');}catch(error){toast(error.message,true);}});
  $('#generateLesson').addEventListener('click',()=>{const data=structure();if(data.approvalStatus!=='approved'||!data.approvedVersionId)return toast('Approve the structure before generating a lesson.',true);window.location.href=`lesson.html?project=${encodeURIComponent(state.projectId)}`;});
  if(!state.projectId||!project()){document.body.innerHTML='<main class="missing-project"><h1>Choose a project first</h1><a href="index.html">Return to Studio</a></main>';return;}render();
})();
