(function(){
  const A=RupaiAuth,S=RupaiSync,$=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),session=A.readSession();
  if(!session)return;
  const userId=session.userId;
  let device=S.listDevices(userId).find(x=>x.current)||S.registerDevice(userId,{label:'This browser'}),view='overview';
  function toast(text){const e=$('#syncToast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
  function download(name,text){const b=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
  function overview(){const st=S.status(userId,device.id),store=S._read(),storage=S.storageSummary(userId),health=store.settings.provider==='local-device'?'Cloud persistence is not configured.':'Provider status must be checked before synchronization.';$('#syncContent').innerHTML=`<div class="sync-grid"><article class="sync-card"><h2>Cloud status</h2><span class="state">${esc(st.state.replaceAll('_',' '))}</span><p>${esc(st.message)}</p><small>${esc(health)}</small></article><article class="sync-card"><h2>Pending changes</h2><div class="metric">${st.pending}</div><p>${st.pending?'Saved locally and waiting for a confirmed provider.':'No pending changes.'}</p></article><article class="sync-card"><h2>Conflicts</h2><div class="metric">${st.conflicts}</div><button class="secondary" data-open="conflicts">Review conflicts</button></article><article class="sync-card"><h2>Storage</h2><div class="metric">${Math.ceil(storage.estimatedLocalBytes/1024)} KB</div><p>${storage.recordCount} records · ${storage.binaryCount} binary references</p><small>${esc(storage.quotaMessage)}</small></article></div><section class="sync-card warning"><h2>Local-first protection</h2><p>A successful local save is not cloud synchronization. “Synced across your devices” appears only after a real remote provider confirms each write.</p><div class="actions"><button class="primary" id="syncNow">Sync now</button><button class="secondary" id="ingest">Prepare existing learning data</button><button class="secondary" id="pause">Pause sync</button></div></section>`;$('#syncNow').onclick=run;$('#ingest').onclick=()=>{const r=S.ingestStudioData(userId,device.id);toast(`${r.ingested} learning records prepared for sync.`);render()};$('#pause').onclick=()=>{S.pause(userId);toast('Sync paused.');render()};$('[data-open]').onclick=()=>{view='conflicts';render()}}
  function queue(){const s=S._read(),items=s.queue.filter(x=>x.userId===userId&&!['confirmed','cancelled'].includes(x.status));$('#syncContent').innerHTML=`<section class="sync-card"><h2>Pending synchronization queue</h2><p>These changes survive refresh and remain on this device until confirmed.</p><div class="actions"><button class="primary" id="retry">Retry eligible</button><button class="secondary" id="exportPending">Export pending changes</button></div>${items.map(x=>`<article class="queue-item"><div><strong>${esc(x.entityType)} · ${esc(x.recordId)}</strong><small>${esc(x.operation)} · retry ${x.retryCount} · ${esc(x.errorState||'waiting')}</small></div><span class="state">${esc(x.status.replaceAll('_',' '))}</span></article>`).join('')||'<p>No pending changes.</p>'}</section>`;$('#retry').onclick=()=>{toast(`${S.retryFailed(userId)} items ready to retry.`);render()};$('#exportPending').onclick=()=>download('rupai-pending-sync.json',S.exportPending(userId))}
  function conflicts(){const list=S.listConflicts(userId);$('#syncContent').innerHTML=`<section class="sync-card"><h2>Conflict review</h2><p>Meaningful differences are never silently overwritten.</p>${list.map(c=>`<article class="conflict" data-conflict="${c.id}"><div><strong>${esc(c.entityType)} · ${esc(c.recordId)}</strong><small>${esc(c.conflictType)} · ${esc(c.recommendedResolution)}</small></div><button class="secondary">Review</button></article>`).join('')||'<p>No open conflicts.</p>'}</section>`;document.querySelectorAll('[data-conflict] button').forEach(b=>b.onclick=()=>review(list.find(x=>x.id===b.closest('[data-conflict]').dataset.conflict)))}
  function review(c){$('#syncContent').innerHTML=`<section class="sync-card"><h2>Review ${esc(c.entityType)}</h2><p>${esc(c.recommendedResolution)}</p><div class="diff"><div><h3>This device</h3><pre>${esc(JSON.stringify(c.localVersion.data,null,2))}</pre></div><div><h3>Cloud version</h3><pre>${esc(JSON.stringify(c.remoteVersion.data,null,2))}</pre></div></div><div class="actions"><button data-resolution="keep_local">Keep Local</button><button data-resolution="keep_cloud">Keep Cloud</button><button data-resolution="merge">Merge</button><button data-resolution="keep_both">Keep Both</button><button data-resolution="restore_deleted">Restore Deleted</button><button data-resolution="confirm_deletion">Confirm Deletion</button><button data-resolution="postpone">Postpone</button><button id="exportBoth">Export Both Versions</button></div></section>`;document.querySelectorAll('[data-resolution]').forEach(b=>b.onclick=()=>{try{S.resolveConflict(userId,c.id,b.dataset.resolution,userId);toast('Conflict resolution saved locally.');view='conflicts';render()}catch(e){toast(e.message)}});$('#exportBoth').onclick=()=>download(`${c.recordId}-conflict.json`,JSON.stringify({local:c.localVersion,remote:c.remoteVersion},null,2))}
  function devices(){const list=S.listDevices(userId);$('#syncContent').innerHTML=`<section class="sync-card"><h2>Registered devices</h2><p>Device labels are user-controlled; sensitive fingerprinting is not collected.</p>${list.map(d=>`<article class="device" data-device="${d.id}"><div><strong>${esc(d.label)} ${d.current?'(Current)':''}</strong><small>${esc(d.type)} · last seen ${new Date(d.lastSeenAt).toLocaleString()} · ${esc(d.sessionStatus)}</small></div><div><button data-rename>Rename</button>${d.current?'':'<button data-revoke class="danger">Revoke</button>'}</div></article>`).join('')}</section>`;document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{const row=b.closest('[data-device]'),label=prompt('Device name');if(label){S.renameDevice(userId,row.dataset.device,label);render()}});document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>{if(confirm('Revoke this device and pause its pending changes?')){S.revokeDevice(userId,b.closest('[data-device]').dataset.device);render()}})}
  function recovery(){const s=S._read(),snaps=s.snapshots.filter(x=>x.userId===userId);$('#syncContent').innerHTML=`<div class="sync-grid"><section class="sync-card"><h2>Local backup</h2><p>Export a structured local backup with an integrity checksum.</p><button class="primary" id="backup">Export local backup</button></section><section class="sync-card"><h2>Recovery snapshot</h2><button class="secondary" id="snapshot">Create snapshot</button><p>${snaps.length} snapshots available.</p></section><section class="sync-card"><h2>Server jobs</h2><button id="exportJob">Request server export</button><button id="deleteJob">Request server deletion</button><p>Unavailable until a cloud provider is configured.</p></section></div><section class="sync-card danger-card"><h2>Reset sync metadata</h2><p>Records remain local, but cursors, queue and conflict metadata are cleared.</p><button class="danger" id="reset">Reset after confirmation</button></section>`;$('#backup').onclick=()=>download('rupai-local-backup.json',S.exportBackup(userId));$('#snapshot').onclick=()=>{S.createSnapshot(userId,'user_recovery');toast('Recovery snapshot created.');render()};$('#exportJob').onclick=()=>toast(S.createExportJob(userId).message);$('#deleteJob').onclick=()=>toast(S.createDeletionJob(userId).message);$('#reset').onclick=()=>{if(confirm('Reset synchronization metadata? Local records will remain.')){S.resetSyncMetadata(userId,true);toast('Sync metadata reset.');render()}}}
  async function run(){const result=await S.runSync({userId,deviceId:device.id,authenticated:true});toast(result.message||`Sync state: ${result.state.replaceAll('_',' ')}`);render()}
  function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({overview,queue,conflicts,devices,recovery})[view]();$('#offlineBanner').hidden=navigator.onLine!==false}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});window.addEventListener('online',render);window.addEventListener('offline',render);render();
})();
