export type SyncState='local_only'|'pending_upload'|'uploading'|'synced'|'downloading'|'conflict'|'retry_scheduled'|'offline'|'provider_unavailable'|'authentication_required'|'permission_denied'|'failed'|'paused';
export type SyncOperation='create'|'update'|'delete'|'restore'|'batch_event';
export type ConflictType='field_conflict'|'delete_vs_update'|'duplicate_event'|'duplicate_submission'|'ordering_conflict'|'profile_preference_conflict'|'mastery_conflict'|'learning_history_conflict'|'ownership_conflict'|'unsupported_schema';
export interface SyncableRecord<T=unknown>{key:string;recordId:string;userId:string;ownerId:string;entityType:string;accessScope:'private'|'creator'|'published'|'classroom'|'linked';permittedReaders:string[];permittedEditors:string[];organizationId:string|null;classroomId:string|null;localVersion:number;serverVersion:number|null;baseServerVersion:number|null;createdAt:string;updatedAt:string;lastSyncedAt:string|null;lastModifiedDeviceId:string;syncStatus:SyncState;deleted:boolean;deletionTimestamp:string|null;serverDeletionConfirmed:boolean;retentionUntil:string|null;restoreEligible:boolean;revisionToken:string|null;changeHash:string|null;schemaVersion:number;data:T}
export interface PendingSyncItem{ id:string;userId:string;deviceId:string;entityType:string;recordId:string;operation:SyncOperation;localVersion:number;payload:unknown;changedFields:string[];createdAt:string;updatedAt:string;retryCount:number;lastAttemptAt:string|null;nextRetryAt:string|null;errorState:string|null;errorClassification:string|null;dependencyIds:string[];priority:string;idempotencyKey:string;status:string}
export interface SyncChange{ id:string;entityType:string;recordId:string;operation:SyncOperation;beforeVersion:number;afterVersion:number;changedFields:string[];deviceId:string;userId:string;timestamp:string;syncState:SyncState;idempotencyKey:string}
export interface SyncConflict{ id:string;userId:string;entityType:string;recordId:string;localVersion:SyncableRecord;remoteVersion:SyncableRecord;baseVersion:unknown;conflictType:ConflictType;detectedAt:string;resolutionStatus:'open'|'resolved'|'postponed';resolutionStrategy:string|null;resolvedAt:string|null;resolvedBy:string|null;recommendedResolution:string}
export interface RegisteredDevice{ id:string;userId:string;label:string;type:string;createdAt:string;lastSeenAt:string;lastSuccessfulSync:string|null;appVersion:string;schemaVersion:number;sessionStatus:'active'|'revoked'|'expired';revokedAt:string|null;current:boolean}
export interface SyncCursor{ id:string;userId:string;domain:string;cursor:string|null;serverRevisionToken:string|null;updatedAt:string}
export interface BinaryObjectMetadata{ id:string;userId:string;ownerId:string;objectKey:string;fileVersion:number;contentType:string;size:number;checksum:string|null;accessPolicy:string;uploadState:SyncState;serverConfirmed:boolean;localCacheReference:string|null;createdAt:string;updatedAt:string}
export interface PersistenceProvider{ name:string;remote:boolean;configured:boolean;readRecord(input:unknown):Promise<unknown>;readCollection(input:unknown):Promise<unknown[]>;createRecord(input:unknown):Promise<unknown>;updateRecord(input:unknown):Promise<unknown>;deleteRecord(input:unknown):Promise<unknown>;batchWrite(items:unknown[]):Promise<unknown[]>;beginTransaction():Promise<unknown>;commitTransaction(input?:unknown):Promise<unknown>;rollbackTransaction(input?:unknown):Promise<unknown>;confirmWriteVersion(input?:unknown):Promise<unknown>;health():Promise<{available:boolean;remote:boolean;serverConfirmed:boolean;message?:string}>;serverTime():Promise<{confirmed:boolean;time:string|null}>;uploadChanges(items:PendingSyncItem[],context:unknown):Promise<{results:unknown[]}>;readChangesSince(cursor:string|null,context:unknown):Promise<{changes:SyncableRecord[];cursor:string|null;serverConfirmed:boolean;revisionToken?:string}>;exportUserData?(userId:string):Promise<unknown>;requestDeletionJob?(userId:string):Promise<unknown>}
