(function () {
  'use strict';
  const KEY='rupaiSync:v1', STUDIO_KEY='teachCurioStudio:v1', SCHEMA_VERSION=1, APP_VERSION='5B';
  const SYNC_DOMAINS=new Set(['user_profile','student_learning_profile','student_knowledge_profile','concept_memory','mastery','weak_topic','study_goal','learning_session','quiz_attempt','attempt_answer','revision_plan','revision_recommendation','learning_history','memory_event','curio_decision','progress_event','accessibility_preferences','language_preferences','guest_migration']);
  const APPEND_ONLY=new Set(['memory_event','learning_history','progress_event']);
  const CREATOR_DOMAINS=new Set(['lesson_draft','lesson_version','visual_asset','quiz_draft','curio_rule','teaching_plan','review_record']);
  const STATES=['local_only','pending_upload','uploading','synced','downloading','conflict','retry_scheduled','offline','provider_unavailable','authentication_required','permission_denied','failed','paused'];
  const now=()=>new Date().toISOString(), uid=p=>`${p}_${crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)}`, clone=v=>JSON.parse(JSON.stringify(v));
  const empty=()=>({schemaVersion:SCHEMA_VERSION,appVersion:APP_VERSION,settings:{mode:'local-first',syncEnabled:false,provider:'local-device',offlineMode:'auto',retryLimit:5,batchSize:50,conflictStrategy:'review',loggingLevel:'safe',retention:{deletedDays:30,auditDays:180,exportDays:7}},devices:[],records:[],queue:[],changes:[],conflicts:[],cursors:[],audit:[],migrations:[],snapshots:[],exportJobs:[],deletionJobs:[],binaryObjects:[],storageReports:[]});
  function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');if(v?.schemaVersion===SCHEMA_VERSION)return{...empty(),...v};}catch{}return empty()}
  function write(state){localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent?.(new CustomEvent('rupai:sync-changed',{detail:clone(state)}));return state}
  function hash(value){const text=JSON.stringify(value),seed=[...text].reduce((n,c)=>((n<<5)-n+c.charCodeAt(0))|0,0);return `local-${Math.abs(seed).toString(36)}-${text.length}`}
  function audit(state,userId,deviceId,action,result='success',meta={}){const safe={};['entityType','recordId','provider','count','reason','conflictId','migrationId','jobId'].forEach(k=>{if(meta[k]!=null)safe[k]=String(meta[k]).slice(0,160)});state.audit.unshift({id:uid('sync_audit'),userId:userId||null,deviceId:deviceId||null,action,result,metadata:safe,createdAt:now()});state.audit=state.audit.slice(0,3000)}
  function providerError(code,message,classification='unknown'){const e=new Error(message);e.code=code;e.classification=classification;return e}
  const localDeviceProvider={
    name:'local-device',remote:false,configured:true,
    async readRecord(input){return getRecord(input.userId,input.entityType,input.recordId)},
    async readCollection(input){return listRecords(input.userId,input.entityType,input.options||{})},
    async createRecord(input){return putRecord(input)},async updateRecord(input){return putRecord(input)},
    async deleteRecord(input){return deleteRecord(input)},
    async batchWrite(items){return items.map(item=>item.operation==='delete'?deleteRecord(item):putRecord(item))},
    async beginTransaction(){return{available:false,id:null,message:'Atomic server transactions require a configured backend.'}},
    async commitTransaction(){return{available:false}},async rollbackTransaction(){return{available:false}},
    async confirmWriteVersion(){return{confirmed:false,serverVersion:null}},
    async health(){return{available:true,remote:false,serverConfirmed:false,message:'Local device storage is available. Cloud persistence is not configured.'}},
    async serverTime(){return{confirmed:false,time:null}},async uploadChanges(){throw providerError('provider_unavailable','No cloud persistence provider is configured.','temporary')},
    async readChangesSince(){return{changes:[],cursor:null,serverConfirmed:false}},async exportUserData(){return{available:false}},async requestDeletionJob(){return{available:false}}
  };
  const unavailable=name=>{const fail=async()=>{throw providerError('provider_unavailable',`${name} persistence is not configured.`,'temporary')};return{name,remote:true,configured:false,readRecord:fail,readCollection:fail,createRecord:fail,updateRecord:fail,deleteRecord:fail,batchWrite:fail,beginTransaction:fail,commitTransaction:fail,rollbackTransaction:fail,confirmWriteVersion:fail,async health(){return{available:false,remote:true,serverConfirmed:false,message:`${name} persistence is not configured.`}},async serverTime(){return{confirmed:false,time:null}},uploadChanges:fail,readChangesSince:fail,async exportUserData(){return{available:false}},async requestDeletionJob(){return{available:false}}}};
  const providers={'local-device':localDeviceProvider,'development-mock':{...unavailable('Development mock server'),name:'development-mock',remote:false,developmentOnly:true},supabase:unavailable('Supabase'),firebase:unavailable('Firebase'),custom:unavailable('Custom backend')};
  function registerProvider(name,provider){if(!name||!provider||typeof provider.health!=='function'||typeof provider.uploadChanges!=='function'||typeof provider.readChangesSince!=='function')throw Error('Persistence provider contract is incomplete.');providers[name]=provider;return true}
  function providerStatus(name=read().settings.provider){const p=providers[name]||unavailable(name);return p.health()}
  function configure(changes){const s=read(),allowed=['syncEnabled','provider','offlineMode','retryLimit','batchSize','conflictStrategy','loggingLevel'];allowed.forEach(k=>{if(changes[k]!==undefined)s.settings[k]=changes[k]});write(s);return clone(s.settings)}
  function registerDevice(userId,input={}){if(!userId)throw Error('Stable user ID is required.');const s=read(),currentKey=`rupaiDevice:${userId}`,stored=localStorage.getItem(currentKey);let device=stored&&s.devices.find(x=>x.id===stored&&x.userId===userId);if(!device){device={id:uid('device'),userId,label:String(input.label||'This device').slice(0,80),type:input.type||'browser',createdAt:now(),lastSeenAt:now(),lastSuccessfulSync:null,appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION,sessionStatus:'active',revokedAt:null,current:true};s.devices.filter(x=>x.userId===userId).forEach(x=>x.current=false);s.devices.push(device);localStorage.setItem(currentKey,device.id);audit(s,userId,device.id,'device_registered');}else{device.lastSeenAt=now();device.current=true;}write(s);return clone(device)}
  function listDevices(userId){return read().devices.filter(x=>x.userId===userId).map(clone)}
  function renameDevice(userId,deviceId,label){const s=read(),d=s.devices.find(x=>x.id===deviceId&&x.userId===userId);if(!d)throw Error('Device not found.');d.label=String(label||'Device').trim().slice(0,80);d.lastSeenAt=now();write(s);return clone(d)}
  function revokeDevice(userId,deviceId){const s=read(),d=s.devices.find(x=>x.id===deviceId&&x.userId===userId);if(!d)throw Error('Device not found.');d.revokedAt=now();d.sessionStatus='revoked';s.queue.filter(x=>x.deviceId===deviceId&&['pending','retry_scheduled'].includes(x.status)).forEach(x=>{x.status='paused';x.errorState='device_revoked'});audit(s,userId,deviceId,'device_revoked');write(s);return clone(d)}
  function ownership(input){return{ownerId:input.ownerId||input.userId,accessScope:input.accessScope||'private',permittedReaders:clone(input.permittedReaders||[]),permittedEditors:clone(input.permittedEditors||[]),organizationId:input.organizationId||null,classroomId:input.classroomId||null}}
  function ensureDomain(entityType){if(!SYNC_DOMAINS.has(entityType)&&!CREATOR_DOMAINS.has(entityType))throw Error(`Unsupported sync domain: ${entityType}`)}
  function recordKey(entityType,recordId){return`${entityType}:${recordId}`}
  function currentRecord(state,entityType,recordId,userId){return state.records.find(x=>x.entityType===entityType&&x.recordId===recordId&&x.userId===userId)}
  function changedFields(before,after){const keys=new Set([...Object.keys(before||{}),...Object.keys(after||{})]);return[...keys].filter(k=>JSON.stringify(before?.[k])!==JSON.stringify(after?.[k]))}
  function queueMutation(state,record,operation,beforeVersion,fields,idempotencyKey,priority='normal'){
    const existing=state.queue.find(x=>x.userId===record.userId&&x.entityType===record.entityType&&x.recordId===record.recordId&&['pending','retry_scheduled'].includes(x.status));
    const payload={data:clone(record.data),deleted:record.deleted,deletionTimestamp:record.deletionTimestamp};
    if(existing){existing.operation=existing.operation==='create'&&operation==='update'?'create':operation;existing.localVersion=record.localVersion;existing.payload=payload;existing.changedFields=[...new Set([...(existing.changedFields||[]),...fields])];existing.updatedAt=now();return existing}
    const item={id:uid('queue'),userId:record.userId,deviceId:record.lastModifiedDeviceId,entityType:record.entityType,recordId:record.recordId,operation,localVersion:record.localVersion,payload,changedFields:clone(fields),createdAt:now(),updatedAt:now(),retryCount:0,lastAttemptAt:null,nextRetryAt:null,errorState:null,errorClassification:null,dependencyIds:[],priority,idempotencyKey:idempotencyKey||uid('mutation'),status:'pending'};
    state.queue.push(item);return item
  }
  function putRecord(input){
    ensureDomain(input.entityType);if(!input.userId||!input.recordId||!input.deviceId)throw Error('User, record and device IDs are required.');
    const s=read(),device=s.devices.find(x=>x.id===input.deviceId&&x.userId===input.userId&&x.sessionStatus==='active');if(!device)throw Error('An active registered device is required.');
    let rec=currentRecord(s,input.entityType,input.recordId,input.userId);const before=rec?clone(rec.data):{},created=!rec,stamp=now();
    if(!rec){rec={key:recordKey(input.entityType,input.recordId),recordId:input.recordId,userId:input.userId,entityType:input.entityType,localVersion:0,serverVersion:null,baseServerVersion:null,createdAt:stamp,updatedAt:stamp,lastSyncedAt:null,lastModifiedDeviceId:input.deviceId,syncStatus:'local_only',deleted:false,deletionTimestamp:null,serverDeletionConfirmed:false,retentionUntil:null,restoreEligible:true,revisionToken:null,changeHash:null,schemaVersion:input.schemaVersion||1,data:{},...ownership(input)};s.records.push(rec)}
    rec.data={...rec.data,...clone(input.data||{})};rec.localVersion++;rec.updatedAt=stamp;rec.lastModifiedDeviceId=input.deviceId;rec.deleted=false;rec.deletionTimestamp=null;rec.syncStatus=navigator.onLine===false?'offline':'pending_upload';rec.changeHash=hash(rec.data);
    const fields=changedFields(before,rec.data),operation=created?'create':'update',queue=queueMutation(s,rec,operation,rec.localVersion-1,fields,input.idempotencyKey,input.priority);
    s.changes.push({id:uid('change'),entityType:rec.entityType,recordId:rec.recordId,operation,beforeVersion:rec.localVersion-1,afterVersion:rec.localVersion,changedFields:fields,deviceId:input.deviceId,userId:input.userId,timestamp:stamp,syncState:rec.syncStatus,idempotencyKey:queue.idempotencyKey});
    audit(s,input.userId,input.deviceId,'local_change_saved','success',{entityType:rec.entityType,recordId:rec.recordId});write(s);return clone(rec)
  }
  function deleteRecord(input){const s=read(),rec=currentRecord(s,input.entityType,input.recordId,input.userId);if(!rec)throw Error('Record not found.');if(rec.lastModifiedDeviceId!==input.deviceId&&!s.devices.some(x=>x.id===input.deviceId&&x.userId===input.userId&&x.sessionStatus==='active'))throw Error('Active device required.');rec.localVersion++;rec.deleted=true;rec.deletionTimestamp=now();rec.deletedBy=input.userId;rec.lastModifiedDeviceId=input.deviceId;rec.syncStatus=navigator.onLine===false?'offline':'pending_upload';rec.retentionUntil=new Date(Date.now()+s.settings.retention.deletedDays*86400000).toISOString();rec.restoreEligible=true;const q=queueMutation(s,rec,'delete',rec.localVersion-1,['deleted','deletionTimestamp'],input.idempotencyKey,'high');s.changes.push({id:uid('change'),entityType:rec.entityType,recordId:rec.recordId,operation:'delete',beforeVersion:rec.localVersion-1,afterVersion:rec.localVersion,changedFields:['deleted'],deviceId:input.deviceId,userId:input.userId,timestamp:now(),syncState:rec.syncStatus,idempotencyKey:q.idempotencyKey});write(s);return clone(rec)}
  function restoreRecord(input){const s=read(),rec=currentRecord(s,input.entityType,input.recordId,input.userId);if(!rec?.deleted||!rec.restoreEligible)throw Error('Record is not eligible for restore.');rec.deleted=false;rec.deletionTimestamp=null;rec.serverDeletionConfirmed=false;write(s);return putRecord({...input,data:rec.data,idempotencyKey:input.idempotencyKey||uid('restore')})}
  function getRecord(userId,entityType,recordId){const rec=currentRecord(read(),entityType,recordId,userId);return rec&&!rec.deleted?clone(rec):null}
  function listRecords(userId,entityType,options={}){return read().records.filter(x=>x.userId===userId&&x.entityType===entityType&&(options.includeDeleted||!x.deleted)).slice(options.offset||0,(options.offset||0)+(options.limit||100)).map(clone)}
  function createSnapshot(userId,reason='manual'){const s=read(),records=s.records.filter(x=>x.userId===userId),snap={id:uid('snapshot'),userId,reason,records:clone(records),queue:clone(s.queue.filter(x=>x.userId===userId)),checksum:hash(records),schemaVersion:SCHEMA_VERSION,createdAt:now()};s.snapshots.unshift(snap);s.snapshots=s.snapshots.slice(0,20);write(s);return{...clone(snap),records:undefined,queue:undefined}}
  function restoreSnapshot(userId,snapshotId,confirmed=false){if(!confirmed)throw Error('Confirmation is required to restore a snapshot.');const s=read(),snap=s.snapshots.find(x=>x.id===snapshotId&&x.userId===userId);if(!snap||hash(snap.records)!==snap.checksum)throw Error('Recovery snapshot failed integrity validation.');s.records=s.records.filter(x=>x.userId!==userId).concat(clone(snap.records));s.queue=s.queue.filter(x=>x.userId!==userId).concat(clone(snap.queue));audit(s,userId,null,'snapshot_restored','success',{reason:snap.reason});write(s);return true}
  function classify(error){if(error.classification)return error.classification;const code=String(error.code||'');if(code.includes('auth'))return'authentication';if(code.includes('permission'))return'permission';if(code.includes('validation'))return'validation';if(code.includes('conflict'))return'conflict';if(code.includes('timeout')||code.includes('network')||code.includes('provider'))return'temporary';return'unknown'}
  function scheduleRetry(item,error,settings){item.retryCount++;item.lastAttemptAt=now();item.errorState=String(error.code||'unknown').slice(0,80);item.errorClassification=classify(error);if(['permission','validation','permanent'].includes(item.errorClassification)||item.retryCount>=settings.retryLimit){item.status='failed';item.nextRetryAt=null}else{item.status='retry_scheduled';item.nextRetryAt=new Date(Date.now()+Math.min(3600000,30000*(2**(item.retryCount-1)))).toISOString()}}
  function conflict(state,local,remote,type,baseVersion){const existing=state.conflicts.find(x=>x.userId===local.userId&&x.entityType===local.entityType&&x.recordId===local.recordId&&x.resolutionStatus==='open');if(existing)return existing;const c={id:uid('conflict'),userId:local.userId,entityType:local.entityType,recordId:local.recordId,localVersion:clone(local),remoteVersion:clone(remote),baseVersion:baseVersion||null,conflictType:type,detectedAt:now(),resolutionStatus:'open',resolutionStrategy:null,resolvedAt:null,resolvedBy:null,recommendedResolution:recommend(type,local.entityType)};state.conflicts.push(c);local.syncStatus='conflict';audit(state,local.userId,local.lastModifiedDeviceId,'conflict_detected','warning',{entityType:local.entityType,recordId:local.recordId,conflictId:c.id});return c}
  function recommend(type,entity){if(APPEND_ONLY.has(entity))return'Merge unique events by ID and idempotency key.';if(entity==='quiz_attempt')return'Keep both distinct attempts; deduplicate only matching submission keys.';if(entity==='mastery')return'Merge evidence and recalculate mastery.';if(type==='delete_vs_update')return'Review deletion intent before choosing.';return'Review field-level differences.'}
  function mergeDifferentFields(local,remote,base){const original=base?.data||{},l=changedFields(original,local.data||{}),r=changedFields(original,remote.data||{}),overlap=l.filter(x=>r.includes(x));if(overlap.length)return null;const merged={...original};r.forEach(k=>merged[k]=clone(remote.data[k]));l.forEach(k=>merged[k]=clone(local.data[k]));return merged}
  function dedupeEvents(local,remote){const items=[...(remote.data?.events||[remote.data]),...(local.data?.events||[local.data])],seen=new Set();return{events:items.filter(x=>{const k=x.idempotencyKey||x.id;if(!k||seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>String(a.serverTimestamp||a.createdAt).localeCompare(String(b.serverTimestamp||b.createdAt)))}}
  function streakFromEvents(events){const days=[...new Set(events.map(x=>x.serverTimestamp||x.createdAt).filter(Boolean).map(x=>String(x).slice(0,10)))].sort();let longest=0,run=0,previous=null;days.forEach(day=>{const stamp=+new Date(day);run=previous!=null&&Math.round((stamp-previous)/86400000)===1?run+1:1;longest=Math.max(longest,run);previous=stamp});return{activityDays:days.length,longest}}
  function mergeLearning(entity,local,remote,base){
    if(APPEND_ONLY.has(entity)){const data=dedupeEvents(local,remote);if(entity==='learning_history')data.recalculatedStreak=streakFromEvents(data.events);return{strategy:'append_unique',data}}
    if(entity==='quiz_attempt'){if(local.data?.idempotencyKey&&local.data.idempotencyKey===remote.data?.idempotencyKey)return{strategy:'deduplicate_submission',data:remote.data};return{strategy:'keep_both',data:null,keepBoth:true}}
    if(entity==='mastery'){const evidence=[...(remote.data?.evidence||[]),...(local.data?.evidence||[])],seen=new Set(),unique=evidence.filter(x=>{const k=x.id||x.idempotencyKey||hash(x);if(seen.has(k))return false;seen.add(k);return true}),score=unique.length?Math.round(unique.reduce((n,x)=>n+Number(x.score||0),0)/unique.length):0;return{strategy:'recalculate_from_evidence',data:{...remote.data,...local.data,evidence:unique,score,level:score>=80?'mastered':score>=60?'good':score>=40?'learning':'needs_revision'}}}
    if(entity==='revision_plan'){const done=new Set([...(remote.data?.completedIds||[]),...(local.data?.completedIds||[])]),pending=new Set([...(remote.data?.pendingIds||[]),...(local.data?.pendingIds||[])]);done.forEach(x=>pending.delete(x));return{strategy:'merge_completion',data:{...remote.data,...local.data,completedIds:[...done],pendingIds:[...pending]}}}
    if(entity==='learning_session'){if(local.data?.status==='completed'&&remote.data?.status==='completed')return{strategy:'keep_both',data:null,keepBoth:true};return{strategy:'preserve_completed',data:local.data?.status==='completed'?local.data:remote.data}}
    if(entity==='concept_memory'){const events=dedupeEvents({data:{events:local.data?.evidence||[]}},{data:{events:remote.data?.evidence||[]}}).events,last=events.map(x=>x.reviewedAt||x.createdAt).filter(Boolean).sort().at(-1)||null;return{strategy:'merge_evidence',data:{...remote.data,...local.data,evidence:events,lastReviewedAt:last}}}
    if(entity==='study_goal'||entity==='user_profile'||entity==='accessibility_preferences'||entity==='language_preferences'){const data=mergeDifferentFields(local,remote,base);return data?{strategy:'different_field_merge',data}:null}
    return null
  }
  function applyRemote(state,userId,deviceId,remote){
    if(remote.userId!==userId||remote.ownerId&&remote.ownerId!==userId&&!remote.permittedEditors?.includes(userId)){const fake={userId,entityType:remote.entityType,recordId:remote.recordId,lastModifiedDeviceId:deviceId,syncStatus:'conflict',data:{}};conflict(state,fake,remote,'ownership_conflict',null);return}
    const local=currentRecord(state,remote.entityType,remote.recordId,userId);
    if(!local){state.records.push({...clone(remote),key:recordKey(remote.entityType,remote.recordId),syncStatus:'synced',lastSyncedAt:now()});return}
    const pending=state.queue.some(x=>x.userId===userId&&x.entityType===remote.entityType&&x.recordId===remote.recordId&&['pending','retry_scheduled','uploading'].includes(x.status));
    if(!pending){Object.assign(local,clone(remote),{key:local.key,syncStatus:'synced',lastSyncedAt:now()});return}
    if(remote.deleted&&!local.deleted){conflict(state,local,remote,'delete_vs_update',local.baseServerVersion);return}
    if(local.schemaVersion>remote.schemaVersion+1||remote.schemaVersion>local.schemaVersion+1){conflict(state,local,remote,'unsupported_schema',local.baseServerVersion);return}
    const merged=mergeLearning(local.entityType,local,remote,{data:local.baseData||{}});
    if(merged?.data){local.data=merged.data;local.localVersion++;local.syncStatus='pending_upload';queueMutation(state,local,'update',local.localVersion-1,Object.keys(merged.data),uid('merge'),'high');return}
    conflict(state,local,remote,local.entityType==='quiz_attempt'?'duplicate_submission':'field_conflict',local.baseServerVersion)
  }
  async function runSync(input){
    const s=read(),userId=input.userId,deviceId=input.deviceId,device=s.devices.find(x=>x.id===deviceId&&x.userId===userId);if(!device||device.sessionStatus!=='active')throw Error('Active device required.');
    if(input.authenticated===false){audit(s,userId,deviceId,'sync_failed','failure',{reason:'authentication_required'});write(s);return{state:'authentication_required',uploaded:0,downloaded:0}}
    if(navigator.onLine===false){s.records.filter(x=>x.userId===userId&&x.syncStatus!=='synced').forEach(x=>x.syncStatus='offline');audit(s,userId,deviceId,'sync_failed','failure',{reason:'offline'});write(s);return{state:'offline',uploaded:0,downloaded:0,message:'Your changes are saved on this device and will retry later.'}}
    if(!s.settings.syncEnabled){write(s);return{state:'local_only',uploaded:0,downloaded:0,message:'Saved on this device. Cloud sync is not enabled.'}}
    const provider=providers[input.provider||s.settings.provider]||unavailable(input.provider||s.settings.provider),health=await provider.health();
    if(!health.available){audit(s,userId,deviceId,'sync_failed','failure',{provider:provider.name,reason:'provider_unavailable'});write(s);return{state:'provider_unavailable',uploaded:0,downloaded:0,message:'Your changes are saved on this device and will retry when a provider is available.'}}
    audit(s,userId,deviceId,'sync_started','success',{provider:provider.name});let uploaded=0,failed=0,downloaded=0;
    const due=s.queue.filter(x=>x.userId===userId&&['pending','retry_scheduled'].includes(x.status)&&(!x.nextRetryAt||+new Date(x.nextRetryAt)<=Date.now())).sort((a,b)=>(a.priority==='high'?-1:1)-(b.priority==='high'?-1:1)).slice(0,s.settings.batchSize);
    due.forEach(x=>x.status='uploading');write(s);
    if(due.length)try{
      const result=await provider.uploadChanges(clone(due),{userId,deviceId,cursor:s.cursors.find(x=>x.userId===userId&&x.domain==='upload')?.cursor||null});
      const latest=read();for(const item of due){const q=latest.queue.find(x=>x.id===item.id),r=(result.results||[]).find(x=>x.idempotencyKey===item.idempotencyKey);if(r?.status==='confirmed'&&r.serverConfirmed===true&&provider.remote===true){q.status='confirmed';q.confirmedAt=now();const rec=currentRecord(latest,item.entityType,item.recordId,userId);if(rec){rec.serverVersion=r.serverVersion;rec.baseServerVersion=r.serverVersion;rec.baseData=clone(rec.data);rec.revisionToken=r.revisionToken||null;rec.lastSyncedAt=r.serverTimestamp||now();rec.syncStatus='synced';if(rec.deleted)rec.serverDeletionConfirmed=true}uploaded++;audit(latest,userId,deviceId,'upload_confirmed','success',{entityType:item.entityType,recordId:item.recordId})}else{scheduleRetry(q,providerError(r?.errorCode||'unconfirmed','Server did not confirm this write.',r?.classification||'temporary'),latest.settings);failed++}}write(latest)
    }catch(error){const latest=read();due.forEach(item=>{const q=latest.queue.find(x=>x.id===item.id);if(q)scheduleRetry(q,error,latest.settings)});failed+=due.length;audit(latest,userId,deviceId,'sync_failed','failure',{provider:provider.name,reason:error.code||'upload_failed'});write(latest)}
    let latest=read();try{
      const cursor=latest.cursors.find(x=>x.userId===userId&&x.domain==='all'),remote=await provider.readChangesSince(cursor?.cursor||null,{userId,deviceId,limit:latest.settings.batchSize});
      if(remote.serverConfirmed===true&&provider.remote===true){(remote.changes||[]).forEach(change=>{applyRemote(latest,userId,deviceId,change);downloaded++});if(cursor)cursor.cursor=remote.cursor;else latest.cursors.push({id:uid('cursor'),userId,domain:'all',cursor:remote.cursor,serverRevisionToken:remote.revisionToken||null,updatedAt:now()})}
    }catch(error){audit(latest,userId,deviceId,'download_failed','failure',{provider:provider.name,reason:error.code||'download_failed'})}
    const open=latest.conflicts.filter(x=>x.userId===userId&&x.resolutionStatus==='open').length,pending=latest.queue.filter(x=>x.userId===userId&&!['confirmed','cancelled'].includes(x.status)).length;
    if(uploaded||downloaded){const latestDevice=latest.devices.find(x=>x.id===deviceId&&x.userId===userId);if(latestDevice)latestDevice.lastSuccessfulSync=now();audit(latest,userId,deviceId,'sync_completed',failed?'partial':'success',{count:uploaded+downloaded})}write(latest);
    return{state:open?'conflict':failed?'retry_scheduled':pending?'pending_upload':uploaded||downloaded?'synced':'local_only',uploaded,downloaded,failed,pending,conflicts:open,serverConfirmed:Boolean((uploaded||downloaded)&&provider.remote)}
  }
  function retryFailed(userId){const s=read();s.queue.filter(x=>x.userId===userId&&['failed','retry_scheduled'].includes(x.status)&&!['permission','validation','permanent'].includes(x.errorClassification)).forEach(x=>{x.status='pending';x.nextRetryAt=null;x.errorState=null});write(s);return s.queue.filter(x=>x.userId===userId&&x.status==='pending').length}
  function pause(userId){const s=read();s.settings.pausedUsers=s.settings.pausedUsers||[];if(!s.settings.pausedUsers.includes(userId))s.settings.pausedUsers.push(userId);s.queue.filter(x=>x.userId===userId&&x.status==='pending').forEach(x=>x.status='paused');write(s)}
  function resume(userId){const s=read();s.settings.pausedUsers=(s.settings.pausedUsers||[]).filter(x=>x!==userId);s.queue.filter(x=>x.userId===userId&&x.status==='paused'&&x.errorState!=='device_revoked').forEach(x=>x.status='pending');write(s)}
  function listConflicts(userId,status='open'){return read().conflicts.filter(x=>x.userId===userId&&(!status||x.resolutionStatus===status)).map(clone)}
  function resolveConflict(userId,conflictId,strategy,resolvedBy){
    const s=read(),c=s.conflicts.find(x=>x.id===conflictId&&x.userId===userId&&x.resolutionStatus==='open');if(!c)throw Error('Open conflict not found.');
    const local=currentRecord(s,c.entityType,c.recordId,userId),allowed=['keep_local','keep_cloud','merge','keep_both','restore_deleted','confirm_deletion','postpone'];if(!allowed.includes(strategy))throw Error('Unsupported resolution strategy.');if(strategy==='postpone')return clone(c);
    if(strategy==='keep_cloud')Object.assign(local,clone(c.remoteVersion),{key:local.key,syncStatus:'synced',lastSyncedAt:now()});
    else if(strategy==='confirm_deletion'){local.deleted=true;local.deletionTimestamp=now();local.syncStatus='pending_upload';queueMutation(s,local,'delete',local.localVersion,['deleted'],uid('resolution'),'high')}
    else if(strategy==='restore_deleted'){local.deleted=false;local.deletionTimestamp=null;local.localVersion++;queueMutation(s,local,'restore',local.localVersion-1,['deleted'],uid('resolution'),'high')}
    else if(strategy==='merge'){const merged=mergeLearning(c.entityType,c.localVersion,c.remoteVersion,c.baseVersion);if(!merged?.data)throw Error('This conflict cannot be merged automatically.');local.data=merged.data;local.localVersion++;queueMutation(s,local,'update',local.localVersion-1,Object.keys(merged.data),uid('resolution'),'high')}
    else if(strategy==='keep_both'){const copy={...clone(c.remoteVersion),recordId:`${c.recordId}_remote_${Date.now()}`,key:'',syncStatus:'pending_upload',localVersion:1,lastModifiedDeviceId:local.lastModifiedDeviceId};copy.key=recordKey(copy.entityType,copy.recordId);s.records.push(copy);queueMutation(s,copy,'create',0,Object.keys(copy.data||{}),uid('resolution'),'high')}
    else{local.syncStatus='pending_upload';queueMutation(s,local,'update',local.localVersion-1,Object.keys(local.data||{}),uid('resolution'),'high')}
    c.resolutionStatus='resolved';c.resolutionStrategy=strategy;c.resolvedAt=now();c.resolvedBy=resolvedBy||userId;audit(s,userId,local.lastModifiedDeviceId,'conflict_resolved','success',{conflictId:c.id});write(s);return clone(c)
  }
  function startMigration(userId,deviceId,mode,remoteSummary={count:0}){
    const s=read();if(s.migrations.some(x=>x.userId===userId&&x.status==='completed'))throw Error('Cloud migration has already completed.');
    const snap=createSnapshot(userId,'initial_cloud_migration'),latest=read(),localCount=latest.records.filter(x=>x.userId===userId).length,m={id:uid('sync_migration'),userId,deviceId,mode,status:'review_required',localCount,remoteCount:Number(remoteSummary.count||0),snapshotId:snap.id,conflictIds:[],createdAt:now(),completedAt:null};latest.migrations.push(m);audit(latest,userId,deviceId,'migration_started','success',{migrationId:m.id});write(latest);return clone(m)
  }
  function confirmMigration(userId,migrationId,choice){const allowed=['merge','use_local','use_cloud','review_conflicts','cancel'],s=read(),m=s.migrations.find(x=>x.id===migrationId&&x.userId===userId);if(!m||!allowed.includes(choice))throw Error('Migration or choice is invalid.');m.choice=choice;m.status=choice==='cancel'?'cancelled':choice==='review_conflicts'?'conflict_review':'pending_sync';if(choice==='use_local')s.records.filter(x=>x.userId===userId).forEach(r=>{if(!s.queue.some(q=>q.userId===userId&&q.entityType===r.entityType&&q.recordId===r.recordId))queueMutation(s,r,r.deleted?'delete':'create',0,Object.keys(r.data||{}),uid('migration'),'high')});audit(s,userId,m.deviceId,'migration_confirmed','success',{migrationId:m.id});write(s);return clone(m)}
  function completeMigration(userId,migrationId,serverConfirmed=false){const s=read(),m=s.migrations.find(x=>x.id===migrationId&&x.userId===userId);if(!m)throw Error('Migration not found.');if(!serverConfirmed)throw Error('Server confirmation is required to complete cloud migration.');m.status='completed';m.completedAt=now();audit(s,userId,m.deviceId,'migration_completed','success',{migrationId:m.id});write(s);return clone(m)}
  function status(userId,deviceId){const s=read(),pending=s.queue.filter(x=>x.userId===userId&&!['confirmed','cancelled'].includes(x.status)),conflicts=s.conflicts.filter(x=>x.userId===userId&&x.resolutionStatus==='open'),device=s.devices.find(x=>x.id===deviceId),provider=providers[s.settings.provider]||localDeviceProvider;let state='local_only';if(navigator.onLine===false)state='offline';else if(conflicts.length)state='conflict';else if(pending.some(x=>x.status==='uploading'))state='uploading';else if(pending.some(x=>x.status==='retry_scheduled'))state='retry_scheduled';else if(pending.length)state='pending_upload';else if(s.records.some(x=>x.userId===userId&&x.syncStatus==='synced'&&x.lastSyncedAt)&&provider.remote)state='synced';const messages={local_only:'Saved on this device',pending_upload:'Waiting to sync',uploading:'Uploading confirmed changes',synced:'Synced across your devices',conflict:'A conflict needs your review',retry_scheduled:'Your changes are saved on this device and will retry later',offline:'Sync paused because you are offline'};return{state,message:messages[state],lastSuccessfulSync:device?.lastSuccessfulSync||null,pending:pending.length,conflicts:conflicts.length,device:clone(device||null),provider:s.settings.provider,providerConfigured:Boolean(provider.configured),localOnly:!provider.remote}}
  function exportPending(userId){const s=read();return JSON.stringify({schema:'rupai-sync-pending/v1',exportedAt:now(),localOnly:true,userId,queue:s.queue.filter(x=>x.userId===userId&&!['confirmed','cancelled'].includes(x.status)).map(x=>({...x,payload:clone(x.payload)})),conflicts:s.conflicts.filter(x=>x.userId===userId&&x.resolutionStatus==='open')},null,2)}
  function exportBackup(userId){const s=read(),payload={schema:'rupai-local-backup/v1',backupVersion:1,userId,createdAt:now(),records:s.records.filter(x=>x.userId===userId),devices:s.devices.filter(x=>x.userId===userId),queue:s.queue.filter(x=>x.userId===userId),conflicts:s.conflicts.filter(x=>x.userId===userId),migrations:s.migrations.filter(x=>x.userId===userId).map(({snapshotId,...x})=>x)},checksum='';payload.checksum=hash(payload.records);return JSON.stringify(payload,null,2)}
  function previewBackup(text){const data=JSON.parse(text);return{valid:data.schema==='rupai-local-backup/v1'&&data.checksum===hash(data.records),userId:data.userId,recordCount:data.records?.length||0,deviceCount:data.devices?.length||0,createdAt:data.createdAt}}
  function resetSyncMetadata(userId,confirmed=false){if(!confirmed)throw Error('Confirmation is required.');const s=read();s.queue=s.queue.filter(x=>x.userId!==userId);s.conflicts=s.conflicts.filter(x=>x.userId!==userId);s.cursors=s.cursors.filter(x=>x.userId!==userId);s.records.filter(x=>x.userId===userId).forEach(x=>{x.serverVersion=null;x.baseServerVersion=null;x.lastSyncedAt=null;x.revisionToken=null;x.syncStatus='local_only'});audit(s,userId,null,'sync_metadata_reset');write(s);return true}
  function createExportJob(userId){const s=read(),job={id:uid('export_job'),userId,status:'unavailable',requestedAt:now(),readyAt:null,expiresAt:null,downloadedAt:null,provider:s.settings.provider,message:'Server-backed export jobs are unavailable until a cloud provider is configured.'};s.exportJobs.push(job);audit(s,userId,null,'export_job_unavailable','failure',{jobId:job.id});write(s);return clone(job)}
  function createDeletionJob(userId){const s=read(),job={id:uid('deletion_job'),userId,status:'unavailable',requestedAt:now(),cancelUntil:null,provider:s.settings.provider,message:'Server account deletion is unavailable until a cloud provider is configured.'};s.deletionJobs.push(job);audit(s,userId,null,'deletion_job_unavailable','failure',{jobId:job.id});write(s);return clone(job)}
  function registerBinary(input){if(!input.userId||!input.objectKey||!input.contentType||!Number.isFinite(Number(input.size)))throw Error('Binary metadata is incomplete.');const s=read(),item={id:uid('binary'),userId:input.userId,ownerId:input.userId,objectKey:input.objectKey,fileVersion:Number(input.fileVersion||1),contentType:input.contentType,size:Number(input.size),checksum:input.checksum||null,accessPolicy:input.accessPolicy||'private',uploadState:'local_only',serverConfirmed:false,localCacheReference:input.localCacheReference||null,createdAt:now(),updatedAt:now()};s.binaryObjects.push(item);write(s);return clone(item)}
  function storageSummary(userId){const s=read(),records=s.records.filter(x=>x.userId===userId),binary=s.binaryObjects.filter(x=>x.userId===userId),bytes=new Blob([JSON.stringify(records)]).size+binary.reduce((n,x)=>n+x.size,0);return{estimatedLocalBytes:bytes,recordCount:records.length,binaryCount:binary.length,cloudQuota:null,cloudUsage:null,quotaMessage:'No cloud provider quota is configured.',orphanedBinary:binary.filter(x=>!x.objectKey).length}}
  function ingestStudioData(userId,deviceId){
    let studio;try{studio=JSON.parse(localStorage.getItem(STUDIO_KEY)||'{}')}catch{return{ingested:0,error:'invalid_local_store'}}
    const map={studentLearningProfiles:'student_learning_profile',studentKnowledgeProfiles:'student_knowledge_profile',conceptMemories:'concept_memory',studentMasteries:'mastery',weakTopics:'weak_topic',studyGoals:'study_goal',curioLearningSessions:'learning_session',quizAttempts:'quiz_attempt',attemptAnswers:'attempt_answer',adaptiveRevisionPlans:'revision_plan',longTermRevisionPlans:'revision_plan',revisionRecommendations:'revision_recommendation',learningTimeline:'learning_history',memoryEvents:'memory_event',progressEvents:'progress_event',curioDecisions:'curio_decision'};let ingested=0;
    Object.entries(map).forEach(([key,type])=>(studio[key]||[]).filter(x=>x.studentId===userId||x.userId===userId||x.accountId===userId).forEach(item=>{const id=item.id||uid(type);if(!getRecord(userId,type,id)){putRecord({userId,deviceId,entityType:type,recordId:id,data:item,idempotencyKey:`ingest:${type}:${id}`});ingested++}}));return{ingested}
  }
  window.RupaiSync={SCHEMA_VERSION,APP_VERSION,STATES,SYNC_DOMAINS:[...SYNC_DOMAINS],CREATOR_DOMAINS:[...CREATOR_DOMAINS],providers,registerProvider,providerStatus,configure,registerDevice,listDevices,renameDevice,revokeDevice,putRecord,deleteRecord,restoreRecord,getRecord,listRecords,createSnapshot,restoreSnapshot,runSync,retryFailed,pause,resume,listConflicts,resolveConflict,startMigration,confirmMigration,completeMigration,status,exportPending,exportBackup,previewBackup,resetSyncMetadata,createExportJob,createDeletionJob,registerBinary,storageSummary,ingestStudioData,_read:read,_write:write,_applyRemote:applyRemote,_mergeLearning:mergeLearning};
})();
