(function(){
  if(!window.__studioSession)return;const $=s=>document.querySelector(s),store=window.TeachCurioStore,service=window.TeachCurioVisualAssets,session=window.__studioSession,params=new URLSearchParams(location.search),projectId=params.get('project'),project=store.getProject(projectId);let page=1,libraryPage=1,selected=null,objectUrls=[];
  const LABELS={illustration:'Illustration',diagram:'Diagram',infographic:'Infographic',historical_art:'Historical Art',modern_photograph:'Modern Photograph',scientific_illustration:'Scientific Illustration',character_image:'Character Image',object_image:'Object Image',landmark:'Landmark',monument:'Monument',animal:'Animal',plant:'Plant',person:'Person',artifact:'Artifact',screenshot:'Screenshot',symbol:'Symbol',icon:'Icon',miscellaneous:'Miscellaneous'},esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;};
  if(!project){document.body.innerHTML='<main><h1>Project not found</h1><a href="index.html">Return to Studio</a></main>';return;}
  function toast(text,error=false){const n=$('#toast');n.textContent=text;n.style.background=error?'#8d3348':'#41285f';n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),3200);}
  function cleanup(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];}
  async function image(asset,img){try{const url=await service.blobUrl(asset);objectUrls.push(url);img.src=url;}catch(error){img.replaceWith(Object.assign(document.createElement('p'),{className:'missing',textContent:error.message}));}}
  function card(item,library=false){const a=library?item:item.asset,r=library?null:item.reference,structured=Boolean(a.structuredVisualId);return`<article class="asset-card" data-asset="${a.id}" ${r?`data-reference="${r.id}"`:''}><div class="asset-thumb">${structured?`<div class="missing">Structured Educational Visual<br><a class="secondary" href="educational-visuals.html?project=${encodeURIComponent(projectId)}&visual=${a.structuredVisualId}">Open visual</a></div>`:`<img data-image="${a.id}" alt="${esc(a.altText)}" loading="lazy">`}</div><div class="asset-card-body"><span class="eyebrow">${esc(LABELS[a.assetType]||a.assetType)}</span><h3>${esc(a.title)}</h3><p>${esc(a.caption||a.description||'No caption')}</p><div class="asset-meta"><span>${esc(a.reviewStatus.replaceAll('_',' '))}</span>${r?`<span>${esc(r.role)}</span><span>${esc(r.placementType.replaceAll('_',' '))}</span>`:''}</div><div class="asset-actions">${library?`<button class="primary" data-reuse="${a.id}">Reuse</button>`:`${structured?'':`<button class="secondary" data-preview="${a.id}">Preview</button>`}<button class="secondary" data-duplicate="${r.id}">Duplicate</button><button class="danger" data-delete="${r.id}">Delete</button>`}</div></div></article>`;}
  async function loadImages(root,assets){for(const img of root.querySelectorAll('[data-image]')){const a=assets.find(x=>x.id===img.dataset.image);if(a)await image(a,img);}}
  async function render(){const result=service.projectAssets(projectId,page,18,{role:$('#roleFilter').value,query:$('#lessonSearch').value}),items=result.items;$('#assetCount').textContent=result.total;$('#assetGrid').innerHTML=items.length?items.map(x=>card(x)).join(''):'<section class="empty-assets"><h2>No matching visuals</h2><p>Upload an image or reuse one from the shared Asset Library.</p></section>';$('#assetPagination').innerHTML=Array.from({length:result.pages},(_,i)=>`<button class="secondary ${page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');await loadImages($('#assetGrid'),items.map(x=>x.asset));}
  function openForm(asset=null){const f=$('#assetForm');f.reset();selected=asset;f.elements.assetId.value=asset?.id||'';$('#assetDialogTitle').textContent=asset?'Edit Metadata':'Upload Image';$('#fileField').hidden=Boolean(asset);if(asset){['assetType','title','subject','chapter','description','caption','altText','source','copyrightStatus','creatorNotes','reviewStatus'].forEach(k=>{if(f.elements[k])f.elements[k].value=asset[k]||'';});f.elements.keywords.value=asset.keywords.join(', ');f.elements.tags.value=asset.tags.join(', ');}else{f.elements.assetType.value='illustration';f.elements.source.value='Creator upload';f.elements.copyrightStatus.value='Creator Owned';f.elements.subject.value=project.subject||'';f.elements.chapter.value=project.chapterHint||'';}$('#assetDialog').showModal();}
  function formData(){const f=$('#assetForm'),d=new FormData(f);return{assetType:d.get('assetType'),title:d.get('title'),subject:d.get('subject'),chapter:d.get('chapter'),description:d.get('description'),caption:d.get('caption'),altText:d.get('altText'),source:d.get('source'),copyrightStatus:d.get('copyrightStatus'),creatorNotes:d.get('creatorNotes'),keywords:d.get('keywords'),tags:d.get('tags'),placementType:d.get('placementType'),role:d.get('role'),targetId:d.get('targetId')||projectId,reviewStatus:d.get('reviewStatus'),lessonId:projectId};}
  async function preview(assetId){selected=store.read().visualAssets.find(a=>a.id===assetId);if(!selected)return;const img=$('#largePreview');img.classList.remove('zoomed');img.removeAttribute('src');img.alt=selected.altText;try{img.src=await service.blobUrl(selected);objectUrls.push(img.src);}catch(error){toast(error.message,true);}$('#previewTitle').textContent=selected.title;$('#previewCaption').textContent=selected.caption||selected.description;$('#previewMeta').innerHTML=[['Type',LABELS[selected.assetType]],['Alt text',selected.altText],['Subject',selected.subject||'—'],['Chapter',selected.chapter||'—'],['Source',selected.source],['Copyright',selected.copyrightStatus],['Version',selected.currentVersion],['Review',selected.reviewStatus.replaceAll('_',' ')]].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');$('#previewDialog').showModal();}
  async function library(){const result=service.search($('#librarySearch').value,{assetType:$('#libraryType').value},libraryPage,24);$('#libraryGrid').innerHTML=result.items.length?result.items.map(a=>card(a,true)).join(''):'<p>No matching reusable assets.</p>';$('#libraryPagination').innerHTML=Array.from({length:result.pages},(_,i)=>`<button class="secondary ${libraryPage===i+1?'active':''}" data-library-page="${i+1}">${i+1}</button>`).join('');await loadImages($('#libraryGrid'),result.items);}
  $('#assetForm').addEventListener('submit',async e=>{e.preventDefault();try{$('#saveState').textContent='Saving…';const input=formData();if(selected)service.update(selected.id,input);else await service.create(projectId,$('#assetFile').files[0],input,session.id);$('#assetDialog').close();$('#saveState').textContent='Saved';await render();toast(selected?'Metadata updated.':'Visual uploaded.');}catch(error){toast(error.message,true);$('#saveState').textContent='Save failed';}});
  $('#assetGrid').addEventListener('click',async e=>{const p=e.target.closest('[data-preview]'),d=e.target.closest('[data-delete]'),copy=e.target.closest('[data-duplicate]');try{if(p)await preview(p.dataset.preview);else if(copy){service.duplicateReference(copy.dataset.duplicate);await render();toast('Placement duplicated without copying the image.');}else if(d&&confirm('Remove this image from this lesson? It remains available in the Asset Library.')){service.detach(d.dataset.delete);await render();}}catch(error){toast(error.message,true);}});
  $('#openLibrary').onclick=async()=>{$('#libraryDialog').showModal();await library();};$('#librarySearch').oninput=()=>{libraryPage=1;library();};$('#libraryType').onchange=()=>{libraryPage=1;library();};$('#libraryGrid').onclick=async e=>{const b=e.target.closest('[data-reuse]');if(!b)return;try{service.reuse(b.dataset.reuse,projectId,{lessonId:projectId,placementType:'lesson',role:'supporting'});$('#libraryDialog').close();await render();toast('Asset reused without duplicating its image file.');}catch(error){toast(error.message,true);}};
  $('#uploadAsset').onclick=()=>openForm();$('#aiActions').onclick=()=>$('#aiDialog').showModal();$('#editMetadata').onclick=()=>{$('#previewDialog').close();openForm(selected);};$('#replaceFile').onchange=async e=>{try{await service.replace(selected.id,e.target.files[0],session.id);await preview(selected.id);await render();toast('Image replaced. Previous version preserved.');}catch(error){toast(error.message,true);}e.target.value='';};$('#assetVersions').onclick=()=>{const versions=service.versions(selected.id);$('#versionList').innerHTML=versions.map(v=>`<article class="version-item"><div><strong>Version ${v.version}</strong><small>${esc(v.kind)} · ${esc(v.fileName)} · ${new Date(v.createdAt).toLocaleString()}</small></div><button class="secondary" data-restore="${v.id}">Restore</button></article>`).join('');$('#versionsDialog').showModal();};$('#versionList').onclick=async e=>{const b=e.target.closest('[data-restore]');if(!b)return;try{service.restore(selected.id,b.dataset.restore,session.id);$('#versionsDialog').close();await preview(selected.id);await render();toast('Previous image version restored.');}catch(error){toast(error.message,true);}};
  $('#zoomPreview').onclick=()=>$('#largePreview').classList.toggle('zoomed');$('#fullscreenPreview').onclick=()=>$('#largePreview').requestFullscreen?.();$('#roleFilter').onchange=render;$('#lessonSearch').oninput=render;$('#assetPagination').onclick=e=>{const b=e.target.closest('[data-page]');if(b){page=Number(b.dataset.page);render();}};$('#libraryPagination').onclick=e=>{const b=e.target.closest('[data-library-page]');if(b){libraryPage=Number(b.dataset.libraryPage);library();}};document.addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(b)$('#'+b.dataset.close).close();});
  window.addEventListener('beforeunload',cleanup);$('#projectName').textContent=project.title;$('#backLesson').href=$('#lessonTab').href=`lesson.html?project=${encodeURIComponent(projectId)}`;$('#quizTab').href=`quiz.html?project=${encodeURIComponent(projectId)}`;$('#createVisualLink').href=`visual-generation.html?project=${encodeURIComponent(projectId)}`;$('#visualPlanLink').href=`visual-plan.html?project=${encodeURIComponent(projectId)}`;$('#educationalVisualsLink').href=`educational-visuals.html?project=${encodeURIComponent(projectId)}`;$('#assetType').innerHTML=Object.entries(LABELS).map(([v,l])=>`<option value="${v}">${l}</option>`).join('');$('#libraryType').innerHTML+=$('#assetType').innerHTML;$('#placementType').innerHTML=service.PLACEMENTS.map(v=>`<option value="${v}">${v.replaceAll('_',' ')}</option>`).join('');$('#assetRole').innerHTML=service.ROLES.map(v=>`<option value="${v}">${v.replaceAll('_',' ')}</option>`).join('');render();
})();
