(function(){
  'use strict';
  const V=TeachCurioVoice,VC=TeachCurioVoiceConversation,C=TeachCurioConversation,session=window.__voiceTestSession,$=q=>document.querySelector(q),actor=()=>({userId:session.userId,permissions:session.permissions||[]});
  let conversationId=null,voiceSessionId=null,unifiedSessionId=null,lastText='';
  const yes=v=>v?'Available':'Unavailable',label=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
  function setup(){
    const cap=V.capabilities(),conversation=C.createConversation({userId:session.userId,teachingMode:'solve_doubt',preferredLanguage:'english',ageGroup:'unknown'});
    conversationId=conversation.id;voiceSessionId=V.createSession({userId:session.userId,conversationId,inputLanguage:'english',outputLanguage:'english',mode:'browser'},actor()).id;unifiedSessionId=VC.start({userId:session.userId,conversationId,voiceSessionId,language:'english'},actor()).session.id;
    $('#capabilities').innerHTML=`<dt>Secure context</dt><dd>${yes(cap.secureContext)}</dd><dt>Microphone API</dt><dd>${yes(cap.microphoneApi)}</dd><dt>Browser recognition</dt><dd>${yes(cap.browserRecognition)}</dd><dt>Browser synthesis</dt><dd>${yes(cap.browserSynthesis)}</dd><dt>Online</dt><dd>${yes(cap.online)}</dd>`;
    $('#providers').innerHTML=`<dt>Speech-to-Text</dt><dd>${yes(cap.providerSpeechToText)}</dd><dt>Text-to-Speech</dt><dd>${yes(cap.providerTextToSpeech)}</dd>`;
    $('#providerNotice').textContent=V.providerStatus().message;
    $('#overallState').textContent=cap.browserRecognition||cap.browserSynthesis?'Browser fallback available':'Text-only fallback';fillVoices();bind();
  }
  function fillVoices(){const rows=V.availableVoices($('#outputLanguage').value);$('#voice').innerHTML='<option value="">Device default</option>'+rows.map(x=>`<option value="${x.id}">${x.displayName} · ${x.locale}</option>`).join('')}
  function state(v){$('#inputState').textContent=label(v);const active=['listening','speech_detected','processing_transcript'].includes(v);$('#listen').disabled=active;$('#stop').disabled=!active;$('#cancel').disabled=!active}
  async function permission(){V.consent(session.userId,{type:'microphone',granted:$('#consent').checked,remember:false,dataCategories:['microphone_audio_during_active_listening','confirmed_transcript']},actor());const out=await V.requestMicrophone(voiceSessionId,session.userId,actor());state(out.state)}
  async function listen(){if(!$('#consent').checked){state('permission_denied');return}V.consent(session.userId,{type:'microphone',granted:true,remember:false,dataCategories:['microphone_audio_during_active_listening','confirmed_transcript']},actor());const out=await VC.activate(unifiedSessionId,session.userId,actor(),{explicitActivation:true,maximumDurationMs:Number($('#duration').value),partialResults:true,onTranscript:e=>{$('#partial').textContent=e.partial?`Temporary: ${e.partial}`:''},onState:v=>{state(v);if(v==='transcript_ready'){const t=V.latestTranscript(voiceSessionId,session.userId);$('#transcript').value=t?.text||'';$('#partial').textContent=''}}});state(out.state)}
  async function speak(){lastText=$('#previewText').value;const settings={voiceId:$('#voice').value||null,rate:Number($('#speechSpeed').value),pitch:Number($('#speechPitch').value),volume:Number($('#speechVolume').value)};V.savePreference(session.userId,{personality:$('#personality').value,speakingRate:settings.rate,pitch:settings.pitch,volume:settings.volume},actor());const out=await V.speak(voiceSessionId,session.userId,lastText,actor(),settings);output(out.state)}
  function output(v){$('#outputState').textContent=label(v);$('#pause').disabled=v!=='speaking';$('#resume').disabled=v!=='paused';$('#stopSpeech').disabled=!['speaking','paused','resumed'].includes(v);$('#replay').disabled=!lastText}
  function bind(){
    $('#pauseSession').onclick=()=>{const value=VC.pauseListening(unifiedSessionId,session.userId,actor());$('#sessionState').textContent=label(value.session.state);$('#pauseSession').disabled=true;$('#resumeSession').disabled=false};$('#resumeSession').onclick=async()=>{const value=await VC.resumeListening(unifiedSessionId,session.userId,actor());$('#sessionState').textContent=label(value.session.state);$('#pauseSession').disabled=false;$('#resumeSession').disabled=true};$('#stopSession').onclick=()=>{const value=VC.stop(unifiedSessionId,session.userId,actor());$('#sessionState').textContent=label(value.session.state);$('#pauseSession').disabled=true;$('#resumeSession').disabled=true;$('#stopSession').disabled=true;$('#recoverSession').disabled=false};$('#recoverSession').onclick=()=>{const value=VC.recover(unifiedSessionId,session.userId,actor());$('#sessionState').textContent=label(value.session.state);$('#pauseSession').disabled=false;$('#stopSession').disabled=false;$('#recoverSession').disabled=true};$('#endSession').onclick=()=>{const value=VC.end(unifiedSessionId,session.userId,actor());$('#sessionState').textContent=label(value.session.state);document.querySelectorAll('button').forEach(button=>button.disabled=true)};
    $('#permission').onclick=permission;$('#listen').onclick=listen;$('#stop').onclick=()=>{VC.pauseListening(unifiedSessionId,session.userId,actor());state('stopped')};$('#cancel').onclick=()=>{V.cancelListening(voiceSessionId,session.userId,actor());VC.pauseListening(unifiedSessionId,session.userId,actor());$('#partial').textContent='';state('cancelled')};
    $('#inputLanguage').onchange=()=>VC.preferences(session.userId,{language:$('#inputLanguage').value},actor());$('#outputLanguage').onchange=fillVoices;$('#speak').onclick=speak;$('#pause').onclick=()=>{VC.pauseNarration(unifiedSessionId,session.userId,actor());output('paused')};$('#resume').onclick=()=>{VC.resumeNarration(unifiedSessionId,session.userId,actor());output('speaking')};$('#stopSpeech').onclick=()=>{VC.interrupt(unifiedSessionId,session.userId,actor());output('stopped')};$('#replay').onclick=speak;$('#runCommand').onclick=()=>{const result=V.interpretCommand($('#commandText').value);$('#commandResult').textContent=result.recognized?`${label(result.command)} · Local rule · No provider used`:'No supported command recognized'};window.addEventListener('pagehide',()=>{if(unifiedSessionId&&VC.snapshot(unifiedSessionId,session.userId,actor()).session.state!=='ended')VC.end(unifiedSessionId,session.userId,actor())});
  }
  document.addEventListener('DOMContentLoaded',setup);
})();
